### ISSUE TITLE
SQL syntax highlight for SQL log panel

### ISSUE THREAD

**Issue by lh-import** [cakephp/debug_kit#100]
Created by **[Predominant](https://github.com/predominant)**, 12th Dec 2009. *(originally [Lighthouse ticket #4](http://cakephp.lighthouseapp.com/projects/42880/tickets/4))*:
- - - -

(Reported by: ichikaway)

Hello.
I make SQL syntax highlight for SQL log panel. It's convenient to see SQL query.
I use GeSHi for syntax highlight.

(Source code diff)[http://thechaw.com/forks/ichikaway/debug_kit/commits/view/16e48f39ce72d6b09a3854ec878c5b69e1529daa]

Screenshot is attached.

thanks.

**Comment by markstory** [comment]
This is in the latest 3.x releases.
