### ISSUE TITLE
Undefined constant "CAKE_VERSION"

### ISSUE THREAD

**Issue by mehov** [cakephp/debug_kit#1008]
### Description

What I did
--

In my `templates/layout/default.php`:

```
<?php debug(\CAKE_VERSION); ?>
```

(Tried both with and without backslash)

What I got
--

> Undefined constant "CAKE_VERSION"

What I expected to get
--

`5.0.8`, as seen in DebugKit → Environment → CakePHP Constants

What's weird, any other CakePHP Constant I tried from the same DebugKit tab works fine.

This is a (relatively) freshly installed CakePHP skeleton app.

### CakePHP Version

5.0.8

**Comment by dereuromark** [comment]
Why not using Configure::version() as it is designed to be used for this?
https://github.com/cakephp/app/blob/9a7f511ed5f10dac993051cb1ecad79ab7cc93e5/templates/Pages/home.php#L84

**Comment by ADmad** [comment]
DebugKit is lying about `CAKE_VERSION` being a constant https://github.com/cakephp/debug_kit/blob/5.x/src/Panel/EnvironmentPanel.php#L77.

**Comment by mehov** [comment]
> Why not using Configure::version() as it is designed to be used for this? https://github.com/cakephp/app/blob/9a7f511ed5f10dac993051cb1ecad79ab7cc93e5/templates/Pages/home.php#L84

I just saw `CAKE_VERSION` in debug kit and believed it was a valid constant. It wasn't obvious that I should have been using `Configure::version()` instead. But now I know.

> DebugKit is lying about CAKE_VERSION being a constant

Thank you for clarification! If not much trouble, consider adding a tooltip to debug kit where it shows that constant saying `Configure::version()` is where the value really is? 

It is kinda confusing, but I'm not sure how much of a problem this is in absolute numbers, maybe not much

**Comment by ADmad** [comment]
Indded it should not be listed as a constant when it's actually not.
