### ISSUE TITLE
Enviroment get error in version 5.1.0

### ISSUE THREAD

**Issue by a-d-w-s** [cakephp/debug_kit#1025]
I update debug kit to 5.1.0 and if click enviroment tab, get error

```
Cake\Error\Debug\ArrayItemNode::__construct(): Argument #2 ($value) must be of type Cake\Error\Debug\NodeInterface, string given, called in F:\server\www.studiokbarrandov.cz\vendor\cakephp\debug_kit\src\View\Helper\ToolbarHelper.php on line 75
TypeError
```
`Error in: [CORE\src\Error\Debug\ArrayItemNode.php, line 40](phpstorm://open?file=F:\server\www.studiokbarrandov.cz\vendor\cakephp\cakephp\src\Error\Debug\ArrayItemNode.php&line=40)`

**Comment by LordSimal** [comment]
Can reproduce that and will provide a fix ASAP

**Comment by a-d-w-s** [comment]
Thanks for the quick fix!
