### ISSUE TITLE
RFC Make WhitespaceShell more flexible on folders to scan

### ISSUE THREAD

**Issue by lh-import** [cakephp/debug_kit#108]
Created by **[Ceeram](https://github.com/ceeram)**, 6th Oct 2011. *(originally [Lighthouse ticket #68](http://cakephp.lighthouseapp.com/projects/42880/tickets/68))*:
- - - -

Currently the shell scans all folders in ROOT, i suggest it should default to APP, and accept --path parameter for alternative paths:

http://bin.cakephp.org/view/543892456

**Comment by markstory** [comment]
Closing as this is quite old and no further requests have been made for it.
