### ISSUE TITLE
Debug trace in log file

### ISSUE THREAD

**Issue by lh-import** [cakephp/debug_kit#111]
Created by **Roman**, 18th Jan 2012. *(originally [Lighthouse ticket #87](http://cakephp.lighthouseapp.com/projects/42880/tickets/87))*:
- - - -

it would be very helpfull especialy if you are using *REST services* or you have some problem on production servers and you can not switch on debug on the view to *redirect* all debug information (Configure::read('debug') > 0) into some log file (the best into debug.log).

**Comment by markstory** [comment]
Closing as the toolbar now stores into a SQLite database that can be viewed in a separate request.
