### ISSUE TITLE
DebugKit not working Cake 2.4.1 

### ISSUE THREAD

**Issue by ghost** [cakephp/debug_kit#122]
Created by **Daniel Cortes**, 27th Sep 2013. _(originally [Lighthouse ticket #135](http://cakephp.lighthouseapp.com/projects/42880/tickets/135))_:

---

I've been trying to install DebugKit and I can't get it to work. I've followed all the instructions provided by DebugKit in ther github repository. Here are the steps I followed:
1. Install CakePHP and check installation.
2. Download the latest DebugKit 2.2.1 which is compatible with Cake 2.4
3. Copy the contents to the cake/plugins/DebugKit folder.
4. Called CakePlugin::load('DebugKit');  in app/Config/bootstrap.php
5. Included toolbar component by calling public $components = array('DebugKit.Toolbar'); within the class of AppController.php
6. Set Configure::write('debug', 1); in app/Config/core.php
7. Removed the 'sql_dump' element from my layout in app/View/Layouts/default.ctp

After doing all that I got the following errors:

Error: The application is trying to load a file from the DebugKit plugin

Error: Make sure your plugin DebugKit is in the app\Plugin directory and was loaded

What I have tried:
1. Not removing sql_dump element.
2. I made sure that the plugin call matches the DebugKit folder name.
3. Follow the instructions of this forum and others that solved the exact error but with earlier versions of both cake and debugkit.
4. Made a fresh reinstall of both Cake and DebugKit.

And still haven't solved the problem. BTW, I'm new to CakePHP so if I'm missing anything too obvious I apologize.

Here is an image that shows the structure of my project (it says Cake_2_0 but that's just the name of the folder, I'm using Cake 2.4.1), I'm using XAMPP as my server. Thanks,

Daniel

**Comment by shahab51021** [comment]
Hi, i encountered this same problem and got it solved by placing DebugKit folder in cakephp/app/Plugin  instead of cakephp/Plugin. Composer installs BebugKit in cakephp/Plugin folder but the framework need it in app/Plugin.

**Comment by mcontreras73** [comment]
Thanks @shahab51021, this work for me, I have CakePHP 2.6.1

**Comment by markstory** [comment]
@shahab51021 Both paths should be equivalent if both paths are the `Plugin` paths defined in `App`.
