### ISSUE TITLE
Config Item DebugKit.panels Not being used

### ISSUE THREAD

**Issue by bigasbespip** [cakephp/debug_kit#206]
I am attempting to create a panel for a plugin in cakephp 3.0. I am using the documentation in the read me, and the config item DebugKit.panels does not appear to exist. 

I get the error that it is not an array if I use the example code:
Configure::write(
    'DebugKit.panels',
    array_merge(Configure::read('DebugKit.panels'), ['MyCustomPanel'])
);

and if I explicitly set it with

Configure::write(
			'DebugKit.panels',
			['MyCustomPanel']
);

Nothing changes, I do not get any errors, and MyCustomPanel does not get loaded.

**Comment by JD-Robbs** [comment]
I, too, had trouble with this. Tried loading a custom Panel (residing in the app skeleton) as per the README instructions.

**Comment by markstory** [comment]
You need to configure the panel _before_ loading the plugin.
