### ISSUE TITLE
Option to use fullBase when loading css, js and image

### ISSUE THREAD

**Issue by bengalo** [cakephp/debug_kit#228]
I'm trying to implement a SSL via a shared proxy where I had to rewrite App.fullBaseUrl and those for css, js and images.
Some of my code only needed a 'fullBase' => true but there is no option to set this for the css and js + cake.icon load in debug kit..
I let you guys decide if this should be default but just an option for enabling using fullBase-paths would be nice.

Had no other choice than rewriting source now..

https://github.com/cakephp/debug_kit/blob/master/View/Elements/debug_toolbar.ctp#L28
https://github.com/cakephp/debug_kit/blob/master/View/Helper/HtmlToolbarHelper.php#L177
https://github.com/cakephp/debug_kit/blob/master/View/Helper/HtmlToolbarHelper.php#L186

First issue report I think, so be easy on me =)

**Comment by markstory** [comment]
To my knowledge this is working with current 3.x releases.
