### ISSUE TITLE
RFC - toolbar should reload periodically or on Ajax complete

### ISSUE THREAD

**Issue by lorenzo** [cakephp/debug_kit#261]
Given that firelog is gone, the toolbar should listen for sent Ajax requests or reload itself periodically in order to show data collected from xhr requests.

**Comment by Laykou** [comment]
Or at least there could be a refresh/reload button to reload only the Debug panel history. I know that I can right-click and refresh the iframe, but the button would be more convenient. :) Currently I am refreshing the page in browser.

**Comment by markstory** [comment]
A refresh button in the toolbar panel seems like a much lower effort solution :smile:

**Comment by JD-Robbs** [comment]
I tried doing that here, but, strangely, new requests don't appear although the panel is reloaded.

**Comment by JD-Robbs** [comment]
With "here", I meant [here](https://github.com/JD-Robbs/debug_kit/blob/patch-2/src/Template/Element/history_panel.ctp). :smile:

**Comment by markstory** [comment]
@JD-Robbs Because of how toolbar state is stored/loaded, you'd need to have additional controller end points to fetch the history state of the most recent request.

**Comment by JD-Robbs** [comment]
Thanks! I think because we'd need a new requestId, right?

**Comment by markstory** [comment]
@JD-Robbs Yes, take care not to also update all the other panels though, as the toolbar uses the requestId to fetch panels incrementally.

**Comment by zoghal** [comment]
@markstory : with this solution can monitor any ajax request

```
(function() {
    var proxied = window.XMLHttpRequest.prototype.open;
    window.XMLHttpRequest.prototype.open = function() {
        console.log( arguments );
        afterAjaxComplete() //run your code here
        return proxied.apply(this, [].slice.call(arguments));
    };
})();
```

**Comment by markstory** [comment]
@zoghal Good idea, we will still need to figure out how to get the latest request id to rebuild the panel, but that is a good start.

**Comment by zoghal** [comment]
@markstory  simple way : request id must be adding in header to response,
new soulotion : 
Now when we get request ID. Create a new request by iframe and show Results.
 api extention in broswers can better monitoring for any request.

so we need simple extension to monitor any request and get results and showing into extension panel( no inject in body page).
We can even take advantage of WebSocket or ServiceWorker for the realtime logger and ... :smiling_imp: .

**Comment by lorenzo** [comment]
I will work on this
