### ISSUE TITLE
3.0 use PDO breaks cake console

### ISSUE THREAD

**Issue by Soswald** [cakephp/debug_kit#266]
In commit 229403b116f7b23f3fe8ed10f037169fe83774fa the introduced "use PDO" breaks the Cake Console.
Removing it gets everything working again.

Greetings

**Comment by 2ndGAB** [comment]
Hello,
I have the same issue in 3.0.4 on ubuntu server and existing `use \PDO` causes the same issue.
Removing it smakes the error disappearing. Don't now if that cause something to not work...
