### ISSUE TITLE
DebugKit breaks while trying to save state to Cache

### ISSUE THREAD

**Issue by carolinamassae** [cakephp/debug_kit#283]
I'm using ToolbarComponent in Windows and recently DebugKit began to break in all requests while trying to write state using FileCacheEngine.

The full stack trace /error can be viewed here: http://jsfiddle.net/d8qrkuk1/.

I just love using DebugKit and since it's breaking the application I had to disable it, it would be very nice if this could be fixed, if you need more info I can pass.

P.S. Sorry for the poor english.

**Comment by markstory** [comment]
Closing as this is quite old and the 2.x branch isn't seeing much action these days.
