### ISSUE TITLE
SQLite database should keep only the most current requests

### ISSUE THREAD

**Issue by lorenzo** [cakephp/debug_kit#302]
Today I noticed that I had a 1Gb sqlite file from debugkit in my project. I think we should periodically delete ancient request data

**Comment by dereuromark** [comment]
+:100:

**Comment by markstory** [comment]
I use `rm` :trollface:

**Comment by markstory** [comment]
Does clearing everything older than 1 month every 1 in 100 requests sound reasonable?

**Comment by dereuromark** [comment]
I think everything older than a day would even be reasonable, as you wouldn't know what that data was about then a day later anyway.

**Comment by lorenzo** [comment]
Or just keep a cap of ~2000 requests. Deletion can happens using a probability divisor so it does not happen on each request

**Comment by markstory** [comment]
I ended up having to use date ranges, as deleting with limit offset is not well supported by the query builder.

**Comment by markstory** [comment]
See #303
