### ISSUE TITLE
DebugKit -- security issue.

### ISSUE THREAD

**Issue by hellosmith420** [cakephp/debug_kit#306]
Dear Debugkit Creator,
Debugkit is a very good tool. But in your instruction to install, you should include the uninstall process also. Because, is debug mode sensitive data are visible. I have hide the debugkit, but the cache is accessiable, `http://example.com/debug_kit/toolbar_access/history_state/2`. From here hackers stolen my amazon credential and made unwanted access.

**Comment by AD7six** [comment]
Thanks for linking to a pr0n site.

Why did you have debug kit enabled on a production site?

OR Why did you have a live app with debug = true?

OR what steps are required to reproduce your scenario with debug kit loaded but disabled?

**Comment by AD7six** [comment]
Infact:

> i[n] debug mode sensitive data are visible.

You should **never** enable debug mode in production, and in principle debug kit shouldn't be installed in production either.

Closing as if you _do_ enable debug mode what you describe is to be expected.
