### ISSUE TITLE
Optimization: MySQL kills query, deadlock detected / transaction timeout.

### ISSUE THREAD

**Issue by sarrala** [cakephp/debug_kit#309]
Is there anything that could optimize following debugkit query:

Too often it runs in preparing state over 50 seconds (that's my query-kill timeout, I'll bet it would be a lot more), maybe adding some carefully picked indexes would help here.

```sql
DELETE FROM panels WHERE request_id not in (SELECT Requests.id AS `Requests__id` FROM requests Requests)
```

I think that main problem is `request_id not in (...over 14000 rows...)`.

Just adding `ADD INDEX ("request_id")` improves it a bit but it does not remove "not in" bottleneck.

Maybe adding automagick cleanup on requests table helps?

**Comment by markstory** [comment]
I can add an index on request_id if that would help. MySQL is pretty bad at subqueries though. Is there a reason you're not using SQLite for the debugkit db?

**Comment by markstory** [comment]
Closing as I have a pull request up to add an index which should improve performance in MySQL.
