### ISSUE TITLE
require pdo_sqlite in composer.json

### ISSUE THREAD

**Issue by bakroistvan** [cakephp/debug_kit#312]
Hi

I just started to be know each other with cakephp 3.
After installing everything with composer I couldn't find why the debugkit isnt loading w/ cakephp.

After
```
composer create-project --prefer-dist -s dev cakephp/app first3
```
could be a msg about it, or maybe one can update the composer.json with this

```
"require-dev": {
        "ext-pdo_sqlite": "*"
}
```

**Comment by markstory** [comment]
You don't _need_ sqlite. The readme tells you how to configure the database if you don't have sqlite. Adding sqlite to suggests might help though.

**Comment by markstory** [comment]
Closing as #313 is open now.
