### ISSUE TITLE
Could not parse version constraint while installing using composer on cake 3.0

### ISSUE THREAD

**Issue by neohunter** [cakephp/debug_kit#317]
I was trying to install it on a cake 3.0 fresh installation as suggested on the wiki but got an error:

```
$ composer require cakephp/debug_kit "3.0.*-dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [RuntimeException]
  Could not load package zendframework/zendframework in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0: I
  nvalid version string "^1.0"

  [UnexpectedValueException]
  Could not parse version constraint ^1.0: Invalid version string "^1.0"

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [packages1] ... [packagesN]
```

**Comment by ADmad** [comment]
There's no `3.0.*-dev` any more. Use `~3.0`

**Comment by ADmad** [comment]
I have fixed the README

**Comment by neohunter** [comment]
Thanks for your quick reply! 

I have one question if you dont mind, why it says zendframework/zendframework ? what it have to do with debugkit?

**Comment by ADmad** [comment]
CakePHP does not use any component from zendframwork so no idea what you are referring to. If you are new to CakePHP I suggest you following the [installation guide](http://book.cakephp.org/3.0/en/installation.html) to get a fresh CakePHP app skeleton which includes DebugKit.
