### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by thaJeztah** [cakephp/debug_kit#319]
I just noticed that the repository (both the 3.x and 2.x branches) is missing a license.

**Comment by ceeram** [comment]
all classes have a docblock on top, which includes MIT license

**Comment by lorenzo** [comment]
It is also here https://github.com/cakephp/debug_kit/blob/master/composer.json#L7

**Comment by ravage84** [comment]
:+1: on adding the MIT LICENSE.txt in both branches.

**Comment by thaJeztah** [comment]
Yes; I noticed the MIT reference in those files,  but adding a license.txt would be nice (for completenes) :smile:

**Comment by markstory** [comment]
Fixed in 806e25547979d0b7f6409b805f4779dd7b9beac1 and a5ae1e18a0707612207da1a97161a4ea9f446ad1

**Comment by thaJeztah** [comment]
Oh thanks, @markstory! I'll remove it from my to-do list :smile:
