### ISSUE TITLE
Slow cache read translation

### ISSUE THREAD

**Issue by entheosweb** [cakephp/debug_kit#333]
Hi, 
today I started a new project with Cake3, and have a problem with DebugKit. When I load any url (eg. a basic users index made with bake) the page takes about 10 seconds for being displayed.

From the Timer panel you can see this operation taking more than 10 seconds
Cache.read translations.debug_kit.it_IT	10.861,66

![schermata 2015-05-07 alle 00 54 27](https://cloud.githubusercontent.com/assets/12187516/7505566/3eca165c-f454-11e4-8e63-124b79365c77.png)

I used File cache, checked the folder permissions, then tried again with Memcached as caching engine but nothing changed. SqlLite is installed, and I also tried creating a database connection for debug_kit storage, but nothing changed.

Tried to delete the DebugKit folder and reinstall with Composer.

Disabling DebugKit Plugin loading solves the problem.

Any hints about what could cause the problem? Thanks

**Comment by markstory** [comment]
DebugKit has no italian translation, perhaps the missed translation is the issue? I've not seen that kind of slowdown before though.

**Comment by entheosweb** [comment]
Tried to switch default_locale to en_US but the issue still remains:

```
Cache.read translations.debug_kit.en_US	11,755.31
```

**Comment by entheosweb** [comment]
Debugging, I found that it's not a DebugKit related issue, but some kind of slow down during the dispatch of "Controller.initialize" event. Happens only when at least one plugin is loaded. Still don't know how to fix it.
