### ISSUE TITLE
Variables tab failing to load when using indexBy('id);

### ISSUE THREAD

**Issue by ttgeo1** [cakephp/debug_kit#338]
I have loaded a model through a controller action.

 $this->loadModel('StatTotals');
 $statTotals = $this->StatTotals->find('all');
 $statTotals = $statTotals->indexBy('id');
 $this->set('statTotals',  $statTotals);

However when I go to see $statTotals in the variables tab, it just stalls. The cake logo just keeps spinning.

But when I debug $statTotals->indexBy('id')->toArray() it seems to be working fine. I asked on cakephp irc but it was suggested that I make a ticket.

**Comment by markstory** [comment]
I took a look and this seems to have been resolved in or before 3.2.5
