### ISSUE TITLE
Variables tab displaying Query object rather than data

### ISSUE THREAD

**Issue by davidyell** [cakephp/debug_kit#339]
**What is happening**
I set data to the View and then open the debugkit panel, hit Variables and I see my variable. I click on it to expand it and I get the query object, http://i.imgur.com/yQZmkgE.png

**What I'm expecting**
I'd like to see the data returned by the query.

Using 3.1.3

**Comment by markstory** [comment]
This is probably a result of my recent changes trying to _fix_ the variables panel. Perhaps Query's should continue to be special cased.

**Comment by davidyell** [comment]
Erm, if I'm using version 3.1.3 and you've added it to the 3.1.2 milestone, I think you might need a new milestone :wink:

**Comment by markstory** [comment]
Fixed the milestone, I missed that when I did the release.

**Comment by dereuromark** [comment]
But https://github.com/cakephp/debug_kit/releases/tag/3.1.3 is also released already.

**Comment by markstory** [comment]
Darnit.

**Comment by markstory** [comment]
Fixed with #342
