### ISSUE TITLE
sort variables

### ISSUE THREAD

**Issue by Graziel** [cakephp/debug_kit#345]
i find that having many viewVars can be annoying to find in debugKit variables, it would be easy to implement ksort after https://github.com/cakephp/debug_kit/blob/master/src/View/Helper/ToolbarHelper.php#L77-L79 as simple
```
if (is_array($values)) {
      ksort($values);
}
```
downside is some users can rely on current setting of non ordered results
(ie to check the ->order in ->find('list') )

**Comment by markstory** [comment]
We could sort just the top level variable scope and not recursively through the variables.

**Comment by dereuromark** [comment]
@markstory I am hesitant to upvote that because the order of the variables usually tells you when it was added. Mixing that up might lose that implicit information...

**Comment by ravage84** [comment]
:+1:  to JS sorting

**Comment by markstory** [comment]
Good point @dereuromark knowing the approximate insert order is handy.

**Comment by Graziel** [comment]
another approach would be to add button which adds cookie via js, reloads the page and change condition to 
```
if (is_array($values) && $cookie_sort_set) {
      ksort($values);
}
```
this way it will remember it so you wont have to click every time you load panel to sort via js and if you dont want sort just delete the cookie again via js and refresh the panel

**Comment by dereuromark** [comment]
Sounds like a good idea to me.

**Comment by markstory** [comment]
I don't think I understand this well enough to build it. Someone will have to do a pull request :smile:

**Comment by markstory** [comment]
Closing as there is a pull request open.
