### ISSUE TITLE
Toolbar not loading

### ISSUE THREAD

**Issue by gjgjwmertens** [cakephp/debug_kit#348]
I am running CakePHP 3 on nginx.
On first install the debug_kit could not load debug_kit/js/toolbar.js. I fixed this by adding debug_kit/webroot as debug_kit to my site root.
Now the iframe tries to load debug_kit/toolbar/id.... but fails, there is no toolbar directory in debug_kit/webroot

**Comment by markstory** [comment]
Sounds like your rewrite rules aren't working correctly, or there is another issue with URL rewriting. Try using the built-in server and see if you have the same issue `bin/cake server -p 8080`, and then go to `localhost:8080` in your web browser.

**Comment by gjgjwmertens** [comment]
Thanks for the feedback. Solved it with configuration changes in the URL rewrite of nginx.
    if (!-e $request_filename) {
        rewrite ^/(.+)$ /home/public_html/app.domain.com/private/cake/$1 last;
        break;
    }

sorry to have bugged you with this...
