### ISSUE TITLE
Simpler DebugKit Sql query out

### ISSUE THREAD

**Issue by markstory** [cakephp/debug_kit#349]
_From @cmann1 on June 11, 2015 13:2_

Perhaps an option to output simpler queries could be helpful when debugging, currently if you open `Sql Log` tab your queries will be extremely verbose:
```sql
SELECT Languages.id AS `Languages__id`, Languages.name AS `Languages__name`, Languages.code AS `Languages__code`, Languages.iso_code AS `Languages__iso_code`, Languages.is_default AS `Languages__is_default`, Languages.deleted AS `Languages__deleted` FROM languages Languages WHERE deleted = 0 ORDER BY Languages.id desc LIMIT 20 OFFSET 0
```
All of the `Table.col AS Table__col` can be difficult to look through and, in my experience at least, most of the time is not needed.
Maybe the debug kit could format the query, stripping out unnecessary information such as the default `AS` statements.
The above statement would be a lot easier to read and still provide the same information if the `SELECT` part was just: `Languages.id, Languages.name, ...`

If you need to see the original full query maybe it could be shown when you hover over it?

_Copied from original issue: cakephp/cakephp#6784_

**Comment by markstory** [comment]
I don't really know if that is a good idea. SQL is non-trivial to parse and manipulate, and logging different SQL than was actually executed seems like it could cause as many problems as it solves.

**Comment by markstory** [comment]
_From @ndm2 on June 11, 2015 20:28_

I'd rather like to optionally see the queries in a highlighted, maybe even formatted fashion, or an easier way too hook into the output generation.

For now I've created a plugin with a custom panel extending `SqlLogPanel`, which grabs the `DebugLog` logger, and uses a copy of the `sql_log_panel.ctp` element, where the query output is being formatted using https://github.com/jdorn/sql-formatter.

While this works, it would be nice if something similar would be supported out of the box, or easier to achieve, ie without having to "reimplement" too much code, namely the element in this case.

**Comment by markstory** [comment]
Formatting the queries sounds like a good option.

**Comment by markstory** [comment]
I gave using jdorn/sql-formatter a spin. The end result looks like:

![screen shot 2015-07-25 at 22 10 05](https://cloud.githubusercontent.com/assets/24086/8892192/083e90e0-331a-11e5-8d69-973018ad4b46.png)

The syntax highlighting uses garish colours which don't look good with the rest of DebugKit.

**Comment by ndm2** [comment]
The colors can easily be customized, static properties aren't that nice tough.

Just for example purposes, especially the non-formatted variant would need something with better contrast.

```php
SqlFormatter::$quote_attributes = 'style="color: #259B24;"';
SqlFormatter::$backtick_quote_attributes = 'style="color: #009688;"';
SqlFormatter::$number_attributes = 'style="color: #D76B6B;"';
SqlFormatter::$word_attributes = 'style="color: #8A7E57;"';
SqlFormatter::$comment_attributes = 'style="color: #aaa;"';
SqlFormatter::$pre_attributes = 'style="color: #594C20; background-color: white;"';
```

![formatted-sql-log-wrapped](https://cloud.githubusercontent.com/assets/5031606/8892341/073a4af6-3354-11e5-875d-75647665c626.png)

![formatted-sql-log](https://cloud.githubusercontent.com/assets/5031606/8892342/0c4cba9c-3354-11e5-8322-fd3284c31ea9.png)

**Comment by lorenzo** [comment]
That looks great to me

**Comment by AD7six** [comment]
I like this too. I'm not sure yet but the whitespace changes are possibly more useful (to me) than the formatting changes.

> Maybe the debug kit could format the query, **stripping out unnecessary information such as the default AS statements**.

Just in case: I definitely do not want anything more significant than whitepsace and formatting to be applied.

**Comment by markstory** [comment]
@ndm2 Cool, I didn't see the color options in the docs.

So do we want coloured output or just formatting?

**Comment by lorenzo** [comment]
I'm more interested in colors than formatting :P

**Comment by markstory** [comment]
Closing as there is a pull request up that can be tweaked further.
