### ISSUE TITLE
DebugKit update required for 3.x

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#350]
With the view updates the debug kit is now broken:

    Deprecated (16384): Controller::$viewPath is deprecated. Use $this->getView()->viewPath() instead. [CORE/src/Controller/Controller.php, line 322]

    Deprecated (16384): Controller::$layout is deprecated. Use $this->getView()->layout() instead. [CORE/src/Controller/Controller.php, line 322]

The result is a non-functional debug kit toolbar.

PS: The problem here is also that once you correct it, all apps that have not upgraded the core but use a `*` restraint on the debug kit will blow up.
I wonder if the current "deprecation notice throwing" strategy is a good one, especially regarding the non-debug (important for production) plugins.

**Comment by markstory** [comment]
Deprecation warnings are easily silenced. I think we should continue using them as it is an effective and  direct way for us to indicate deprecations.

**Comment by ADmad** [comment]
I agree with @markstory

**Comment by ADmad** [comment]
I have create a [3.2](https://github.com/cakephp/debug_kit/tree/3.2) for cake 3.1 compatibility.

**Comment by markstory** [comment]
@ADmad Thanks. I'll cap the current debugkit versions to only accept 3.0.x instead of `~3.0`.

**Comment by djamesfar** [comment]
3.1-RC1 DebugKit throwing deprecation warnings when Variables panel selected:
```
 Property $layout is deprecated. Use $this->viewBuilder()->layout() instead in beforeRender(). [CORE/src/View/ViewVarsTrait.php, line 98]
```

**Comment by antograssiot** [comment]
@djamesfar you should use 3.2 branch of debugkit with cake 3.1

**Comment by markstory** [comment]
This has been fixed now.
