### ISSUE TITLE
Debugkit missing...

### ISSUE THREAD

**Issue by joshuajb123** [cakephp/debug_kit#352]
Its working after i clean install cakephp from composer then I change something in the app config.... now its missing i dont know why....

chrome console:
GET http://localhost/collab/debug_kit/js/toolbar.js net::ERR_CONTENT_DECODING_FAILED

**Comment by joshuajb123** [comment]
Got this figured...

My problem is I install cake in:
http://localhost/site1/

i fixed it when making a virtual host.
http://site1

hope it helps the others..

**Comment by dereuromark** [comment]
I also do that sometimes and it works. But a vhost is sure the better solution. Closing then.
