### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by Graziel** [cakephp/debug_kit#363]
ive added some enhancements to debug_kit for my personal use but i would like to share:
- variables now have title with path
- variables can now be turned to JSON with a button click
- variables can now display line, file and function where they were set if its supplied with viewVarsBT(for ease of doing that added DebugKitTrait)
- variables are now expandable when clicking on `<strong>` tag instead of whole line and only if it has some sublist to show
- variables now have their class name when is_object - with exception to Query cause of bunch of issues with unserializable
- variables using sort are now deep sorted
- Generated Models in sql log now shows - line, file, function when used via loadModel (when DebugKitTrait is used and only when loaded with loadModel)
- fixed missing validation errors
- moved object conversion from shutdown event to ToolbarHelper
- added count of Traversable objects and arrays
- Query object now uses __debugInfo instead of toArray()
- panel title bar is now always on top
- caching of panel content

the changes can be found in https://github.com/Graziel/debug_kit/tree/Variables 
write here if you are interested in merging of any of these changes

**Comment by markstory** [comment]
> * fixed missing validation errors
> * moved object conversion from shutdown event to ToolbarHelper
> * variables now have their class name when is_object - with exception to Query cause of bunch of issues with unserializable
> * added count of Traversable objects and arrays

These all sound interesting.

The traits and JSON I'm less sure about, but I think trying your branch out might show how useful they could be.

**Comment by Graziel** [comment]
for me looking at larger data sets is easier via JSON than clicking and expanding each level of tree in debug_kit but it could be also done using print_r or any other function, also it might help others with copy paste to gist / pastebin

about the trait i like to know quickly where variable is comming from (it also shows in 'title' where it was changed) but again it might be personal thing

**Comment by josegonzalez** [comment]
@markstory I did something similar to that trait thing except I override the `AppModel::find()` to add it via the logging toolbar.

**Comment by markstory** [comment]
I can totally see how knowing where view variables are being set is useful. I don't have an idea in mind that is better than the trait, but I still find it kind of funny feeling.

**Comment by dereuromark** [comment]
ping @Graziel 
Any PR here for some of those topics maybe?

**Comment by othercorey** [comment]
Closing since the user hasn't responded or opened PR with their changes.
