### ISSUE TITLE
2.2.*: Composer installs DK it in root 'Plugin' directory, instead of 'app/Plugin'.

### ISSUE THREAD

**Issue by nelson6e65** [cakephp/debug_kit#365]
For version **2.2.x**, composer install it in `/Plugin/DebugKit`, and this path is not used in app, because Cake (2.7) throws errors: `Make sure your plugin DebugKit is in the app/Plugin directory and was loaded`.

**How can I use it, installing DebugKit via composer?**

**Comment by markstory** [comment]
Where is your composer.json file? It should be in `app/composer.json` not in the root directory.

**Comment by nelson6e65** [comment]
Oh... In root, as I downloaded from cakephp *.zip.

I just ran `composer update`  in root directory.

**Comment by rchavik** [comment]
"your project's composer.json" would be `app/composer.json`.

**Comment by nelson6e65** [comment]
@rchavik I guest... The project composer.json is located in the root. In CakePHP 2.7.3 download, the composer.json has this: 

```js
"require-dev": {
    "phpunit/phpunit": "3.7.*",
    "cakephp/debug_kit" : "2.2.*"
},
```

Then, `composer update` installs DebugKin in root directory. I guest I must create **another** `*.json` in `app/composer.json.` and run there. Should be clarify in instructions about composer install then:

"[...]composer knows to install it inside your **`/Plugin`** directory, rather than in the usual vendors file. It is recommended that you add **`/Plugin/DebugKit`** to your .gitignore file."

to 
"[...]composer knows to install it inside your **`/app/Plugin`** directory, rather than in the usual vendors file. It is recommended that you add **`/app/Plugin/DebugKit`** to your .gitignore file."

**Comment by rchavik** [comment]
> I guest... The project composer.json is located in the root.

Not really. I'd like to think the `composer.json` in `ROOT` is cakephp's.  It defines cakephp's dependencies, not your application's.

You application will have a different set of dependencies, and you should set it in your `app` dir.

Also, you might want to have a look/use https://github.com/FriendsOfCake/app-template to base your app of.

**Comment by nelson6e65** [comment]
I see... Thanks.
