### ISSUE TITLE
Toolbar tabs autoclose

### ISSUE THREAD

**Issue by davidyell** [cakephp/debug_kit#367]
**What I did**
Used `"cakephp/debug_kit": "2.2.*@dev"` with Cake `2.7.3`. Loaded a page, clicked the variable tab, expanded a variable, then clicked the grey bar at the bottom of the drop down.

**What happened**
The bar vanishes. Then it will display and hide only when hovering over the toolbar. 

**Workaround**
You have to click the toolbar tab again a few times until it becomes 'sticky' again.

**Comment by markstory** [comment]
I'll see if I can reproduce this.

**Comment by davidyell** [comment]
Annoyingly it doesn't happen 100% of the time!

**Comment by markstory** [comment]
Pull request is up now.
