### ISSUE TITLE
Unserialize() error

### ISSUE THREAD

**Issue by tartempion34** [cakephp/debug_kit#369]
Hi all,

I Want to use debug_kit, but Variables, SQL logs and history pannels had errors.
When I display these pannels, I have this error:

Notice (8): unserialize(): Error at offset 214 of 218 bytes [ROOT/vendor/cakephp/debug_kit/src/Controller/PanelsController.php, line 87]

Is there a method for fixing this problem?

Thanks

**Comment by markstory** [comment]
You can remove the debugkit sqlite database. This will remove all the tracked panel data, but should fix the error.

**Comment by tartempion34** [comment]
@markstory  Thanks for your answer. I removed the SQLite database and I configured DebugKit for working with a PostreSQL database, but I have this problem again.

**Comment by markstory** [comment]
Ok, without knowing what data is triggering the unserialize issue there isn't much I can do.

**Comment by tartempion34** [comment]
How can I know what data is triggering this issue?

**Comment by markstory** [comment]
I would start by looking at the serialized data, and seeing which bytes the error comes from.

**Comment by tartempion34** [comment]
Okay, 
Code line 87: $this->set(unserialize($panel->content));

in the panel "History":
error: Notice (8): unserialize(): Error at offset 59 of 63 bytes [ROOT/vendor/cakephp/debug_kit/src/Controller/PanelsController.php, line 87]
Data in $panel->content: 'a:1:{s:8:"requests";a:10:{i:0;O:15:"Cake\ORM\Entity":10:{s:14:"'

In the panel "SQL Logs":
error: Notice (8): unserialize(): Error at offset 128 of 132 bytes [ROOT/vendor/cakephp/debug_kit/src/Controller/PanelsController.php, line 87]
Data in $panel->content: 'a:2:{s:6:"tables";a:1:{s:11:"DroitsUsers";s:11:"DroitsUsers";}s:7:"loggers";a:1:{i:0;O:30:"DebugKit\Database\Log\DebugLog":5:{s:11:"'

**Comment by markstory** [comment]
Well that data looks like an incomplete serialized object.

**Comment by tartempion34** [comment]
Ans it's a problem

**Comment by lorenzo** [comment]
What database are you using for debugkit?

**Comment by lorenzo** [comment]
Ah, I just read it is postgres. Make sure to make the fields big enough so they can contain all the serialized data

**Comment by tartempion34** [comment]
@lorenzo thanks for your answer. I checked the database, there is no limit on charvar fields. Anyway, tables was created by debugKit so I don't think it creates too small fields.
I removed the postgres connection for using sqlite, and it works. I think I will stay on this database.

Thanks for your answers
