### ISSUE TITLE
Installation instructions are aimed at experienced/expert CakePHP users

### ISSUE THREAD

**Issue by etfb** [cakephp/debug_kit#372]
Picture if you will: a new CakePHP user, with a shiny new installation of PHP and Apache, installs CakePHP 2.x (because he happens to be working somewhere that requires 2.x for historical reasons).  Once he gets the salt sorted and the database configured, Cake tells him that it might be a good plan to install debug_kit.  Fair enough; off to github to grab it.  There's even an Installation section in the README, so that's nice. And what does it say?

> Install the plugin with composer from your CakePHP Project's ROOT directory (where composer.json file is located)

No explanation of what "composer" [sic] is, and it's not spelt with a capital C so it's not immediately obvious that it's a product or tool.  A link to a Composer HOWTO would seem to be the absolute bare minimum requirement here.

> Load the plugin

A line of what might be PHP code here.  The use of [] instead of array() is a recent innovation and one that not every newbie or even most tutorials will be aware of, and the :: makes it look more like C++ than anything. But more worryingly, there's no mention of where this line should be inserted!

> Set 'debug' => true, in config/app.php.

I was going to say that this, at least, is clear -- but the directory names are usually in initial-caps (Config, not config) and I can't see any file called app.php.  Is it maybe in debug_kit rather than in Cake?  I don't know; I haven't downloaded it yet.

OK: the problem is simple,  You have a product that's advertised for use by newbs, before they've even created their first Cake app.  You have installation instructions that are not adequate for newbs, that require knowledge and experience (and more than a little proofreading).

Suggestion: either fix the instructions, or advise the Cake project to postpone recommending debug_kit until after the rest of the tutorials.

**Comment by etfb** [comment]
Note that the README for the 2.2 branch does solve these problems, so if the CakePHP intro page had linked to the correct branch, I never would have discovered that the master branch doesn't. That doesn't let you off the hook, but it does give you an example to work from.

**Comment by ADmad** [comment]
Just above the "Installation" section the README of master branch there's a "DebugKit for CakePHP 2.x" section which states: 

> If you want DebugKit for your 2.x application, you can use the latest 2.2.y tag or the 2.2 branch.

Suggestion:  Please don't skip over sections of readme.

**Comment by etfb** [comment]
That's a good fix for the immediate problem; bravo!

Now of course the same instructions that exist in the 2.2 branch need to be imported to the master.  Note that they're missing the instruction to call "composer install", and unless I made a typo they also don't create the right plugin directory - it should be "plugins", not "plugin".

**Comment by etfb** [comment]
Additional suggestion: assume that everyone will skip to the Installation section.  Put it at the top, and include all relevant info.  The most commonly broken rule in all Free/Libre/Open Source projects is this: do not put a bouncer on door you want everyone to enter.

**Comment by ravage84** [comment]
I tried to improve the installation instructions for 3.x and 2.2.x with the PRs mentioned above.

**Comment by etfb** [comment]
Looks good.  Nice!

**Comment by markstory** [comment]
Closing as the README in both versions has been improved.

**Comment by etfb** [comment]
Agreed. That's much better.
