### ISSUE TITLE
Plural of virus isn't really viri

### ISSUE THREAD

**Issue by etfb** [cakephp/debug_kit#373]
I'll quote chapter and verse from a dictionary if required, though I don't think it should be necessary.  lib/Cake/Utility/Inflector.php in the latest 2.x build (maybe in 3.x too; I didn't check) includes "virus" as one of the words that has its "us" changed to "i".  It should be left out of the regexp (line 50, starting with '/(alumn|bacill|cact' etc) since the correct English plural of virus is viruses, so will be caught by the catch-all on line 51.

Apropos of nothing: I love that this file exists, and that it's so comprehensive.  Oxen! Testes! Lice!  Someone has gone to a lot of trouble, and appears to have had a lot of fun.  Excellent work all round!

**Comment by etfb** [comment]
Here's a polite explanation of the error:

http://dictionary.reference.com/help/faq/language/g63.html

**Comment by dereuromark** [comment]
See http://sandbox3.dereuromark.de/sandbox/inflector?string=virus
This is also in the 3.x branch.
But you should open a ticket @ cakephp/cakephp (the actual framework), not some debug plugin of it.

**Comment by etfb** [comment]
You're right, of course. I'll delete this and put it in the right place. My apologies!
