### ISSUE TITLE
toolbar.js throws errors if CORS is used

### ISSUE THREAD

**Issue by plopzer** [cakephp/debug_kit#379]
Error in javascript console:

    Refused to get unsafe header "X-DEBUGKIT-ID"
        logAjaxRequest @ toolbar.js:46

**Comment by markstory** [comment]
How can someone reproduce this issue?

**Comment by plopzer** [comment]
If you're using apache, on the server serving the ajax request, send the header:

    Access-Control-Allow-Origin: http://example.com

where example.com is the server where the request is originating from

**Comment by plopzer** [comment]
It looks like maybe setting the following header might fix it. I'll try it tomorrow.

    Access-Control-Expose-Headers: X-DEBUGKIT-ID

**Comment by markstory** [comment]
Looks like Firefox doesn't have an issue with getting 'unsafe' headers. However, chrome does.

**Comment by plopzer** [comment]
I tried both Access-Control-Expose-Headers and Access-Control-Allow-Headers but couldn't get either to work. I think there is supposed to be a way to specify the headers that gets sent in pre-flight?

**Comment by markstory** [comment]
The issue is that the domain responding to the CORS request has to use `Access-Control-Expose-Headers` and there is 0 chance that this will always be the case. Given that chrome logs an error and doesn't raise an exception, it might be best to ignore this error unless you also control the domain you're doing CORS requests to.

I was able to fix the error by adding `$this->response->header(['Access-Control-Allow-Header' => 'X-DEBUGKIT-ID']);` to the domain responding to the CORS request.

**Comment by jtraulle** [comment]
Hi,

Sorry to reopen this but I am facing the exact same issue
```
Refused to get unsafe header "X-DEBUGKIT-ID"
(anonymous) @ toolbar.js:62
```

Any idea ?

**Comment by palanza** [comment]
up same error

**Comment by lorenzo** [comment]
@palanza check this answer https://github.com/cakephp/debug_kit/issues/379#issuecomment-146399825

**Comment by jtraulle** [comment]
Thanks @lorenzo ; understood :wink:

**Comment by VARGA-Peter** [comment]
`$this->response->header(['Access-Control-Allow-Header' => 'X-DEBUGKIT-ID']);`

Can I ask for more detailed code which is running under CakePHP 4.1.4. I tried `$this->response->withHeader('Access-Control-Allow-Header', 'X-DEBUGKIT-ID');` in `AppController.php->initialize()`. Nothing helps. When I run Google Maps API requests I see always the error in the console. Thx

**Comment by ndm2** [comment]
As @markstory wrote, that's only for when you control the receiving server, you cannot do anything about it when you're issuing requests to a 3rd party service that you don't control, if the don't expose the `X-DEBUGKIT-ID` header in `Access-Control-Allow-Header`, then you can't do anything about it.

The "error" message that chrome shows here is really non-error, I don't know why they've not chosen a notice instead. AFAICT you can safely ignore it. There's no problem in your code, it won't halt JS execution or anything, it just means `XmlHttpRequest.getRequestHeader()` tried to access something that it's not allowed to, and the method will return `null`.

Debug Kit could probably avoid the problem in most cases by checking all response headers first whether the Debug Kit header is present in the first place. If it is, then chances are that the server sending the header also set proper access control for CORS requests.

**Comment by VARGA-Peter** [comment]
> The "error" message that Chrome shows here (I assume you're using Chrome, as AFAIK it's the only browser that shows this error) is really a non-error, I don't know why they've not chosen a notice instead. AFAICT you can safely ignore it. There's no problem in your code, it won't halt JS execution or anything, it just means `XmlHttpRequest.getRequestHeader()` tried to access something that it's not allowed to, and the method will return `null`.

Yes, I noticed it doesn't stop the JS execution, it only appeared in the console, but now, also thx to you, I disabled the DebugKit which wasn't needed on the page anyway and the message has gone. Thx for the explanation.
