### ISSUE TITLE
Database gets silly big

### ISSUE THREAD

**Issue by dakota** [cakephp/debug_kit#380]
If you've got a particularly active development environment (Especially if you are using simple ajax polling) it is possible for the sqlite db file to get massive:

```
vagrant@dev2:/var/www/html$ ls -hlaG tmp | grep sql
-rwxrwxrwx 1 vagrant 2.0G Oct  6 08:57 debug_kit.sqlite
```

While there is the `gc` method, I don't think that is is strict enough. It doesn't make sense to only delete requests older than 2 weeks when DebugKit only shows the last 10 requests at any one time. I believe that the `gc` should rather delete all requests, except for the last say 50 (configurable perhaps).

**Comment by dereuromark** [comment]
:+1: No point in keeping anything beyond 20+
You wouldn't even know what it was about either way after xx other requests following.

**Comment by ravage84** [comment]
:+1: to be configurable, those who actually need more shouldn't be bitten in the a**.
But I would say 50 sound good, max 100 may be.

How much space could be taken up by 100 requests?

**Comment by dakota** [comment]
Closing this, I've opened a PR.
