### ISSUE TITLE
Error: The application is trying to load a file from the DebugKit plugin.

### ISSUE THREAD

**Issue by cnizzdotcom** [cakephp/debug_kit#383]
Okay so I've been using CakePHP3 since it was an early release candidate, after updating some old 3.0 based code to 3.1 and upgrading debug kit with it I am now getting this:

Error: The application is trying to load a file from the DebugKit plugin. 
Make sure your plugin DebugKit is in the /var/www/personal/uberniche/plugins/ directory and was loaded.

I can see that vendor/cakephp/debugkit exists, but Cake does not seem to be looking there or I am not thinking through this correctly. After digging I read that vendor/cakephp-plugins.php should be kicking it in my file system, but its not http://book.cakephp.org/3.0/en/plugins.html#installing-a-plugin-with-composer.

Should debugkit exist in my apps Plugin directory or is it supposed to load from vendor? How does one resolve the issue I am experiencing?

**Comment by markstory** [comment]
DebugKit should be in in vendor/. Also make sure that  vendor/cakephp-plugins.php has the correct paths, and that your config/bootstrap.php file has `Plugin::load('DebugKit', ['bootstrap' => true]);`

**Comment by cnizzdotcom** [comment]
Do not close this, you've ignored a critical portion of my report. vendor/cakephp-plugins.php does not exist in my file system! I suspect this is the primary issue as I would surmise that it servers as an autoloader, but I don't have it for some reason. Please advise.

**Comment by markstory** [comment]
Given that your application is older, you are likely missing the [plugin installer](https://github.com/cakephp/app/blob/master/composer.json#L12), and [post-install hook](https://github.com/cakephp/app/blob/master/composer.json#L36) which builds the cakephp-plugins.php file.

**Comment by cnizzdotcom** [comment]
This has resolved my issue, for future viewers be sure to add this to your composer.json "scripts" per the giant red box that should appear in your terminal:

"post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump"

Nice to be back in business.

**Comment by mehov** [comment]
My case was a bit different. If you're [loading a plugin by its class name](https://github.com/cakephp/app/blob/061d4c5c4146169cf64465d4b44975f7081af5eb/src/Application.php#L54), make sure the [corresponding class](https://github.com/cakephp/debug_kit/blob/afc3b1554068b20711e5e6a9edff18040ea4a3a0/src/Plugin.php) is actually created.
