### ISSUE TITLE
Always get notice 'Make sure you have `Plugin::load("DebugKit", ["bootstrap" => true]);'

### ISSUE THREAD

**Issue by giozhou** [cakephp/debug_kit#385]
I installed cakephp V3.0 
I have loaded the component 
//bootstrap.php
```php
// Only try to load DebugKit in development mode
// Debug Kit should not be installed on a production system
// if (Configure::read('debug')) {
    Plugin::load('DebugKit', ['bootstrap' => true, 'routes' => true]);
// }
```
And in my AppController.php I have added this code 

```php
class AppController extends Controller
{
    public $viewClass = 'App\View\SmartyView';
    public $components = array('DebugKit.Toolbar');
……
```

File is existing in my project

```linux
gio@ubuntu:~/git/crmv2$ ls vendor/cakephp/debug_kit/src/Controller/Component/
ToolbarComponent.php
```

What's the problem I encountered?

**Comment by markstory** [comment]
In CakePHP 3.0 there is no component. Have you tried removing the $components line?

**Comment by giozhou** [comment]
No component? 
Below is path in Cakephp V3.0
```
ls vendor/cakephp/debug_kit/src/Controller/Component/
ToolbarComponent.php
```

before I added code, 
```
public $components = array('DebugKit.Toolbar');
```
no exception like this .
```
DebugKit is now loaded through plugin bootstrapping. Make sure you have `Plugin::load("DebugKit", ["bootstrap" => true]);` in your application's bootstrap.php.
```

But I still want to use debugkit toolbar for I want to see sql dump.

**Comment by lorenzo** [comment]
Please follow the installation instructions in the book:
http://book.cakephp.org/3.0/en/debug-kit.html

**Comment by 1906sam** [comment]
Remove this line from your appController (for cakephp 3.x)
public $components = array('DebugKit.Toolbar');

It should work then.
