### ISSUE TITLE
PDOException triggers a FatalError

### ISSUE THREAD

**Issue by JustDoItSascha** [cakephp/debug_kit#386]
My application throws a PDOException. This PDOException triggers a FatalError itself.

The error is in debug_kit/src/Panel/VariablesPanel.php line 85.

```
Warning: Warning (2): get_class() expects parameter 1 to be object, string given in     [/var/www/html/dev/my-app/vendor/cakephp/cakephp/src/Template/Layout/dev_error.ctp, line 206]
```

The $error variable in line 206 contains a string with

```
Unserializable object - PDOException. Error: SQLSTATE[42000]: Syntax error or access violation:........
```

Tested with DebugKit 3.0.2 and DebugKit 3.1.0

**Comment by lorenzo** [comment]
The offending line:

https://github.com/cakephp/debug_kit/blob/83467f84857484ac3bc6579d2ca84b5de8ef7a2e/src/Panel/VariablesPanel.php#L85

**Comment by JustDoItSascha** [comment]
Not correct, offending Line is https://github.com/cakephp/debug_kit/blob/83467f84857484ac3bc6579d2ca84b5de8ef7a2e/src/Panel/VariablesPanel.php#L87

**Comment by dereuromark** [comment]
Both lines would result in the same issue.

**Comment by markstory** [comment]
Closing as I think this has been fixed.

**Comment by ravage84** [comment]
@markstory just for the records, I see no commit reference here. Wherre/how did this get fixed?

**Comment by markstory** [comment]
No one else has reported similar issues so I assumed it had been fixed.
