### ISSUE TITLE
Not working with xdebug

### ISSUE THREAD

**Issue by gjm** [cakephp/debug_kit#388]
Not working when xdebug is enabled. When i disable xdebug works fine.
![cakephp_xdebug](https://cloud.githubusercontent.com/assets/77360/11440096/af55cfc6-94f7-11e5-89a8-a98dc1a754bc.jpg)

**Comment by lorenzo** [comment]
Would you mind reporting this to the xdebug project as well? @gjm 
In the meantime I'll see if I can reproduce it myself. Can I see your bootstrap.php?

**Comment by lorenzo** [comment]
And php version please :D

**Comment by gjm** [comment]
Thanks for you reply Lorenzo.

My bootstrap.php is completely stock after installation with composer. Get it at https://goo.gl/ZhwgYR

I'm running PHP 5.6.11 on Ubuntu 15.10 (64 bit).

**Comment by lorenzo** [comment]
Thanks

**Comment by riconeitzel** [comment]
same here … running it on MAMP with php5.6 with xdebug – only turning off xdebug works :-/

**Comment by Asgraf** [comment]
I would like to notice that setting `xdebug.collect_params` ini setting to `1` seems to fix the problem.

**Comment by dereuromark** [comment]
Maybe you can make a PR to docs to add this troubleshooting note there?

**Comment by riconeitzel** [comment]
can @gjm confirm that @Asgraf's fix works?

**Comment by Asgraf** [comment]
To be precise only values  0 and 1 are safe with debugkit.
Values 2,3,4,5 are causing problems
https://xdebug.org/docs/all_settings

**Comment by gjm** [comment]
I'm sorry but I cannot confirm since I'm no longer working on this project.

Thanks for your work anyway.


Gonçalo Marrafa

**Comment by dereuromark** [comment]
PR open: https://github.com/cakephp/docs/pull/5965

**Comment by othercorey** [comment]
Sorry to comment on a closed issue, but the PR is still open from several months ago.

>Would you mind reporting this to the xdebug project as well?

I was wondering if the issue was ever reported to xdebug. Does anyone know?
