### ISSUE TITLE
Unserialize errors after moving to PostgreSQL storage

### ISSUE THREAD

**Issue by ethanpooley** [cakephp/debug_kit#392]
I'm running into problems making PostgreSQL the storage mechanism for DebugKit. Features that worked previously (History, SQL Log, and Variables) now print `unserialize()` errors.

Versions:
- Cake 3.1.3
- DebugKit 3.2.1
- PHP 5.6.16
- PostgreSQL 9.4.5

Environments:
- Ubuntu 14.04 on Virtualbox 5.0.12
- Ubuntu 14.04 on Heroku (Cedar-14)

Configuration:
- `config/app.php`
```
    'Datasources' => [
        'debug_kit' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'host' => 'localhost',
            'port' => '5432',
            'username' => 'REDACTED',
            'password' => 'REDACTED',
            'database' => 'REDACTED',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'quoteIdentifiers' => false,
        ],
        ...
```
- `config/bootstrap.php`
```
if (Configure::read('debug')) {
    Plugin::load('DebugKit', ['bootstrap' => true, 'routes' => true]);
}
```

Output when clicking on the Variables panel:
```
Notice (8): unserialize(): Error at offset 129 of 133 bytes [ROOT/vendor/cakephp/debug_kit/src/Controller/PanelsController.php, line 91]
Code

        $panel = $this->Panels->get($id);
        $this->set('panel', $panel);
        $this->set(unserialize($panel->content));

Context

$id = 'd8e536ac-cf60-4607-96c6-917d7bf52f1f'
$panel = object(DebugKit\Model\Entity\Panel) {

	'id' => 'd8e536ac-cf60-4607-96c6-917d7bf52f1f',
	'request_id' => 'ceacdb37-3521-48ce-b28b-911c825c77bd',
	'panel' => 'Variables',
	'title' => 'Variables',
	'element' => 'DebugKit.variables_panel',
	'summary' => '3',
	'content' => 'a:2:{s:7:"content";a:3:{s:10:"_serialize";a:1:{i:0;s:8:"agencies";}s:8:"agencies";a:20:{i:0;O:23:"App\Model\Entity\Agency":10:{s:14:"',
	'[new]' => false,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'DebugKit.Panels'

}

unserialize - [internal], line ??
DebugKit\Controller\PanelsController::view() - ROOT/vendor/cakephp/debug_kit/src/Controller/PanelsController.php, line 91
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37
```

When I look at my database I see that DebugKit has created two tables for itself: `panels` and `requests`. When I look at individual records in the `panels` table, the `content` element appears to be getting cut off short for the symptomatic panels. The data in `content` is much longer for the panels that function properly.

**Comment by lorenzo** [comment]
Can you show the table schematic that was generated by debugkit?

**Comment by ethanpooley** [comment]
```
mydatabase=# \d+ panels
                               Table "public.panels"
   Column   |       Type        | Modifiers | Storage  | Stats target | Description 
------------+-------------------+-----------+----------+--------------+-------------
 id         | uuid              | not null  | plain    |              | 
 request_id | uuid              | not null  | plain    |              | 
 panel      | character varying |           | extended |              | 
 title      | character varying |           | extended |              | 
 element    | character varying |           | extended |              | 
 summary    | character varying |           | extended |              | 
 content    | text              |           | extended |              | 
Indexes:
    "panels_pkey" PRIMARY KEY, btree (id)
    "unique_panel" UNIQUE CONSTRAINT, btree (request_id, panel)

mydatabase=# \d+ requests
                                    Table "public.requests"
    Column    |            Type             | Modifiers | Storage  | Stats target | Description 
--------------+-----------------------------+-----------+----------+--------------+-------------
 id           | uuid                        | not null  | plain    |              | 
 url          | character varying           | not null  | extended |              | 
 content_type | character varying           |           | extended |              | 
 status_code  | integer                     |           | plain    |              | 
 method       | character varying           |           | extended |              | 
 requested_at | timestamp without time zone | not null  | plain    |              | 
Indexes:
    "requests_pkey" PRIMARY KEY, btree (id)
```

**Comment by markstory** [comment]
From the looks of that entity dump, your serialized content has been truncated.

**Comment by ethanpooley** [comment]
Yes, and I turned on Postgres logging to catch the INSERT query. It's been truncated prior to insertion:

```
LOG:  execute pdo_stmt_00000011:
    INSERT INTO panels (
        request_id,
        panel,
        title,
        element,
        summary,
        content,
        id
    ) VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING *

DETAIL:  parameters:
    $1 = '336b8f4c-8067-4a4e-b430-d5ebef62f216',
    $2 = 'Variables',
    $3 = 'Variables',
    $4 = 'DebugKit.variables_panel',
    $5 = '3',
    $6 = 'a:2:{s:7:"content";a:3:{s:10:"_serialize";a:1:{i:0;s:8:"agencies";}s:8:"agencies";a:20:{i:0;O:23:"App\Model\Entity\Agency":10:{s:14:"',
    $7 = '14fa218f-b0e0-4e11-af72-8e56a161163e'

```

**Comment by lorenzo** [comment]
It is probably PDO doing something funny

**Comment by ethanpooley** [comment]
Happy to grab any additional data for you guys, but I don't want to just flail around. What can I try for you?

**Comment by lorenzo** [comment]
Let me try it for myself before...

**Comment by markstory** [comment]
Until this issue is fixed, you might want to use the default SQLite storage.

**Comment by ethanpooley** [comment]
Yes @markstory, that's what we'll do for now. The impetus for the switch though is having a functional DebugKit on Heroku (or any scaling stack) regardless of the number of app servers in use.

**Comment by markstory** [comment]
SQLite works fine on heroku from my experience. Are you hoping to have debugkit running in an environment where multiple app servers are involved?

**Comment by josegonzalez** [comment]
You might need to set `ext-sqlite` in your composer.json for heroku...

**Comment by ethanpooley** [comment]
Each Heroku dyno has its own filesystem, and each request in a session is routed randomly across available dynos. So DebugKit on top of SQLite works just fine for single-dyno environments, but fails in multi-dyno environments in proportion to the number of dynos available. In the multi-dyno environment a panel request may hit a different filesystem—and thus a different SQLite database—than the one in which its data was stored. (So @josegonzalez we do have SQLite loading properly, and it is not malfunctioning per se. It's just that Heroku's architecture can render normal SQLite behavior inappropriate for some purposes.)

Perhaps it isn't so common to desire DebugKit to be operational on a multiple-app-server environment, since development and debugging are usually done using as few resources as possible. But since the multi-dyno environment can introduce unique problems (just as in this instance) we have decided to keep one development environment running with at least two dynos so that we can catch and debug any such problems prior to staging and production.

There may well be other solutions available to us. A shared filesystem add-on for Heroku would be one example. But using Postgres as the storage engine for DebugKit is the ideal solution in our case because it has the simplest implementation and adds no new dependencies to our app. I do not know of another solution as lightweight as adding a single Datasource definition to `config/app.php` and then never needing to give it another thought.

**Comment by josegonzalez** [comment]
Interesting. I've never used heroku like that in development, but your use case is pretty sound.

**Comment by markstory** [comment]
I'll see if I can reproduce this issue locally with postgres. I won't be able to check against heroku's postgres though.

**Comment by markstory** [comment]
I was able to reproduce this issue locally with postgres 9.4.2 and PHP 5.5.27. From looking at the serialized output, it looks like the strings are being truncated at the first null byte by pdo_pgsql.

**Comment by markstory** [comment]
Pull request up now.

**Comment by half2me** [comment]
@ethanpooley How did you get rid of the Missing Plugin error message for DebugKit on Heroku?

**Comment by ethanpooley** [comment]
@half2me I didn't encounter one, that I recall. If you want to create a new issue around that and paste the whole error, I'll take a look at it.

**Comment by half2me** [comment]
@ethanpooley It was in the `require-dev` section of my composer.json, and I didn't read over the heroku documentation properly, they install with `--no-dev` option.
However, I could not get debug_kit to properly use Postgres as storage. See my Issue here:
https://github.com/cakephp/debug_kit/issues/466#issuecomment-261298215
