### ISSUE TITLE
Issue with custom panels

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#395]
I cannot get the [documented approach](http://book.cakephp.org/3.0/en/debug-kit.html#developing-your-own-panels) of custom panels to work with CakePHP3.

Might the tests be wrong or insufficient?
The test namespace is just `Panel` here, I would assume `PluginName\Panel` at least, or App for non plugin:
https://github.com/cakephp/debug_kit/blob/master/tests/test_app/Plugin/DebugkitTestPlugin/Panel/PluginTestPanel.php#L17

I used the documented approach of https://github.com/dereuromark/CakePHP-XHProf README and it failed to recognize the custom panel.

**Comment by markstory** [comment]
I'll take a look, I remember having app panels working at one point.

**Comment by markstory** [comment]
Seems like [this author managed to get it working](https://github.com/dorxy/debug_http).

**Comment by markstory** [comment]
The documented approach worked fine for an application hosted panel. Make sure you setup the panel config before loading the plugin. Having the `Configure` call after the `Plugin::load()` call will result in the panel not being loaded.

**Comment by dereuromark** [comment]
You were right, the order mattered. Thx.

**Comment by HavokInspiration** [comment]
Maybe it would be worth mentionning in the doc ?

**Comment by markstory** [comment]
@HavokInspiration Probably.
