### ISSUE TITLE
Prefix storage tables to avoid collisions

### ISSUE THREAD

**Issue by ethanpooley** [cakephp/debug_kit#396]
The database tables used by DebugKit are `panels` and `requests`. These are very generic names that could easily be present in applications. When DebugKit is given a dedicated database this is no problem, but in some environments a dedicated database would increase complexity and/or expense. To provide the most flexibility, simplest setup, and fewest failures, DebugKit's storage tables should be prefixed to avoid collisions.

**Comment by lorenzo** [comment]
In principle I agree with you, but why not just use sqlite?

**Comment by lorenzo** [comment]
@ethanpooley since you are using postgres, would it be acceptable in the mean time to use another postgres schema?

**Comment by markstory** [comment]
Use a dedicated database, postgres schema or SQLite.

**Comment by ethanpooley** [comment]
@lorenzo Our reasons for not using SQLite in this instance are explained here: https://github.com/cakephp/debug_kit/issues/392#issuecomment-167877396

Thank you both for looking at this. I was not up to speed on schemas in Postgres, being a long-time MySQL user. I went ahead and implemented the alternative schema even though our app doesn't currently have a name conflict with DebugKit's tables. The `schema` configuration for datasources was appropriately documented and easy to find at http://book.cakephp.org/3.0/en/orm/database-basics.html

Changing the datasource configuration was not quite enough. DebugKit errored until I manually created the named schema. Is it possible to have DebugKit check for the existence of the schema that was defined in its datasource, and create that schema if it does not yet exist? Otherwise this solution requires that a step be added to environment provisioning.

Although I'm grateful for the new knowledge and agree that it represents part of a solution, I think I remain in favor of my original suggestion. In my mind the standard debugging toolkit should be as unobtrusive as possible, require as little configuration as possible, and should go out of its way to avoid causing any problems or taking up any developer time. Namespacing its storage for carefree co-existence with other apps furthers that goal, as does attempting auto-creation of the designated database or schema when MySQL, Postgres, etc. are configured as a datasource. The DebugKit database is effectively created from scratch when SQLite is configured, after all.

Regardless of whether those ideas are ever adopted I think an update to the "Database Configuration" section of the README is warranted, mentioning the namespacing issue. This seems a good place, since the topic is relevant precisely when altering the default configuration. There's also currently a section "DebugKit Storage" that is redundant - perhaps that could be resolved at the same time. If no one objects to that I'll give it a go.

**Comment by lorenzo** [comment]
Most of how php works with database comes from the assumption that everything was setup already. Since creating database and schemas often require privileged access, that is not something cake attempts to do; An exception being sqlite, since it is just a file in the filesystem, and we know almost for sure that we have permission to create the file in a development environment.

I'd be glad If you are up to fixing the documentation on configuring the database :)

**Comment by ethanpooley** [comment]
@lorenzo Yep, I definitely see those points. In my own case I've added this line to the datasource configuration:
```
'init' => ['CREATE SCHEMA IF NOT EXISTS debug_kit'],
```
But I agree there's no good way to universalize that, especially with the privileges gotcha. To me that reinforces the importance of allowing DebutKit to play nicely within an app's own schema. But as to the docs, I'll PR something soon.

**Comment by lorenzo** [comment]
Oh, that's a very elegant way of dealing with it. We can just add that to the docs for using debugkit with postgres
