### ISSUE TITLE
(ORM) query()->update() giving error

### ISSUE THREAD

**Issue by markstory** [cakephp/debug_kit#397]
_From @half2me on December 29, 2015 22:3_

I am just trying out the example code in the documentation for my own data:

``` php
$query = TableRegistry::get('Products')->query();
$result = $query->update()
  ->set(['ean' => '111111111'])
  ->where(['id' => '1'])
  ->execute();
```
I get the following error:
![error you cannot call all on a non select query use execute instead](https://cloud.githubusercontent.com/assets/6759894/12042909/fc5c2b8e-ae7f-11e5-8f36-27df1d278fa9.png)
I don't understand, I am not using 'all' I am using 'execute'. Why doesn't it work?

_Copied from original issue: cakephp/cakephp#7922_

**Comment by markstory** [comment]
_From @lorenzo on December 29, 2015 22:12_

Could you open this bug in the debugkit repo please?

**Comment by markstory** [comment]
I'm guessing that `$result` or `$query` is being assigned to the view context as well?

**Comment by lorenzo** [comment]
The problem is that in the variables panel we check for a `Database\Query` class but then call the `all()` method, instead of checking if it is also a `ORM\Query`

**Comment by markstory** [comment]
One could use ORM\Query to do update() as well. I think we need to see if the query is a select query before calling all().

**Comment by markstory** [comment]
Pull request up now.
