### ISSUE TITLE
Constant Arrays notice/warning

### ISSUE THREAD

**Issue by Tzaoh** [cakephp/debug_kit#401]
If you declare an array as constant (you can do it from PHP 5.6 I think) you get a notice/warning because in `\vendor\cakephp\debug_kit\src\Template\Element\environment_panel.ctp` it is trying to print it through `<td><?= h($val) ?></td>`(line 34).

I guess one correct aproach would be to check if it is an array and if so use something like `print_r()`

![capture](https://cloud.githubusercontent.com/assets/5722357/12243941/6ec2b23a-b8a1-11e5-9750-2579c7ffe36c.PNG)

**Comment by markstory** [comment]
Normally I would do a pull request, but I pushed a fix for this to master in ca07485 like a muppet.
