### ISSUE TITLE
Add panel for "Cache log"

### ISSUE THREAD

**Issue by tersmitten** [cakephp/debug_kit#402]
A few days ago we were debugging something and we thought that it would be really helpful for debug_kit to have a "Cache log" panel just like the SQL log.
- "Queries" would be cache keys
- "Affected", "Num. rows", "Took (ms)" can be remove
- Actions would contain an option to show the cache value

What do you think about the idea and how difficult would it be to build it?

**Comment by markstory** [comment]
I can see how a cache 'query' panel could be helpful. We already have a proxy that counts operations to cache backends. Tracking which keys are being manipulated shouldn't be very hard.

**Comment by tersmitten** [comment]
You are talking about CakePHP 3 right?

**Comment by markstory** [comment]
@tersmitten I am.

**Comment by dereuromark** [comment]
@tersmitten Are you interested in making a PR?
