### ISSUE TITLE
debug kit seems to use user defined Inflections when it creates sqlite tables then fails to read it.

### ISSUE THREAD

**Issue by xavier83ar** [cakephp/debug_kit#406]
It seems that debug kit is using user defined Inflection rules when it creates sqlite data base but then when it needs to read it, it ignores inflections (or that's what I think) so it fails because it cannot describe tables. 

To reproduce this issue, install a fresh new cakephp project with composer (debug_kit should get installed), then edit `config/bootstrap.php` and add this lines:

```php
// spanish inflector rules
Inflector::rules('plural', [
    '/([r|d|j|n|l|m|y|z|s])$/i' => '\1es',
    '/([a|e|é|i|o|u])$/i' => '\1s',
]);
Inflector::rules('singular', [
    '/([r|d|j|n|l|m|y|z|s])es$/i' => '\1',
    '/([a|e|é|i|o|u])s$/i' => '\1',
]);
```

After that you should remove `tmp/debug_kit.sqlite` file to force debug_kit  to recreate the sqlite database and check the project's home page from a browser, you should see an error _"Cannot describe requests. It has 0 columns"_. If you check `debug_kit.sqlite` database you would find that there is a __`requestses`__ table, created with that name due to inflections.

If you remove those lines, then remove `debug_kit.sqlite` and hit the home page, it will work, add Inflections again and everything continues working.

**Comment by markstory** [comment]
I suspect the process of fixtures -> table generation uses inflections when it shouldn't.

**Comment by markstory** [comment]
Pull request up now.
