### ISSUE TITLE
Panel SQL logs

### ISSUE THREAD

**Issue by danilort** [cakephp/debug_kit#408]
Hello,
I installed DebugKit (manual installation) and I enabled the plugin, following your documentation, but the "SQL logs" does not work.

See:
[BUG DebugKit SQL log.pdf](https://github.com/cakephp/debug_kit/files/164816/BUG.DebugKit.SQL.log.pdf)

**Comment by ravage84** [comment]
Have you removed this line?

https://github.com/cakephp/cakephp/blob/2.8.1/app/View/Layouts/default.ctp#L61

**Comment by markstory** [comment]
SQL logs work fine in the applications I have. I suspect you've not removed the logs in your layout, or that your page has no queries. Removing the layout code is [mentioned in the install/setup section](https://github.com/cakephp/debug_kit/tree/2.2#enable-plugin) of the docs.

**Comment by danilort** [comment]
Yes, I had commented this row.
Now I have deleted the row, and it works.
Thank you.

I advise you to change the documentation, you must use:
Configure::write('debug', 2);        //not 1
