### ISSUE TITLE
Standalone version of toolbar

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/debug_kit#411]
For me, DebugKit is vital for debugging especially in the case of AJAX. As in theses cases I typically get the correct result, or just no result at all (`json_encode()` just fails).

Now how do you debug AJAX requests via DebugKit? You need to reload the page and then use the History panel. So what I do, is having a second tab with an unrelated page, which I refresh after doing some troublesome XHR requests, then open up the toolbar again, go to History, select the right request, then go to the other panels.

I suggest the following functionality which would be a tremendous help to me:

1. Have a page that just renders DebugKit with the History panel always visible on the left, the toolbar tabs on the right (main page)
2. Have the History panel automatically refresh periodically to show new requests
3. The user can select a request in the History panel while the main page stays with the same open tab

Example scenario: I am adding functionality to my finder that causes no data being delivered. I open the DebugKit page in a secondary window/tab and select the ORM tab. Whenever I change the finder code, I trigger a new AJAX request. I can go through the different requests in the History panel and see how the generated SQL changes.
Another example scenario: Working on performance optimization and keeping the Timer tab open.

Obviously this can also improve the workflow for regular page visits.

**Comment by ravage84** [comment]
Have you ever had a look at the (Firefox) development console, when you have installed DebugKit and do an AJAX call? :smirk_cat:

**Comment by dereuromark** [comment]
Or chrome developer toolbar :) For that matter. Both developer friendly browsers come with it almost out of the box and very powerful ajax debugging tools.

**Comment by ypnos-web** [comment]
Thanks for your comments, I use the chrome developer toolbar all the time and look at the network traffic to debug XHR responses. However am I missing an interaction between the Chrome debugging and debug_kit? 

So naive question: Having debug_kit enable, how would I use the Chrome debugging to have a look at SQL querys?

**Comment by ravage84** [comment]
You don't see something like this?

![debugkit_console](https://cloud.githubusercontent.com/assets/625761/13814831/29f4d114-eb88-11e5-80bb-b5b861941b76.png)

**Comment by ypnos-web** [comment]
Ok so this is Firebug and not the built-in console. I installed Firebug. But the Fireburg console just stays empty, for whatever reason.

**Comment by ravage84** [comment]
May be add:
```
// In AppController.php
App::uses('FireCake', 'DebugKit.Lib');
````

**Comment by ypnos-web** [comment]
I am using CakePHP 3.x.

**Comment by dakota** [comment]
@ypnos-web DebugKit 3 already catches all ajax requests on the current view

**Comment by dakota** [comment]
![image](https://cloud.githubusercontent.com/assets/83255/13818323/1c5a63f0-eb9e-11e5-92f0-9ead06f8c495.png)

![image](https://cloud.githubusercontent.com/assets/83255/13818332/252e6134-eb9e-11e5-8efb-99b594fc6105.png)

Clicking on it will load the details for that request.

**Comment by ypnos-web** [comment]
Yes it does! It didn't work before and I never realized it changed.

I still think what I propose would be useful (esp. the divided view with history vs the other tabs) but the need for it is not as imminent anymore.

Thanks for your patience.

**Comment by markstory** [comment]
If you have an idea on how to make the divided view work a pull request would be great. Closing this issue as the core ask (XHR debugging) already works.
