### ISSUE TITLE
PDOException triggers fatal error: Call to undefined method Cake\Database\Query::toArray() 

### ISSUE THREAD

**Issue by berarma** [cakephp/debug_kit#413]
I've found that a SQL error in the count query of the paginator component triggers this fatal error in the following line:
https://github.com/cakephp/debug_kit/blob/83467f84857484ac3bc6579d2ca84b5de8ef7a2e/src/Panel/VariablesPanel.php#L76

As fas as can understand, the _PDOException_ contains a trace with a _Cake\Database\Query_ object. The code checks for this type of object and then calls the method _toArray()_ that exists in the _Cake\ORM\Query_ class but not in _Cake\Database\Query_.

I've worked around this by changing the condition to:
```php
if ($item instanceof \Cake\ORM\Query || $item instanceof ResultSet) {
```

But I don't know how this should be handled.

**Comment by markstory** [comment]
Your fix sounds reasonable to me.
