### ISSUE TITLE
Iframe does not expand

### ISSUE THREAD

**Issue by p-try** [cakephp/debug_kit#414]
I am experiencing the issue that the Debug Kit iframe does not expand when I click on it. It stays in its original size (40 by 40 pixels). Debug Kit itself is working perfectly. When I manipulate the HTML using my web browser developer tools to expand the iframe, everything is fine.

Browser: Mozilla Firefox 45.0.1
CakePHP 3.2.6
Debug Kit 3.2.7
Windows 7

![unbenannt](https://cloud.githubusercontent.com/assets/7594671/14385762/5ec04528-fda2-11e5-8225-eb7a3a5bd891.PNG)
Debug Kit in the bottom right corner of the browser viewport after clicking on it.

**Comment by markstory** [comment]
How can someone reproduce this? Without a way to reproduce no fixes can really be done.

**Comment by p-try** [comment]
You are right, I am sorry. If I had tried to reproduce it with a new app in the first place, I would have got to the bottom of the problem right away.
My app is behind a reverse proxy to make it available from outside our network. When I access it via the proxy, DebugKit uses the original server hostname for the iframe src attribute. Due to XSS restrictions, DebugKit is not able to modify the iframe size. I can easily work around the problem using the original server hostname to access the app instead of the reverse proxy.

**Comment by Marlinc** [comment]
I actually had the same issue, the following code is what's causing it: https://github.com/cakephp/debug_kit/blob/master/src/Routing/Filter/DebugBarFilter.php#L235-L236

**Comment by markstory** [comment]
@Marlinc That code is just emitting a script tag. How is that the problem? It sounds like an iframe sandboxing issue which isn't something I can fix.

**Comment by Marlinc** [comment]
Yes I know @markstory :smile:, the issue is that hostname that's detected is wrong.

**Comment by markstory** [comment]
Which hostname is being detected incorrectly?

**Comment by Marlinc** [comment]
In my case it wasn't an issue with CakePHP. It had to define `fullBaseUrl` in my application.

**Comment by p-try** [comment]
Thank you! How can I be so stupid? That fixes it alright.
