### ISSUE TITLE
paginate() doesn't show entities in variables tab

### ISSUE THREAD

**Issue by pgmassari** [cakephp/debug_kit#419]
I noticed the following (CakePhp 3.2.5, DebugKit 3.2.8, controller: products, action: index):

With:
```
public function index()
{
        $this->set('products', $this->paginate($this->Products));
        $this->set('_serialize', ['products']);
}
```

in the Variables panel, only the count is shown.

![screenshot-localhost 2016-05-20 15-57-46](https://cloud.githubusercontent.com/assets/5167784/15431678/3a5ee890-1eab-11e6-8d76-68fde21b710e.png)

While with:
```
public function index()
{
        $this->set('products', $this->Products->find());
        $this->set('_serialize', ['products']);
}
```

in the Variables panel, the full result set is present.

![screenshot-localhost 2016-05-20 16-06-01](https://cloud.githubusercontent.com/assets/5167784/15431686/4112fad2-1eab-11e6-8128-9143907e940f.png)

Is this working as intended?

**Comment by markstory** [comment]
I wasn't able to reproduce this with CakePHP 3.2.9 and and DebugKit 3.2.8. Do you happen to have any `resultFormatter()` methods being applied? The output you're seeing matches how DebugKit outputs instances of `Cake\Collection\Collection`. If you are doing some post-processing on your results, then what you're seeing is expected.

**Comment by pgmassari** [comment]
I don't explicitly apply any `resultFormatter()`

So, it's my understanding that since `paginate` invokes `all()`
https://github.com/cakephp/cakephp/blob/master/src/Controller/Component/PaginatorComponent.php#L171
http://api.cakephp.org/3.2/class-Cake.Datasource.QueryTrait.html#_all

DebugKit will only show the count of the result set. Correct?

**Comment by markstory** [comment]
Interesting, normally DebugKit will [iterate ResultSet objects](https://github.com/cakephp/debug_kit/blob/master/src/Panel/VariablesPanel.php#L75).

**Comment by pgmassari** [comment]
I tried to change that line as follows:

```
if ($item instanceof Query || $item instanceof ResultSet || $item instanceof \Cake\Collection\Collection) {
```

and DebugKit iterates as expected. Could this be a viable solution?

**Comment by markstory** [comment]
Yes that could work, I don't remember why we don't already capture `Collection`. It might have something to do with how streaming objects work.

**Comment by pgmassari** [comment]
Nice. Should I open a pull request?

**Comment by markstory** [comment]
@pgmassari That would be great :+1:
