### ISSUE TITLE
wrong file grouping in Include panel in windows

### ISSUE THREAD

**Issue by raul338** [cakephp/debug_kit#424]
Using debug_kit in windows (w/apache) i'm getting this list in the include panel
```
core(array)
  Other(array)
    0 CORE/Core\functions.php
    1 CORE/Collection\functions.php
    2 CORE/I18n\functions.php
    ...
app(array)
  Other(array)
    0 APP/Controller\UsersController.php
    1 APP/Controller\AppController.php
    ...
```
I solved changing the hardcoded `'/'` to `DS` constant in [IncludePanel.php#L170](https://github.com/cakephp/debug_kit/blob/master/src/Panel/IncludePanel.php#L170) (also in _niceFilename)
```
core(array)
  Auth(array)
    0 CORE\Auth\Storage\SessionStorage.php
    1 CORE\Auth\Storage\StorageInterface.php
    2 CORE\Auth\BaseAuthorize.php
  Behavior(array)
    0 CORE\ORM\Behavior\TreeBehavior.php
    1 CORE\ORM\Behavior\TimestampBehavior.php
  Cache(array)
    ...
```
I didn't make a pull request because I can't test it in linux for now

Also I'm using plugins and always shows as empty array, but I think it is another issue

**Comment by markstory** [comment]
Pull request open now.
