### ISSUE TITLE
CakePHP v3.2.12 http://test/debug_kit/js/toolbar.js 404 (Not Found)

### ISSUE THREAD

**Issue by wilecoyte78** [cakephp/debug_kit#429]
in CakePHP v3.2.12

I get GET http://test/debug_kit/js/toolbar.js 404 (Not Found)

When I try this:
cd webroot
ln -s ../vendor/cakephp/debug_kit/webroot debug_kit

I get this:

toolbar.js:53 GET http://test/debug_kit/toolbar/b977c7b2-a414-4970-8ac3-ef48e3e8982e 404 (Not Found)

**Comment by markstory** [comment]
How can someone reproduce this? How did you install the plugin?

**Comment by wilecoyte78** [comment]
By doing a fresh install of cake composer self-update && composer create-project --prefer-dist cakephp/app test

**Comment by wilecoyte78** [comment]
I am using Ubuntu 16.04 php 7.04 Apache 2.4.18 MySQL 5.7.12

**Comment by markstory** [comment]
@wilecoyte78 I don't know what's going on then.

**Comment by wilecoyte78** [comment]
Neither do I because this is a fresh install of Ubuntu, Apache2, PHP 7, and CakePHP. I have the exact same setup on a previous computer that I set up months ago without any issues. Exactly the same computer. distro, apache, php, the only difference now it that its a dual boot computer. The are different cake version and the old computer works fine. Even when I upgrade the old computer to the newest cakephp it still works fine

old computer:
Welcome to CakePHP v3.2.10 Console
---------------------------------------------------------------
App : src
Path: /var/www/html/test/src/
PHP : 7.0.4-7ubuntu2.1

new computer:
Welcome to CakePHP v3.2.12 Console
---------------------------------------------------------------
App : src
Path: /var/www/html/test/src/
PHP : 7.0.4-7ubuntu2.1

**Comment by wilecoyte78** [comment]
I did one other thing to see if it would work bin/cake server

The debug kit works perfectly without any issues. I really need it work when I put my site live using a domain name.

This is my .conf file: When I have it go live I will be changing the server name

<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	ServerName test
	DocumentRoot /var/www/html/test/webroot
	ErrorLog /var/www/logs/test/error.log
	CustomLog /var/www/logs/test/access.log combined
</VirtualHost>

**Comment by markstory** [comment]
Given that you have one site working on that machine with the same versions of libraries, I suspect there is a configuration issue you need to sort out.

**Comment by wilecoyte78** [comment]
Sorry about that I forgot to put AllowOverride All in my conf file for the directory
