### ISSUE TITLE
third party panels list

### ISSUE THREAD

**Issue by danielzzz** [cakephp/debug_kit#430]
hi, it would be great if there was a maintained list of third party panels for debug kit.
I'd like to have a panel showing X last entries from the log (not just for the current request), but before reinventing the wheel, maybe someone made it already (google not helping).
Having a curated list of panels would be really helpful... 

thanks, dan

**Comment by markstory** [comment]
>  Having a curated list of panels would be really helpful... 

Sounds great! Do you know of any panels? Because I don't :smile:

**Comment by danielzzz** [comment]
:D 
for starters, I found these:
https://github.com/wa0x6e/DebugKitEx
https://github.com/dorxy/debug_http (this is similar to the history panel)
https://github.com/mcurry/interactive (this one seems a bit old, not sure if outdated)

Maybe if you encourage people to actually let you know if they develop new panels, something else pops up ;)

cheers! dan

**Comment by markstory** [comment]
If you have the time, a pull request to update the `README.md` would be greatly appreciated :smile:

**Comment by dereuromark** [comment]
:+1: PR for readme

**Comment by ravage84** [comment]
We could mention the list or link to the list in the [DebugKit cookbook section](http://book.cakephp.org/3.0/en/debug-kit.html), too

**Comment by saeideng** [comment]
would be better to have lists in https://github.com/FriendsOfCake/awesome-cakephp 
instead of this repo/readme
then we can close this issue

**Comment by dereuromark** [comment]
Well since you would look here first for Panels, might be then at least good to have a backlink to there then.

**Comment by dereuromark** [comment]
PRs for the debug kit docs are welcome to add those.
