### ISSUE TITLE
DebugKit not compatible with CakePHP 3.3.0-beta

### ISSUE THREAD

**Issue by bobmulder** [cakephp/debug_kit#431]
Hi all,

Trying Cake 3.3.0-beta gave me the issue that DebugKit isn't working properly. I've loaded the plugin, but the tab isn't showing on the pages. It's hard for me to find the issue, but for now I blame the upgrade to 3.3.0-beta because of the following:

The `DebugBarFilter` class implements the following methods which are responsible for showing the debug tab on pages: `beforeDispatch` (for event `Dispatcher.beforeDispatch`) and `afterDispatch` (for event `Dispatcher.afterDispatch`).

I would like to hear what to do :)

Greetz,

Bob

**Comment by ADmad** [comment]
Upgrade to `3.3.0-beta2`.

**Comment by bobmulder** [comment]
Thanks @ADmad, I missed the new beta release.

**Comment by ADmad** [comment]
It hasn't been announced yet, week is just starting in US :)
