### ISSUE TITLE
can't load cake.icon.png

### ISSUE THREAD

**Issue by maxmasetti** [cakephp/debug_kit#438]
actually only that: 200 ok but "no respose data"

**Comment by markstory** [comment]
How can someone reproduce this? The file is in the repo and zipballs from github.

**Comment by maxmasetti** [comment]
digging deep I found that dowloaded file via wget is same length but "different" nature:
```
max$ file cake.icon.png 
cake.icon.png: PNG image data, 40 x 40, 8-bit/color RGBA, non-interlaced
max$ file ~/cake.icon.png 
/Users/max/cake.icon.png: data
max$ diff cake.icon.png ~/cake.icon.png 
Binary files cake.icon.png and /Users/max/cake.icon.png differ
max$ l cake.icon.png ~/cake.icon.png 
-rw-r--r--  1 max  staff  1756  2 Set 17:51 /Users/max/cake.icon.png
-rw-r--r--  1 max  staff  1756  2 Set 17:51 cake.icon.png
```
trying to get more info...

**Comment by maxmasetti** [comment]
mmm... the two file are quite similar but the downloaded one begins with a 0x0a (\n) alien char and conversely lacks the last byte.

**Comment by maxmasetti** [comment]
and now... magically all works correctly.
don't know.
beg your pardon
