### ISSUE TITLE
time difference between timer and the total response time 

### ISSUE THREAD

**Issue by danielzzz** [cakephp/debug_kit#442]
hi, sorry if this is a wrong place to ask but I am trying to find out why my app is getting slow occasionally.

from debugkit I'm getting the total request time 5 secs but the total waiting time in chrome console is 12 secs. 
this is on localhost so the actual download time is a couple of milliseconds. 

another case is when the total request time is XXX secs, but the lines below don't sum up to this..

what may cause this difference? 
thanks, dan

**Comment by markstory** [comment]
DebugKit often takes quite a while to do its work. It shouldn't be adding 7 seconds though. Furthermore there is DNS, SSL negotiation, network transfer.

The timer bars won't sum up as there are a number of code sections that DebugKit can't inject timers into.

**Comment by markstory** [comment]
If you're looking for more indepth profiling data you might want to look at tools like xhprof/xhgui or services like tideways/blackfire.io

**Comment by danielzzz** [comment]
I am quite confident it's not a network problem (it shouldn't be on localhost anyway, should it?)
The script itself should be ok, too -as it works perfectly on an external server.
I will play with xdebug, maybe it catches something, but I suspect it must be something related to the environment - maybe docker itself (but it worked perfectly until now) or maybe the hd is failing..

thanks anyway, dan

**Comment by markstory** [comment]
I didn't know you were testing over localhost :smile:

**Comment by danielzzz** [comment]
yes, I said it in my first comment ;) 
I know some people were having disk speed problems when using docker (I had some with virtual box), but it was mostly on osx and win (I'm on linux). And here everything was working perfectly until very recent...
Checking "top" on the apache and mysql boxes doesn't show anything unusual and the sql queries themselves are executed pretty fast. Then the system goes into the twilight zone for 20 secs... No idea why.. 
I will try with another disk to see if the problem still persist.

**Comment by markstory** [comment]
> yes, I said it in my first comment ;)

Derp so it was, my mistake.

**Comment by lorenzo** [comment]
@danielzzz In my experience the time comes from connecting to a database or a cache server. That happens before debugkit starts the timer

**Comment by danielzzz** [comment]
@lorenzo thanks, I will check it

**Comment by markstory** [comment]
Closing as I don't think there is anything to be done here. Timers work, and there have always been and likely always will be gaps as we don't instrument everything.

**Comment by danielzzz** [comment]
The only thing  I can think of that might improve the readings is to have the gaps listed somewhere in the detail list below the total time. Like when the total time is for ex. 10 secs and then the items below don't sum up to this value.
