### ISSUE TITLE
SQL log does not contain binded values, only placeholders

### ISSUE THREAD

**Issue by markstory** [cakephp/debug_kit#445]
_From @mirorac on September 20, 2016 11:13_

This is a:
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 3.3.3
- Platform and Target: -
### What you did

Screenshot of SQL log from debug panel - one request. Screenshot _is not_ result of merging two different screenshots.
![screen shot 2016-09-19 at 17 58 05](https://cloud.githubusercontent.com/assets/8964866/18667931/ed085228-7f32-11e6-9a82-abc03743c343.png)
### Expected Behavior

I expect to see actual values (exact sql sent to DB) as it is inside green circle. 
### Actual Behavior

Some queries have unbound placeholders logged as it is inside red circle. I think only queries made by associations (contain clause in query builder) are logged with placeholders. 

_Copied from original issue: cakephp/cakephp#9485_

**Comment by markstory** [comment]
_From @lorenzo on September 20, 2016 11:30_

How can we reproduce this problem?

**Comment by markstory** [comment]
_From @mirorac on September 20, 2016 11:45_

I am sorry, I do not know what is the root of problem. I have tried to solve it but no results so far.

I have application which has been built on version 3.2.13 and I noticed this issue right after updating to 3.3.3. Before update, I am sure there were no placeholders in sql log. I use this panel quiet often.

So there are no placeholders in your sql logs in any applications?

**Comment by markstory** [comment]
_From @lorenzo on September 20, 2016 12:19_

No, problem... finding the root of the problem is not what I'm asking for, only a way I can test this myself. I have a couple cake 3 applications and haven't seen this so far, so I was hoping for some guidance on how to trigger this error.

**Comment by thinkingmedia** [comment]
It appears to be just an issue with the `IN` clauses and arrays.

**Comment by arilia** [comment]
I confirm that I only see this behavior with the IN clause

this simple code triggers the problem

    $q = $this->Users->find()
            ->where([
                'name LIKE' => '%a%',
                'id IN' => [1,2,3,4,5]
            ])->all();

and in the SQL panel I see the placeholders for the IN clause but not for the LIKE clause

    WHERE 
    (
        name like '%a%' 
        AND id in (: c1,: c2,: c3,: c4,: c5)
    )

**Comment by arilia** [comment]
don't think it's a problem related just to debugKit, actually if I set `logQueries(true);` I see the same behavior in the log file, too.

**Comment by markstory** [comment]
The root cause of this issue was in how `IN` clause placeholders were generated. I've put up a pull request to fix that issue.
