### ISSUE TITLE
Won't load!!!

### ISSUE THREAD

**Issue by maxmasetti** [cakephp/debug_kit#449]
version 3.3.3 won't load. revert to 3.3.2 and now goes

**Comment by ravage84** [comment]
OMG! It's so HELPFUL to add **3** exclamation marks to the subject.
And even better, a one liner will most certainly help us to help you :smiling_imp:

**Comment by ravage84** [comment]
OMG! It's so HELPFUL to add **3** exclamation marks to the subject.
And even better, a one liner will most certainly help us to help you :smiling_imp:

**Comment by maxmasetti** [comment]
hi, don't know what I can do: simply won't show anything in the browser. no error in the log. required previous version and all is ok. If you have got any advice or test to do, your welcome

**Comment by lorenzo** [comment]
Please join us in the irc or slack channel and we will help you :)
