### ISSUE TITLE
DebugKit not compatible with CakePHP v2.9

### ISSUE THREAD

**Issue by cniklas** [cakephp/debug_kit#450]
Got this error in my console when trying to use the i18n Shell:
```
Fatal error: Class 'Object' not found in C:\xampp\htdocs\mywh\Plugin\DebugKit\Model\ToolbarAccess.php on line 22
```
In the CakePHP 2.9.0 release log it says:
> The `Object` class has been deprecated due to upcoming PHP7 collisions. It has been renamed to `CakeObject` to avoid collisions with new PHP reserved words.

Guess there's the rub.

I then changed line 22 in DebugKit\Model\ToolbarAccess.php to:
`class ToolbarAccess extends CakeObject`
Now it seems to work, but can someone please prove my soluton and submit a fix here?

**Comment by markstory** [comment]
Sounds like we're missing an App::use() call in CakePHP core. I suspect there are many plugins that rely on `Object` existing automatically.

**Comment by markstory** [comment]
I think this is a gap in CakePHP core. I've opened a pull request to fix the problem there.
