### ISSUE TITLE
Streamed body request cause multiple problems

### ISSUE THREAD

**Issue by nrother** [cakephp/debug_kit#452]
This is somewhat related to cakephp/cakephp#9408.

This code causes a warning to be emitted:
```php
$this->response->body(function () use ($writer) {
    $writer->save('php://output');
});
```
The warning is `strrpos() expects parameter 1 to be string, object given [ROOT/vendor/cakephp/debug_kit/src/Routing/Filter/DebugBarFilter.php, line 232]`

I also get a `RuntimeException` with message `Unable to emit response; headers already sent`, but I'm not completely sure if this is related. The exception goes away, when I disable DebugKit or use non-streamed responses, though.

For context: I'm trying to sent a streamed resource that is a complete HTML page (PHPExcel's Html Writer).

**Comment by markstory** [comment]
This error isn't related to cakephp/cakephp#9408, and has been hiding out since streaming responses were added, nice find :clap:

Closing as a pull request is open.
