### ISSUE TITLE
TimerPanel.php:35 I18n extraction

### ISSUE THREAD

**Issue by dorxy** [cakephp/debug_kit#462]
I'm getting the following error when using the I18n extract task for DebugKit:

`Invalid marker content in /my-project/vendor/cakephp/debug_kit/src/Panel/TimerPanel.php:35 * __d('debug_kit',$name)`

Might be worth to to fix in an upcoming version :) 
(not sure how yet, that's why I didn't do a PR)

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/debug_kit/pull/751
