### ISSUE TITLE
Change settings on the fly

### ISSUE THREAD

**Issue by whatchado** [cakephp/debug_kit#463]
Is it possible to change which panels are loaded on the fly? For instance, in some actions of a particular controller I use a component and have a custom panel specific to this component. Can I load my custom panel only when I use the component?

**Comment by dereuromark** [comment]
You can do that in initialize() callback in each controller before the component is loaded afaik.

**Comment by markstory** [comment]
I don't think there is an easy way to load a panel on the fly. It isn't as easy as it may initially seem because panels may need to setup additional listeners/hooks that may have already happened.
