### ISSUE TITLE
Allow the debug bar to track AJAX/JSON requests by front-end JavaScript

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/debug_kit#465]
Has there every been any discussion about extending the debug_kit to track data made by JavaScript AJAX calls from the front-end to the back-end.

I have an AngularJS application that makes a lot of JSON requests. I can see something where there is a panel to see all tracked AJAX calls and selecting one switches the panels to that request.

What are the technical challenges in supporting such a feature?

**Comment by markstory** [comment]
We already track XHR requests and update the History panel, but what did you have in mind that the native browser tools don't already do?

**Comment by thinkingmedia** [comment]
I need to see the SQL queries that were performed for the XHR request. If that is already supported, then this can be closed. I just assumed it didn't update.

**Comment by markstory** [comment]
Check the history panel, it should capture XHR requests, and let you look at the SQL queries that are being run.

**Comment by thinkingmedia** [comment]
awesome! thanks.
