### ISSUE TITLE
debug_kit config ignoring driver type

### ISSUE THREAD

**Issue by half2me** [cakephp/debug_kit#466]
I'm running my app on Heroku.
The DATABASE_URL env looks like this: `postgres://...`
I have changed my config/app.php to look like this:

```php
'Datasources' => [
        'debug_kit' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'quoteIdentifiers' => false,
            'url' => env('DATABASE_URL', null),
        ],
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
            'url' => env('DATABASE_URL', null),
        ],
    ],
```

The `default` is working fine, and my app can connect to the database, but when I enable debug mode, I get the following error: Database driver Cake\Database\Driver\Sqlite cannot be used due to a missing PHP extension or unmet dependency.
It seems like DebugKit is completely ignoring the postgres: part of the url.
If I remove `debug_kit` key from this Datasources config, everything works fine, and debug_kit doesn't show up. But when I try to configure it, it just does this. Any idea why?

**Comment by markstory** [comment]
No idea. Is there a stack trace related to the error you're getting? Are you able to get what you'd expect out of
```php
$connection = Cake\Datasource\ConnectionManager::get('debug_kit');
debug($connection->driver());
```

**Comment by half2me** [comment]
@markstory I'll check on monday :)

**Comment by ethanpooley** [comment]
@half2me I'm updating our stack right now, and once I'm done moving us forward to CakePHP 3.3.8 I'll return to my months-old project of moving Debug Kit onto PostgreSQL storage on Heroku. At that point I'll definitely try to come back here and report whether my experience intersects with yours in any way. Perhaps some code from my first attempt might be helpful too, though. I didn't rely on the raw URL. Instead I split it up and set the parts manually in our config file, like this (note the `init` element as well):
```
/**
 * Parse Heroku DSNs into arrays for convenient
 * use during configuration.
 **/
$postgresDSN = parse_url(env('DATABASE_URL'));

return [
    'Datasources' => [
        # DebugKit is not multi-server safe due to its default storage mechanism, SQLite.
        # Heroku enviroments that enable DebugKit should specify for it a storage
        # mechanism that is shared by all dynos, such as a PostgreSQL database.
        'debug_kit' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'host' => $postgresDSN['host'],
            'port' => $postgresDSN['port'],
            'username' => $postgresDSN['user'],
            'password' => $postgresDSN['pass'],
            'database' => ltrim($postgresDSN['path'], '/'),
            'schema' => 'debug_kit',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'init' => ['CREATE SCHEMA IF NOT EXISTS debug_kit'],
            'cacheMetadata' => true,
            'quoteIdentifiers' => false,
        ],
        ...
    ],
    ...
];
```

**Comment by half2me** [comment]
thanks @ethanpooley

**Comment by half2me** [comment]
@markstory Looking at the error msg and toggling the parameters, I realized it was not having a problem with the debug_kit settings but the 'test' database. I have no idea why it was trying to load those, as I was not running unit tests, simply enabling debug mode.
Anyway, debug kit is not loaded, and running that command you sent me:
```php
object(Cake\Database\Driver\Postgres) {
	'connected' => false
}
```
any idea?

**Comment by markstory** [comment]
Not really. Perhaps you could get a stack trace from where the test connection is being initialized and go from there?

**Comment by half2me** [comment]
@markstory I'll take a look at the stackTrace

**Comment by dereuromark** [comment]
Is this still an issue?
Or can we close?

**Comment by tamalmcp** [comment]
> Not really. Perhaps you could get a stack trace from where the test connection is being initialized and go from there?

I am using CakePHP 4.3.4 . after clone my project from github I got the following error.

**Database driver Cake\Database\Driver\Sqlite cannot be used due to a missing PHP extension or unmet dependency. Requested by connection "test"**

and solved it to the following way:
config/app_local.php
keep the DATABASE_TEST_URL null to the test connection
     **'url' => env('DATABASE_TEST_URL', null)**
