### ISSUE TITLE
debug kit 3.2 error 

### ISSUE THREAD

**Issue by dhananjayve** [cakephp/debug_kit#473]
i have installed cakephp using composer
composer create-project --prefer-dist cakephp/app testapp

Installation was successful. but when i have open app in browser i got this error

Fatal error: Call to undefined method Cake\Network\Response::getBody() in \testapp\vendor\cakephp\debug_kit\src\ToolbarService.php on line 213

**Comment by josegonzalez** [comment]
Duplicate of #471.

**Comment by dhananjayve** [comment]
Thank you
