### ISSUE TITLE
Problem with raleway `Failed to decode downloaded font`

### ISSUE THREAD

**Issue by flashios09** [cakephp/debug_kit#474]
Hi,

Recently i updated the framework(using the cakephp v3.4.0-beta4) and i have this warning in console:
![image](https://cloud.githubusercontent.com/assets/1313482/21931763/83f204d0-d99d-11e6-9a7b-c018fec0ef61.png)

I tried many browsers(Chrome, Safari, Firefox) always the same warning.
I tried the CakePHP dev server `bin/cake server`, the same warning.
I removed the **debug_kit** folder from **vendor/cakephp** then `composer update`(today it installed v3.5.1), the same warning.

Finally i tried to install the raleway font on my mac and it refuse:
![image](https://cloud.githubusercontent.com/assets/1313482/21932038/d374ac0a-d99e-11e6-9eaf-4fdc94cbfc34.png)

**Comment by markstory** [comment]
I will see if I can reproduce this. Is your webserver behind tls/ssl?

**Comment by flashios09** [comment]
@markstory 
> Is your webserver behind tls/ssl?

No, it's not.

**Comment by flashios09** [comment]
@markstory 
The symlink created via `bin/cake plugin assets symlink` solved the prob. 
https://book.cakephp.org/3.0/en/deployment.html#improve-your-application-s-performance
PS: 
Even with this **patch** and using debug_kit 3.6.0, i can't install the *raleway-regular.ttf* on my mac, always the same error on the same screenshot

**Comment by markstory** [comment]
> Even with this patch and using debug_kit 3.6.0, i can't install the raleway-regular.ttf on my mac, always the same error (view the previous screenshot)

I got these font files from google's CDN so they might not work as system fonts, and I don't think providing people with installable raleway is a goal of ours.

**Comment by flashios09** [comment]
> I got these font files from google's CDN so they might not work as system fonts, and I don't think providing people with installable raleway is a goal of ours.

I don't care about installing the raleway font on my mac, i added this as an extra info.
The symlink solve the prob ;)
Thanks
