### ISSUE TITLE
Fatal error: Call to undefined method Cake\Network\Response::getBody() in /.../vendor/cakephp/debug_kit/src/ToolbarService.php on line 213

### ISSUE THREAD

**Issue by vonboth** [cakephp/debug_kit#479]
Since the last upgrade of cake via composer I get this error

Fatal error: Call to undefined method Cake\Network\Response::getBody() in /.../vendor/cakephp/debug_kit/src/ToolbarService.php on line 213

Cake: 3.3.12
Debug-Kit: 3.5.1

Current PHP-Versions: 5.6.19 as well as 7.0

**Comment by antograssiot** [comment]
It should have been fixed already by #477.
Maybe we need to tag a new version, I'll have a look later today if no one's does before.

**Comment by antograssiot** [comment]
@vonboth Meanwhile you can pin to 3.5.0

**Comment by lorenzo** [comment]
I tagged a new version yesterday, please run a composer update

**Comment by vonboth** [comment]
Thank you for the quick reply!
I searched for the issue but couldn't see ist. Sorry for that!
Cake is great because of this awesome support!!
Thanks guys

(By the way: did composer update this morning and the issue appeared just now)
