### ISSUE TITLE
"no such file or directory"

### ISSUE THREAD

**Issue by siran** [cakephp/debug_kit#481]
I am not still able to reproduce this, but wanted to report it.

Something happens, apparently with debug_kit, that ends up writing an invalid file:

```
$ ls -l tmp/
ls: cannot access tmp/debug_kit.sqlite: No such file or directory
total 4
drwxrwxrwx 2 root root 0 Jan 22 13:13 bake
drwxrwxrwx 2 root root 0 Jan 10 21:39 cache
drwxrwxrwx 2 root root 0 Jan 16 00:03 csv
-????????? ? ?    ?    ?            ? debug_kit.sqlite          <--------
```
Maybe it possibly my machine/server/setup? I don't know.

I'm using CakePHP 3.3, DebugKit ~3.2, Linux subsystem in Windows10 running Apache2 and PHP7.1

**Comment by markstory** [comment]
Without a way to reproduce this, there isn't anything we can do.
