### ISSUE TITLE
variable's tab

### ISSUE THREAD

**Issue by siran** [cakephp/debug_kit#482]
More of a "feature request" or "enhancement":

In the "variables tab", when inspecting a multilevel array variable, the opened branches are closed if one has to temporarily close and reopen Debug_kit's Variable tab (for example, to see the actual output of the webapp).

It would be nice if the opened branches remained open, and maybe have 'collapse all' link on the tab.

**Comment by markstory** [comment]
Any idea on how you would implement that?
