### ISSUE TITLE
Fatal Memory Error

### ISSUE THREAD

**Issue by siran** [cakephp/debug_kit#483]
While doing a migration (thousands of queries involved) and having debug_kit enabled, y got a Fatal Error

    Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) 
    in .../app/vendor/cakephp/cakephp/src/ORM/Query.php on line 213

After deactivating debug_kit and doing the migration again no error occurred.

**Comment by markstory** [comment]
Well storing all the queries takes more memory. What are you hoping to see here as a resolution?

**Comment by josegonzalez** [comment]
Why are you running a migration via the web?

**Comment by ravage84** [comment]
128 MB isn't *that* much if you really work a big data set...

**Comment by thinkingmedia** [comment]
@josegonzalez he's not doing it via the web. `app/config/bootstrap.php` still loads debug_kit on the CLI.

Found this in `debug_kit/config/bootstrap.php`:

```
$debugBar = new DebugBarFilter(EventManager::instance(), (array)Configure::read('DebugKit'));

if (!$debugBar->isEnabled() || php_sapi_name() === 'cli' || php_sapi_name() === 'phpdbg') {
    return;
}
```

@markstory could the above this be the reason? Looks like something is configured even in CLI.

**Comment by markstory** [comment]
@thinkingmedia Until the `loadPanels()` method is called the query logger should not be injected, so in CLI debug kit shouldn't be actively running. At least that was the original intent.

**Comment by thinkingmedia** [comment]
@markstory thanks, disabling debug_kit likely freed enough memory and this issue is unrelated.
