### ISSUE TITLE
Add configuration to disable/reorder panels

### ISSUE THREAD

**Issue by nrother** [cakephp/debug_kit#489]
Currently all default panels are always shown. With the recent addition of the new panels the list got so long that it overflows to the next line on my small monitor I usually keep firefox on.

As far as I can see one can add custom panels using the `DebugKit.panels` configuration, but there is no way to remove the default panels.

**Comment by dereuromark** [comment]
I always thought

    'MyPanel' => false

would disable that one.
Maybe some docs missing if that works?
Otherwise I agree, this would be useful. 

Reordering might be a bit more tricky.

**Comment by lorenzo** [comment]
We just need to make the bar scroll horizontally on overflow

**Comment by nrother** [comment]
Actually I also expected that to work, but it did not... [The code](https://github.com/cakephp/debug_kit/blob/master/src/ToolbarService.php#L134) also does not look like if that would be supported.

Horizontal scrolling isn't much better that vertical scrolling, both keep the variables panel, I use most often, out of reach :frowning:  (Actually I think that horizontal scrolling is worse...)

**Comment by dereuromark** [comment]
@nrother You can make a PR to allow the disabling etc, should be a quick addition.

**Comment by lorenzo** [comment]
@nrother we can also make the variables panel the first one as it is the most commonly used

**Comment by nrother** [comment]
@dereuromark Actually I'm not quite sure how to do this in a elegant way... A simple 
```php
foreach ($this->config('panels') as $panel => $enabled) {
	if ($enabled) {
	    $this->registry->load($panel);
    }
}
```
would not work if someone tries to add a panel while disabling another one (like `'panels' => ['Custom', 'DebugKit.Timers' => false]` because the panel name is now sometimes the key and sometimes the value... Is there an elegant way to solve this?

**Comment by dereuromark** [comment]
Yes, other places in core and plugins check on the $panel being numeric here.
If so, then they are only values no key.

**Comment by markstory** [comment]
Closing as a pull request is open now.
