### ISSUE TITLE
SQLSTATE[HY000] [1049] Unknown database 'debug_kit'

### ISSUE THREAD

**Issue by RobbiNespu** [cakephp/debug_kit#492]
Hi there, I am getting this error, I don't know where to start troubleshoot the problem

**Comment by antograssiot** [comment]
See https://book.cakephp.org/3.0/en/debug-kit.html#debugkit-storage or  https://github.com/cakephp/debug_kit#database-configuration
As stated in the doc, install SQLite or configure a debug_kit database.
