### ISSUE TITLE
afterDispatch no firing

### ISSUE THREAD

**Issue by akkaweb** [cakephp/debug_kit#496]
This is a weird issue I am facing with DebugKit. It used to work before, but I am not sure when and why did it stop working.
 
After debugging the plugin itself I came to find out that `afterDispatch` was not firing for DebugKit. If I change ` 'priority' => 9999,` to ` 'priority' => 1,` in the following method, then DebugKit works fine.

` debug_kit/src/Routing/Filter/DebugBarFilter.php`

     public function implementedEvents()
     {
        return [
            'Dispatcher.beforeDispatch' => [
                'callable' => 'beforeDispatch',
                'priority' => 0,
            ],
            'Dispatcher.afterDispatch' => [
                'callable' => 'afterDispatch',
                'priority' => 9999,
            ],
        ];
     }

For now, I will keep this change, but I was wondering if anyone can point me to a fix.

**Comment by markstory** [comment]
Are you stopping the events anywhere? Stopped events won't get sent to all listeners.

**Comment by akkaweb** [comment]
@markstory I am not, at least not knowingly. I do, however, have a couple custom events setup and I will look into those to see if any is causing this.

**Comment by markstory** [comment]
Closing as I've not been able to reproduce this and the latest versions of debugkit are using middleware so events are not going to be a long term problem.
