### ISSUE TITLE
MailPreview has no method loadModel

### ISSUE THREAD

**Issue by nrother** [cakephp/debug_kit#498]
The demo code in the new mailer preview reads as follows:

```php
namespace App\Mailer\Preview;

use DebugKit\Mailer\MailPreview;

class UserMailPreview extends MailPreview
{
    public function welcome()
    {
        $this->loadModel("Users");
        $user = $this->Users->find()->first();
        return $this->getMailer("User")
            ->welcome($user)
            ->set(["activationToken" => "dummy-token"]);
    }
}
```

I tried this code and got a fatal error because `MailPreview` has no `laodModel()` method.

**Comment by dereuromark** [comment]
You just have to add the ModelAwareTrait:

    use ModelAwareTrait;

**Comment by nrother** [comment]
Yes, but this should be either in the demo code or in the `MailPreview` class. The current version of the demo code is just broken :smile:

**Comment by lorenzo** [comment]
I can just add the trait
