### ISSUE TITLE
Show a warning or throw an error if SQL Lite is not installed

### ISSUE THREAD

**Issue by burzum** [cakephp/debug_kit#503]
When setting up a new stage site we had the problem that debug kit was not showing up even the fact it was loaded and everything else was OK.

Just by checking Google if there are similar issues we found this
http://stackoverflow.com/questions/30063184/cakephp-debugkit-toolbar-not-visible

So basically installing SQL Lite solve the problem for us.

> sudo apt-get install php7.0-sqlite

However, debug kit could have saved us some time to worry about this by showing a warning or throwing an exception that it won't work correctly without SQL Lite. Can we add this?

**Comment by dereuromark** [comment]
It is already in suggest: https://github.com/cakephp/debug_kit/blob/master/composer.json#L48

**Comment by markstory** [comment]
You don't *need* SQLite, you can either have SQLite setup, or configure a different database connection in your application configuration. We could raise an error if debug kit's connection is not valid though.

**Comment by burzum** [comment]
> We could raise an error if debug kit's connection is not valid though.

That's all I'm asking for.

**Comment by davidyell** [comment]
We just his this issue with a brand new box, using a new Ansible script. /cc @hackzilla

**Comment by dereuromark** [comment]
Anyone willing to PR the suggested improvement?

**Comment by othercorey** [comment]
Doesn't this throw an exception is the connection is invalid?

**Comment by othercorey** [comment]
Closing with existing warning.
