### ISSUE TITLE
Undefined variable: packages in ComposerController.php line 93

### ISSUE THREAD

**Issue by nhristov** [cakephp/debug_kit#509]
#When checking for package updates using the DebugKit toolbar I'm getting this error:

`Undefined variable: packages [ROOT/vendor/cakephp/debug_kit/src/Controller/ComposerController.php, line 93]`

Currently using 3.9.2

**Comment by antograssiot** [comment]
What version of composer/composer is installed ?

**Comment by nhristov** [comment]
Composer version 1.4.1

**Comment by antograssiot** [comment]
I'ce fixed the issue in #510
I'llll try to update this code soon as composer can now issue json out of the outdated command.
