### ISSUE TITLE
Enhancements for Request panel: new section with browser request header + History refresh without page reload

### ISSUE THREAD

**Issue by gugleboot** [cakephp/debug_kit#511]
Possible enhancement for Request panel - new section with browser request header?? 
some of this data is already in Environment panel but Request panel is used more often and it 
would help to debug mobile connections to the website,  since you can't debug pages on mobiles without hassle (debug must be on to record everything on mobile devices, but switching panels is impossible, maybe prev / next panel button ? + responsive css).

Can History panel refresh data without page reload ? I see requests from the browser (built in dev tool) when closing/opening History panel, but its the same data even after request from other browsers or tools like REST client.

Flush History button ??

**Comment by markstory** [comment]
> Can History panel refresh data without page reload ?

It currently captures XHR requests made from the page that debugkit is on. We can't catch all the requests though as we're not a browser tool.

> Possible enhancement for Request panel - new section with browser request header??
some of this data is already in Environment panel but Request panel is used more often

Moving the request headers out of Enviroment and into the Request panel is something I've been considering but not had time to do. Same with making the layout responsive.

**Comment by gugleboot** [comment]
> Can History panel refresh data without page reload ?

Yes i'am aware of this, what i meant was - using many browsers + tools with debug on so all request are captured and having ability to just see refreshed History on one unused browser tab where debug kit was loaded before requests were made from other tools /browsers - simplifying reload/refresh for debug kit without making another request that will be logged in History panel - iframe reload maybe ?

**Comment by markstory** [comment]
Reloading the history panel is in the realm of doable. Presently reloading the iframe should do the trick, but a UI control would be easier to use.

**Comment by saeideng** [comment]
>Can History panel refresh data without page reload ?

this now  implemented
there is a button to reload history

title of issue could be change
