### ISSUE TITLE
History panel not tracking xhr requests

### ISSUE THREAD

**Issue by 34l** [cakephp/debug_kit#513]
Hi, I'm using CakePHP 3.4.3 and Debug_Kit 3.9.3, I love this tool, but this tool can't register XHR requests in history panel.

I'm begginer developer

**Comment by 34l** [comment]
Hi, I don't have any error in my browser, I make my XHR request using the ajax function of JQUERY (usually), debug kit can't get, register and update this requests in history panel.
In CakePHP 3.3.15 I don't have this issue.

**Comment by markstory** [comment]
Ok. When you're using 3.3.15 is the version of debugkit also different? The xhr tracking is done entirely in debugkit and the CakePHP version shouldn't be that impactful.

**Comment by 34l** [comment]
In my CakePHP 3.3.15 project I'm using debugkit 3.4, I think this issue come since 3.5 version of this tool, I tried use the debugkit 3.9.3 in cakePHP 3.3.15 and the issue continue.

debugkit 3.4 work correctly with CakePHP 3.4.3.

**Comment by markstory** [comment]
Pull request open now.
