### ISSUE TITLE
Basic toolbar for production server

### ISSUE THREAD

**Issue by alexlambson** [cakephp/debug_kit#516]
I have been wondering if there is a way to get a more basic version of the toolbar on a production server.

I know I can change the debug configuration on the fly in beforefilter, but this clears the cache for all users.

It would be nice to get a basic version of the toolbar (just shows request, session, and view variables) for admin users so that I can quickly see what's going on with a page even when I am not on my dev PC.

**Comment by saeideng** [comment]
i think you can change that times on the fly
like https://github.com/cakephp/app/blob/master/config/bootstrap.php#L94-L95
but if you use `_cake_model_` and `_cake_core_`
otherwise 
you can create new cache like https://github.com/cakephp/app/blob/master/config/app.default.php#L98-L105

**Comment by alexlambson** [comment]
@saeideng well, looks like it is possible to do what I am wanting to do. 

So I would just throw it into debug mode when I detect and admin user and set the debug mode to use the cache?

**Comment by markstory** [comment]
You can use the existing `forceEnable` config setting to force DebugKit on when debug=false. That combined with the panels configuration will let you do everything you've listed here.

**Comment by alexlambson** [comment]
@markstory quick question. Can I set forceEnable=true at runtime? If so, how do I do that?

**Comment by markstory** [comment]
It can be done during bootstrap before the plugin is loaded. You use `DebugKit.forceEnable` in Configure.
