### ISSUE TITLE
Blocked loading mixed active content

### ISSUE THREAD

**Issue by gugleboot** [cakephp/debug_kit#518]
When tabs are clicked console logs:

>  Blocked loading mixed active content 

reason: using http:// instead of https:// - some services use cloud flare and are enforcing https 
causing debugging impossible
possible solution: new init option to configure https , or any form of detection of the protocol

**Comment by markstory** [comment]
DebugKit uses Router::url() to generate the base url for an application. You need to make that function output the right value for your application setup. Generally this means setting the base url configuration options/constants.

Once those configuration options are correct the errors you're seeing will be resolved.
