### ISSUE TITLE
Data too long for column 'url' at row 1

### ISSUE THREAD

**Issue by nhristov** [cakephp/debug_kit#520]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1

This often happens when using OAuth with URLs that don't fit in varchar 255

Again, fix was simple:
```sql
ALTER TABLE `requests` CHANGE `url` `url` LONGBLOB NULL DEFAULT NULL;
```

**Comment by dereuromark** [comment]
Since URLs shouldnt be longer than 2048, isnt something before longblob possible?
longblob is 4294967295 - a normal "text" with 65000 chars should suffice, should it not?

**Comment by nhristov** [comment]
Sounds legit, I've just gone ahead and made it longblob, but text should suffice indeed.

**Comment by markstory** [comment]
Pull request open now.
