### ISSUE TITLE
Shell to empty and compact sqlite db

### ISSUE THREAD

**Issue by hervethouzard** [cakephp/debug_kit#522]
Hello,

A suggestion, add a shell to empty and compact sqlite db.

**Comment by markstory** [comment]
What would the shell do beyond rm tmp/debug_kit.sqlite` ?

**Comment by hervethouzard** [comment]
not necessary delete the file but remove its content

**Comment by ADmad** [comment]
> not necessary delete the file but remove its content

How is that better than simply deleting the file?

**Comment by hervethouzard** [comment]
Are you able to recreate it?

**Comment by ADmad** [comment]
If you `tmp` directory is writable by the webserver user (which it should be`) it will be automatically recreated.

**Comment by dereuromark** [comment]
> Are you able to recreate it?

Did you try it?

**Comment by dereuromark** [comment]
I am :-1: on this, as deleting this simple file should be enough. DebugKit could display a warning if the file size exceed a limit of e.g. 100MB or sth.

**Comment by hervethouzard** [comment]
Ok, I was not aware that the file will be recreated.
This suggestion can be ignored.

**Comment by lorenzo** [comment]
@hervethouzard Maybe you can add that to the documentation for DebugKit in the book? I'm sure others will find it useful
