### ISSUE TITLE
sql log panel is empty in 3.9.5 when using history

### ISSUE THREAD

**Issue by saeideng** [cakephp/debug_kit#527]
sql log panel is empty in v 3.9.5 when using history for post/put request
that works well in v 3.9.3

**Comment by markstory** [comment]
It works fine for me locally. How can I reproduce this issue?

**Comment by saeideng** [comment]
i'm sorry 
my problem is related to 
https://github.com/cakephp/debug_kit/pull/524

> History view was incorrect as panel content was shifted 2 panels to the left because of the new scroll buttons.

i saw variables content instead of sql log in sql log panel

**Comment by saeideng** [comment]
thank you to fix it

**Comment by markstory** [comment]
Cool :metal:
