### ISSUE TITLE
3.8+ has bad CakePHP version requirement

### ISSUE THREAD

**Issue by themrwilliams** [cakephp/debug_kit#530]
As of 3.8.0, debug_kit uses Cake\Mailer\Mail:: getOriginalSubject() which does not exist until Cake 3.2 (IIRC), however 3.8.0+ requires cakephp/cakephp: >=3.1.0 <4.0.

So the below combination results in a broken installation of debug_kit:
"cakephp/cakephp": "~3.1.0",
"cakephp/debug_kit": "~3.0",

If debug_kit 3.8.0+ correctly required cakephp/cakephp >= 3.2.0 that would resolve the issue.  Otherwise users have to dig a little bit to figure out where the breaking change occurred in order to get the right version of debug_kit installed.

**Comment by cleptric** [comment]
This was fixed with 5ca947a352b60ec72ba31577312e331fe5f71464

**Comment by themrwilliams** [comment]
Wonderful.  We didn't pull debug_kit 3.9.4 because the (fixed) requirement became cakephp 3.3.3+, but I don't know how that could be avoided when the problem is a broken dependency.

Thanks!  I'll close this.
