### ISSUE TITLE
Remove DebugKit's Wiki

### ISSUE THREAD

**Issue by ravage84** [cakephp/debug_kit#532]
I noticed the outdated  Wiki info through https://github.com/cakephp/app/pull/517.
So I propose to remove the current Wiki of the DebugKit.

Once removed, the confusion leading to PR cakephp/app/pull/517 should not happen again.

DebugKit for CakePHP 2.x including some documentation:
https://github.com/cakephp/debug_kit/tree/2.2
https://github.com/cakephp/debug_kit/tree/2.2#documentation

DebugKit for CakePHP 3.x including some documentation:
https://github.com/cakephp/debug_kit
https://github.com/cakephp/debug_kit#documentation

Wiki for DebugKit (outdated):
https://github.com/cakephp/debug_kit/wiki
https://github.com/cakephp/debug_kit/wiki/Configuration
https://github.com/cakephp/debug_kit/wiki/Roadmap
https://github.com/cakephp/debug_kit/wiki/Toolbar-Panels

DebugKit for CakePHP 2.x Documentation in CookBook:
https://book.cakephp.org/2.0/en/development/debugging.html#debug-kit

DebugKit for CakePHP 3.x Documentation in CookBook:
https://book.cakephp.org/3.0/en/debug-kit.html

**Comment by inoas** [comment]
Is the wiki still up to date for 2.x users?

If yes: I would place a fat orange bold deprecation warning at the top stating that the wiki is only for 2.x users and where to find the 3.x docs

**Comment by ravage84** [comment]
I would rather __move__ the configuration stuff.
The most value I see is in a centralized [roadmap](https://github.com/cakephp/debug_kit/wiki/Roadmap), if up to date, as a roadmap spans over multiple main versions, normally.

**Comment by markstory** [comment]
Closing as incorrect wiki pages have been deleted, and links to the current docs for 2.x and 3.x have been added.
