### ISSUE TITLE
Adding Intl.default_locale to Environment Panel

### ISSUE THREAD

**Issue by ravage84** [cakephp/debug_kit#533]
Today we had an issue with the localisation of numbers. I tried to find a hint on the Environment panel. Unfortunately none of the translation/localisation relevant environment variables vere available on that panel.
So I propose to add ``Intl.default_locale`` to the Environment panel.

http://php.net/manual/en/intl.configuration.php#ini.intl.default-locale

Other variables might be nice to have, too.

**Comment by markstory** [comment]
Sounds like a good idea. Any chance you want to send a pull request to add it?

**Comment by ravage84** [comment]
Should I just append it to the list of variables on this panel? Or anyhow different?
