### ISSUE TITLE
Incompatible with PHP5.4

### ISSUE THREAD

**Issue by kiseragi** [cakephp/debug_kit#534]
Hello,

MailPanel.php has the following line which is incompatible with PHP5.4:

$reflection = new ReflectionClass(Email::class);

This should read as follows:

$reflection = new ReflectionClass(get_class(new Email));

Thanks,

**Comment by ravage84** [comment]
According to the [composer.json](https://github.com/cakephp/debug_kit/blob/3.10.2/composer.json#L26), it should be compatible to PHP 5.4.

**Comment by ADmad** [comment]
If we shouldn't claim 5.4 compatibility if we are not running the test suite on 5.4

**Comment by ravage84** [comment]
Agree @ADmad , [Travis-CI Tests](https://github.com/cakephp/debug_kit/blob/master/.travis.yml#L3) only run in 5.6+ 

The framework itself [requires PHP 5.6](https://book.cakephp.org/3.0/en/installation.html#requirements) nowadays. Why should we provide more backwards compatibility for the DebugKit?

**Comment by ADmad** [comment]
We shouldn't​ :) Just bump up php version in composer config.

**Comment by ravage84** [comment]
PR is up:
https://github.com/cakephp/debug_kit/pull/535

**Comment by kiseragi** [comment]
Pls let me know if you like this closed :+1:
