### ISSUE TITLE
Undefined variable: plugin in [..../debug_kit/src/Template/MailPreview/email.ctp, line 22]

### ISSUE THREAD

**Issue by ToX82** [cakephp/debug_kit#536]
I'm using the (awesome) mail log panel to test some emails, but I'm having a little problems: when I use it, it throws some errors like this in my log files.

    Notice (8): Undefined variable: plugin in [/var/www/myapp/vendor/cakephp/debug_kit/src/Template/MailPreview/email.ctp, line 22]
    Request URL: /debug_kit/mail_preview/sent/1d7d96b4-3f2d-4f55-bd68-6162930a33b0/0
    Referer URL: http://localhost/myapp/debug_kit/toolbar/89bad51e-28f7-4784-a500-e5269ec7e01a
    Client IP: 127.0.0.1
    Trace:
    Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
    include - ROOT/vendor/cakephp/debug_kit/src/Template/MailPreview/email.ctp, line 22
    Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1025
    Cake\View\View::_render() - CORE/src/View/View.php, line 986
    Cake\View\View::render() - CORE/src/View/View.php, line 610
    Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 623
    Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 125
    Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 93
    Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 60
    [main] - ROOT/webroot/index.php, line 36

This is the code that sends the email:

    $email = new Email();
    $email->template('resetpassword')
        ->viewVars(['user' => $user])
        ->emailFormat('both')
        ->to($user['email'])
        ->from(['info@example.com' => 'Example.com'])
        ->send();

**Comment by markstory** [comment]
Closing as a pull request is open now.
