### ISSUE TITLE
Add configuration option to hide schema reflection queries

### ISSUE THREAD

**Issue by markstory** [cakephp/debug_kit#539]
From cakephp/cakephp#10644

> It's many time an inconvenience to have Schema Queries on DebugKit's SqlLog
> This is a tiny fix to avoid logging those queries based on a App.logSchemaQueries Configure > parameter.

Instead of modifying the core query loggers, it might be cleaner to do the query log filtering in DebugKit when formatting SQL for display. Perhaps DebugKit should hide schema reflection queries by default and display them when the `verboseQueries` configuration option is enabled? Other implementations that come to mind are a client side checkbox that uses localStorage for persistence and hides the offending rows dynamically, or a cookie that is sent to DebugKit eliding the queries during HTML rendering.

**Comment by ravage84** [comment]
> Instead of modifying the core query loggers, it might be cleaner to do the query log filtering in DebugKit when formatting SQL for display. 

Agree, if that's feasable.

How or where this is filtered, I have no preference, yet.

**Comment by markstory** [comment]
SQLPanel does some transformations on the queries to insert placeholders. We could flag queries as schema related at that point, allowing us to filter them out when the panel is rendered later.

**Comment by dereuromark** [comment]
I always had to manually add some filtering in my custom SQL panel here. 
Would really be nice to get this done out of the box :)

**Comment by markstory** [comment]
@dereuromark Would you be looking for a way to filter out specific patterns, or just schema reflection queries?

**Comment by dereuromark** [comment]
Just schema reflection and non-business relevant ones.
I often see questions why "what are all those queries" while those are just noise and not production relevant :) So those should just be filtered out. Everything else would be fine to keep.

**Comment by markstory** [comment]
Closing as a pull request is open now.
