### ISSUE TITLE
Email preview doesn't work with default template

### ISSUE THREAD

**Issue by berarma** [cakephp/debug_kit#541]
I can't get the email preview to work unless I set the template in the Preview class or in the Mailer.

I've found out the problem to be in line https://github.com/cakephp/debug_kit/blob/master/src/Mailer/PreviewResult.php#L45

This line tries to check that the Mailer doesn't already have a template set and sets the template to the method name. This fails because the ```Mailer::template()``` call will always return the Mailer itself since it's implemented as a magic method that will call the method with the same name in the email class then return always the Mailer for method chaining.

**Comment by lorenzo** [comment]
Do you want to send a pull request for fixing this?

**Comment by berarma** [comment]
PR is up.
