### ISSUE TITLE
Debug kit 2.2.6 Make a redirect to debug_kit/toolbar_access/sql_explain

### ISSUE THREAD

**Issue by ynaderi** [cakephp/debug_kit#543]
## Error: DebugKitController could not be found.

I searched about it and I found that the function **explainLink** of **HtmlToolbarHelper**  helper cause this problem.

When I change `return $form;` to `return null;` it works well.

**Comment by markstory** [comment]
Where are you changing that code?

**Comment by ynaderi** [comment]
`\app\Plugin\DebugKit\View\Helper\HtmlToolbarHelper.php `

```
public function explainLink($sql, $connection) {
		if (!preg_match('/^[\s()]*SELECT/i', $sql)) {
			return '';
		}
		$sql = str_replace(array("\n", "\t"), ' ', $sql);
		$hash = Security::hash($sql . $connection, 'sha1', true);
		$url = array(
			'plugin' => 'debug_kit',
			'controller' => 'toolbar_access',
			'action' => 'sql_explain'
		);
		foreach (Router::prefixes() as $prefix) {
			$url[$prefix] = false;
		}
		$this->explainLinkUid = (isset($this->explainLinkUid) ? $this->explainLinkUid + 1 : 0);
		$uid = $this->explainLinkUid . '_' . rand(0, 10000);
		$form = $this->Form->create('log', array('url' => $url, 'id' => "logForm{$uid}"));
		$form .= $this->Form->hidden('log.ds', array('id' => "logDs{$uid}", 'value' => $connection));
		$form .= $this->Form->hidden('log.sql', array('id' => "logSql{$uid}", 'value' => $sql));
		$form .= $this->Form->hidden('log.hash', array('id' => "logHash{$uid}", 'value' => $hash));
		$form .= $this->Form->submit(__d('debug_kit', 'Explain'), array(
			'div' => false,
			'class' => 'sql-explain-link'
		));
		$form .= $this->Form->end();
		return null; //I put it here  without deleting any code, I know that It's not a god place but instead of putting it at the begin of the function I but it at the end of the function before return to verify if there cause problem
		return $form;
	}
```


in my project.

**Comment by markstory** [comment]
Won't that hide/break the links?

**Comment by ynaderi** [comment]
Yes it will, but that was the fastest way that i found, because in the project we don't really need the **buttons** in the **sql log** menu of **DebugKit** to explain what happened.

**Comment by markstory** [comment]
Ok. But removing the buttons is not something I'm willing to do. Why do you want to remove them?

**Comment by ynaderi** [comment]
For sure not. I report this issue because you can review and correct it. I removed the buttons because they are not urgency for my project and I should fix the bug for my project. 
But as I said if you search [DebugKitController could not be found](https://www.google.ca/search?q=DebugKitController+could+not+be+found&rlz=1C1GGRV_frCA752CA752&oq=DebugKitController+could+not+be+found&aqs=chrome..69i57j69i59.576j0j7&sourceid=chrome&ie=UTF-8) in google you can see some website that have this problem and maybe they haven't aware yet. 
thanks.

**Comment by markstory** [comment]
But what issue do the explain links cause *you* in your application? A few of the google results looked like applications that were deploy in debug modes.

**Comment by ynaderi** [comment]
My application, it goes to`myapp/debug_kit/toolbar_access/sql_explain` but if I change the debug mode to 0 it works correct.

**Comment by dereuromark** [comment]
There was no update anymore. Resolved? Otherwise please tell us to reopen.
