### ISSUE TITLE
Feature: Add dashboard

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#554]
This is what I usually do for my plugins, and it really helps to get an overview of the functionality provided and that one doesnt have to remember specific URLs or find them in the toolbar at the bottom.

So Dashboard URL entrypoint would be `/debug-kit` directly.
It contains (ideas):

- [x] Size of current DB and button to clear/reset
- [x] Link to MailPreview

We can also then piece by piece add more stuff:
- [ ] More statistics and metrics.
- [ ] current PHP and DB versions, etc.
- [ ] Last requests to inspect in detail maybe
- [ ] Other useful dashboard toolings that can be provided that make sense to have there (more global than on the bottom of a specific page as toolbar).

**Comment by markstory** [comment]
Sounds like a neat idea. This might also be a good place to explore more history as well.

**Comment by dereuromark** [comment]
The other enhancements can be follow PRs. I will close this now.
