### ISSUE TITLE
RFC, Re-order debug bar tabs in order of most used

### ISSUE THREAD

**Issue by davidyell** [cakephp/debug_kit#556]
# Suggestion
I think it might be helpful to re-order the tabs in the debug bar so that the ones used most often are placed first.

## Context
I have recently started using an app on my Mac called Magnet, which arranges my windows. I find with a smaller browser window the 'Variables' tab, my most used one, is off the screen and I have to scroll to reach it.

## Proposed evidence
It's actually probably worth trying somehow, perhaps with Google Analytics, to gather usage data on which to base this RFC. A simple straw poll perhaps via Twitter or IRC might yield initial results.

## Compromise solution
Allow for configuration of the ordering when the plugin is setup.

**Comment by dereuromark** [comment]
Isn't this already possible using the documented https://github.com/cakephp/debug_kit/#configuration ?
By defining it there you can set your own order afaik.

**Comment by ravage84** [comment]
@davidyell 
> the ones used most often are placed first.

What is first? For man it would be left. For all the right-to-left people it's the opposite :trollface: 
Also, for some certain panels are more important than to others.

**Comment by dereuromark** [comment]
Please confirm my initial response. If this can already be configured, then we should close this.

**Comment by inoas** [comment]
Problem is that on narrow browser windows the tabs to the right are just cut off.

**Comment by markstory** [comment]
There are buttons to scroll through the toolbar though. We could also do a vertical toolbar in smaller layouts, but it will still overflow some of the time.

**Comment by davidyell** [comment]
> Isn't this already possible using the documented 
No, it isn't, according to the page you linked.

@ravage84 Which is why I suggested research to find out.

@markstory There are, but they do not expose the tabs completely, see the Variables tab below.

![Toolbar](https://i.imgur.com/CWsWq3m.png)

**Comment by ravage84** [comment]
How about using a burger-style menu, if the view port is too small? The selected/active menu will be the only snown next to the burger icon.

**Comment by dereuromark** [comment]
OK, the problem is how `$this->config($config);` merges, it doesnt know about the assoc nature of the keys and thus merges in an order that does not support this.
If we could fix that, we would easily allow projects to specify their own "desired" order :)

As for the size, burger-style sounds good!

**Comment by davidyell** [comment]
Turns out I was clicking the wrong arrow!

**Comment by davidyell** [comment]
I think this can be closed now, due to it mostly being user error.
