### ISSUE TITLE
DebugKitTransport and custom methods on TransportClasses

### ISSUE THREAD

**Issue by darxmac** [cakephp/debug_kit#558]
We have some custom mail transports, with some custom methods. When running with debug_kit and calling them in controllers, it errors out with unknown method since DebugKitTransport is injected instead of the normal Transport and returned with `$email->getTransport()`

Is there a better way to avoid this than calling 

`Configure::write('DebugKit.panels', ['DebugKit.Mail' => false]);`

**Comment by markstory** [comment]
Presently no. However, the DebugKitTransport could implement `__call` and forward all method calls to the decorated transport.

**Comment by challgren** [comment]
@darxmac What I did was write a Utility function to pull the original transport and then do my modifications on the original transport and then create a new DebugKitTransport

```
        if ($mailer->getTransport() instanceof DebugKitTransport) {
            $transport = AppUtilities::getTrueMailgunTransport();
            $transport->setOption('tag', 'reset-password');
            $transport = new DebugKitTransport($transport->getConfig(), $transport);
            $mailer->setTransport($transport);
        }
```

AppUtilities
```
    public static function getTrueMailgunTransport($mailer = 'mailgun')
    {
        $transportConfig = Email::getConfigTransport($mailer);
        $config = [
            'className' => $transportConfig['originalClassName'],
        ];
        if ($transportConfig['className'] == 'DebugKit.DebugKit') {
            unset($transportConfig['className'], $transportConfig['originalClassName']);
        }
        $config = $transportConfig + $config;
        $transport = new MailgunTransport($config);

        return $transport;
    }
```

**Comment by markstory** [comment]
Closing as I've made the DebugKitTransport better at proxying methods and properties.

**Comment by challgren** [comment]
Awesome thank you!!
