### ISSUE TITLE
Unable to get rid of routes.php & setup routes through Application::routes() only.

### ISSUE THREAD

**Issue by ADmad** [cakephp/debug_kit#559]
I was trying out loading routes through `Application::routes()` without having `config/routes.php` and things work as expected until I loaded `DebugKit`.

The problem occurs because `DebugKitMiddleware` get's added to the queue as first middleware and when it's loading it `RoutingPanel` the routes have still not been loaded as `RoutingMiddleware` which calls `Application::routes()` has still not run. Hence the `Router` tries to load `config/routes.php` resulting in error.

Since we indent to do away with `config/routes.php` in future this issue needs to be fixed.

**Comment by ADmad** [comment]
Forgot to mention that the problem occurs when loading serving plugin assets through `AssetMiddleware`.

**Comment by ADmad** [comment]
```
Warning (2): include(/myapp/config/routes.php): failed to open stream: No such file or directory [CORE/src/Routing/Router.php, line 1095]
Code Context

include - CORE/src/Routing/Router.php, line 1095
Cake\Routing\Router::_loadRoutes() - CORE/src/Routing/Router.php, line 1095
Cake\Routing\Router::routes() - CORE/src/Routing/Router.php, line 1070
DebugKit\Panel\RoutesPanel::summary() - ROOT/vendor/cakephp/debug_kit/src/Panel/RoutesPanel.php, line 33
DebugKit\ToolbarService::saveData() - ROOT/vendor/cakephp/debug_kit/src/ToolbarService.php, line 199
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php, line 53
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 81
[main] - ROOT/webroot/index.php, line 37
```

**Comment by markstory** [comment]
> Forgot to mention that the problem occurs when serving plugin assets through AssetMiddleware.

So static assets have the 404s?

**Comment by ADmad** [comment]
No,  they have the error  shown at top followed by actual file content.
