### ISSUE TITLE
Variables tab broken when Router used in Entity classes

### ISSUE THREAD

**Issue by kyleweishaupt** [cakephp/debug_kit#562]
Hi. I'm currently experiencing an issue with the Variables tab not opening. After some digging around I noticed DebugKit is getting a 404 error that is throwing `Cake\Routing\Exception\MissingRouteException`, causing the tab to never open.

The more specific error is `Error: A route matching "array ( 'controller' => 'Posts', 'action' => 'upload', 0 => 123, '_ext' => 'json', 'plugin' => 'DebugKit',)" could not be found.`

The exception seems to be coming from my entity classes generating their own endpoint URLs. Some of my entities include code like the following:

```
/**
 * virtual 'upload_file_url' property
 *
 * @return string
 */
protected function _getUploadFileUrl()
{
	return Router::url([
		'controller' => 'Posts',
		'action' => 'upload',
		$this->id,
		'_ext' => 'json'
	], true);
}
```
My routes.php doesn't have anything custom in it and uses the DashedRoute fallback. The URLs work fine throughout the rest of the app. Here's what my routes.php is pretty much like: 
```
<?php
use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {

    // Home Page (Dashboard)
    $routes->connect('/', [
        'controller' => 'App', 
        'action' => 'dashboard'
    ], [
        'name' => 'dashboard'
    ]);

    // RequestHandler
    $routes->extensions([
        'json',
        'pdf'
    ]);

    $routes->fallbacks(DashedRoute::class);
});

Plugin::routes();
```

This is occurring on the latest CakePHP (3.5.5 at this time) and the latest DebugKit release.

Any help or suggestions for a better way of passing endpoint URLs around my app are greatly appreciated :)

**Comment by markstory** [comment]
Looks like the route array is inheriting the plugin key from the current request. You might want to try adding`plugin => false` to your routing array. That should resolve this, and ensure your entity URLs work in other plugins as well.

**Comment by ADmad** [comment]
Adding `'plugin'=>false` to your url array should fix your problem. Without that you will get similar whenever the entity instance is created for a plugin action.

**Comment by kyleweishaupt** [comment]
Thank you! Setting `plugin => false` solved the issue
