### ISSUE TITLE
Issues 404 latest version of debug_kit 3.11.2

### ISSUE THREAD

**Issue by xsyfrost** [cakephp/debug_kit#564]
Debug_kit : 3.11.2
cakephp: 3.5.6

The routes.php are making troubles in rendering debug_kit.
This line (hereunder) are looking for the url of debug_kit in the MAIN WEBROOT folder (as in my conf of nginx the documentRoot folder is /.../app/webroot/):

Router::plugin('DebugKit', ['path' => '/debug-kit'], function (RouteBuilder $routes) {

That means debug_kit is looking for /.../app/webroot/debug_kit/some_token which is the main project folder what is generating a 404 error. In fact it should go to the vendor folder.

I solved the trouble in replacing:
Router::plugin('DebugKit', ['path' => '/debug-kit'], function (RouteBuilder $routes) {
by the old one
Router::plugin('DebugKit', function (RouteBuilder $routes) {
And now it is working again

**Comment by dereuromark** [comment]
Did you clear the cache etc?
This sounds very strange and is not reproducible here with 3.5.6.

**Comment by HavokInspiration** [comment]
I had the same issue after upgrading.
I had to clear my browser cache, remove the `debug_kit` symlink already created in webroot and run `bin/cake plugin assets symlink` again for it to finally use the new JS file which contains the good iframe URL.

**Comment by dereuromark** [comment]
Sounds like this is clarified. Clearing cache and fresh symlinks do the trick.

**Comment by xsyfrost** [comment]
Didn't solved the trouble for me.
I deleted in /app/webroot the debug_kit folder
Then i executed bin/cake plugin assets symlink
I uses a cache killer in the browser. 
As expected i got the same error
![debug_kit](https://user-images.githubusercontent.com/9862529/33546845-68d92986-d8e2-11e7-9784-d82aaa2b5c42.png)

**Comment by xsyfrost** [comment]
Sorry my fault i forgot some changes i made
You can close the topic
