### ISSUE TITLE
sql-formatter 

### ISSUE THREAD

**Issue by Oxicode** [cakephp/debug_kit#566]
https://github.com/jdorn/sql-formatter/

**Comment by markstory** [comment]
What is the goal of this issue?

**Comment by tersmitten** [comment]
Probably to (fancy) format queries in the "Sql Logs" tab

**Comment by lorenzo** [comment]
@tersmitten isn't that what we use already for formatting the queries? https://github.com/cakephp/debug_kit/blob/master/composer.json#L31
