### ISSUE TITLE
Ability to see SQL generated statement with parameters substituted

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/debug_kit#568]
_From @brettl on June 11, 2017 19:47_

* [x] enhancement

* CakePHP Version: 3.next
When running the ->sql() function on an ORM call allow the ability to see the sql statement with the parameters in the place holders.

Currently when calling sql on the ORM you will see example "where id = :c1"
allow the ability to call an example ->sql(1) or ->sql()->substituted(); and the resulting sql will now be "where id = 1"
this would allow the ability to take your sql being generated and run in a sql viewer /editor and run your command and possibly see if you are producing the incorrect data or if you are generating the incorrectsql statement

_Copied from original issue: cakephp/cakephp#10761_

**Comment by thinkingmedia** [comment]
_From @dereuromark on June 11, 2017 20:19_

Isn't `(string)...->sql()` casting doing this? Showing you the final SQL query that would be run?

**Comment by thinkingmedia** [comment]
_From @markstory on June 12, 2017 5:17_

@dereuromark Right now there isn't a way to get the SQL query that will be executed with placeholders populated from the database layer. You can only get that information by interpolating the parameters yourself, or using a tool like debug kit.

We won't be able to chain off of `sql()`, but we could have a new method that returns the populated SQL query.

**Comment by thinkingmedia** [comment]
_From @makallio85 on June 26, 2017 5:27_

+1 to this

**Comment by thinkingmedia** [comment]
_From @lorenzo on June 29, 2017 13:45_

I'd like to do this for when calling `debug($query)`

**Comment by thinkingmedia** [comment]
Oh I would like to work on this. I have a working example already and just need to migrate it to the debugKit.

Always including the variable bindings is *risky*. For example; some of the IN operators can be huge which makes reading the SQL difficult. So I will make this an optional feature.

**Comment by elovin** [comment]
Is this only possible with the debug kit in debug mode?  I would like to use cakephp orm to build the sql query and then send the full sql string as a async database query with another library (in my case reactphp MySQL).  To do this I would need the full sql query string including params, is that possible?

**Comment by markstory** [comment]
No that isn't possible. Inserting the parameters into a SQL string defeats prepared statements which is one of the main ways Cakephp prevents SQL injection.  You might be able to serialized and deserialize a query object depending on parameter values and attached processing functions instead.

**Comment by elovin** [comment]
Yes of course you are right, my question was ill formed.

What I need is to get the params from the cakephp query so that I can use them in the prepared statement of the async db query. 

I realized that that's already possible if I call `$query->getValueBinder()->bindings(); `after calling `$query->sql();` and get the values from the resulting array.

I then replace the cakephp placeholders with the placeholder from reactphp mysql which is using ? as a placeholder. `mb_ereg_replace("(?<=\s):c[0-9]+(?=\s|$|\)|\])", '?', $sql)`

**Question:**

Can I expect the cakephp placeholders in the sql string to always match the order of the params array even if I use subqueries ?
E.g. `SELECT ... c:0 ...  c:1 ...` in the string and `[c:0 => [..], c:1 => [..]]` in the params array even when using subqueries in matching, contain ... (I tested this with some queries so this seems to be the case) ?

**Comment by markstory** [comment]
> Can I expect the cakephp placeholders in the sql string to always match the order of the params array even if I use subqueries ?

Generally yes. However, you're going into undocumented and generally untested areas of behavior so I won't make any strong promises.

**Comment by mehov** [comment]
I am working on an endpoint that responds with JSON, so I can't use the debug kit on that exact method. (Unless I refactor it to temporarily have a template.)

This method runs an SQL query that I need to look at, but if I call `->sql()` on it, obviously I'm getting the placeholders. According to [`class-Cake.ORM.Query.html#sql()`](https://api.cakephp.org/3.9/class-Cake.ORM.Query.html#sql()) there doesn't seem to be an argument or a flag I could pass to make it return the full query, and I'm curious why is that.

(I did read the above regarding the SQL injections, and maybe I'm missing the point, but either way nothing stops me from taking the `->sql()` output and filling the placeholders with values if I really wanted to harm myself. As in, obtain the raw query that's being hidden from me, and take it elsewhere.)

Here's my case. The query I'm working on doesn't return any data. I want to take the raw SQL, and play with it in MySQL Workbench until I figure out why. Then I would adjust my CakePHP query conditions accordingly.

Every time I run into this situation, I `debug()` my `$query` and manually copy-paste the values into the placeholder'd SQL. I guess there must be reason why the framework won't have an option to output the full SQL it's about to run, but why is that?
