### ISSUE TITLE
ToolbarService::injectScripts should timestamp JS file to fix caching conflicts

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/debug_kit#570]
I was running a previous version of DebugKit and updated to the latest. After doing this the DebugKit icon on the app's pages failed to load. Inspecting the `<iframe>` source code revealed a routing not found error which sent me down the wrong path to fix it.

My browser had cached an outdated version of `toolbar.js`. Once I cleared the cache the DebugKit bar appeared.

The `ToolbarService::injectScripts` should append a timestamp taken from the `toolbar.js` file. This should be added as a query parameter `/debug_kit/js/toolbar.js?384773372` (just a unix timestamp).

This will resolving cache issues whenever the file is changed.

**Comment by raul338** [comment]
To keep cache, the query should be the version
Like this `/debug_kit/js/toolbar.js?v=3.11.3`

**Comment by thinkingmedia** [comment]
@raul338 there isn't a way to know the version number of the plug-in at run-time. Not from what I could find. It's also not guaranteed to always work. (i.e. if a debug kit developer manually makes changes while working on a *new* version).
