### ISSUE TITLE
Debug kit breaks window.postMessage with objects.

### ISSUE THREAD

**Issue by riddlemd** [cakephp/debug_kit#576]
The debug  javascript files onMessage handler does not account for messages that are not strings and causes the whole onMessage stack to be tossed some times...

To fix it change line 270 in webroot\js\toolbar-app.js from:

`if (event.data.indexOf('ajax-completed$$') === 0) {`

to

`if (typeof event.data === 'string' && event.data.indexOf('ajax-completed$$') === 0) {`

**Comment by markstory** [comment]
Pull request open now.
