### ISSUE TITLE
invalid request history 

### ISSUE THREAD

**Issue by saeideng** [cakephp/debug_kit#578]
sometimes you see extra request in the debug_kit that is invalid

![debug_kit_asset](https://user-images.githubusercontent.com/8215801/34848154-fb2083ac-f732-11e7-8a15-eae7a529af89.png)

also number of request history  limited to `10`
with this invalid request you lost previous request history

suggestions:
1) adding filters buttons to filter (/remove )  assets (js/css,...) 
2) adding a  button to remove invalid histories ( runtime ) , and reload list
3) capability to increase limitation from `10` 
4) pagination ( @markstory )

I like 2

**Comment by markstory** [comment]
Are these requests handled by the asset middleware?  We could add pagination to the request history as another option.

**Comment by saeideng** [comment]
>Are these requests handled by the asset middleware?

```php
//APP/Application.php
    public function middleware($middlewareQueue)
    {
        $middlewareQueue
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(ErrorHandlerMiddleware::class)

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(AssetMiddleware::class)

            // Add routing middleware.
            ->add(new RoutingMiddleware($this));

        return $middlewareQueue;
    }
```

this problem occur in several my apps (probably in all )
with cake 3.5, 3.4 ,....

**Comment by markstory** [comment]
Ok. Are those assets coming from plugins? That would explain why cake is handling them and your webserver is not serving them directly.

**Comment by saeideng** [comment]
>Ok. Are those assets coming from plugins? 

Yep, local plugin 
I use `plugins/... ` for templates 

for example `plugins/BackEnd/webroot/bootstrap/css/bootstrap.min.css` for above screenshot

**Comment by saeideng** [comment]
@markstory  I tested 
I added `touch(time().'_.txt');` into first of  `webroot/index.php`
and I try load 2 css directly from web

I add new/fresh plugin for test 
```
/config/bootstrap.php
Plugin::load('New'); // this plugin just have 1 css file 

//browser
http://site.local/test/new/css/test.css // creates `1515785147_.txt`
http://site.local/test/css/test.css // OK (without creating `txt` file )

**Comment by markstory** [comment]
Ok. It makes sense that debugkit would be logging asset requests as they are being handled by CakePHP. Would being able to paginate through history help solve your problem?

**Comment by saeideng** [comment]
also I added 
`touch(time().'_asset');` into `AssetMiddleware::__invoke()`
`touch(time().'_router');` into `RoutingMiddleware::__invoke()`

just first test (asset ) creates file

**Comment by saeideng** [comment]
>Would being able to paginate through history help solve your problem?

probably

**Comment by saeideng** [comment]
can we add a flag to the request object to detecting/showing  assets from other request?
so, we can ignore those request in the debug_kit

**Comment by markstory** [comment]
> can we add a flag to the request object to detecting/showing assets from other requests?

Could add a response header :smile:

**Comment by dereuromark** [comment]
PR open.
