### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/debug_kit#581]
It would be very cool if all the phrases contained in the debug were in the I18N translation standard. When I start a project I always translate debug_kit, but it always stays in the middle because a lot of it does not use functions like __ ("") and __d ().

Please!

**Comment by dereuromark** [comment]
Why would you need that for a debugging tool? All other things for local dev are also not translated - and shouldn't be (necessary) IMO.

**Comment by dereuromark** [comment]
The energy here is much better spent on e.g. fixing a few open issues/tickets https://github.com/cakephp/debug_kit/issues for example.
Functional completeness/correctness outweighs here any sugar like having the debugging tool spit out some translated stuff (some as in almost nothing, as most exceptions and other things are still all always in English by the way).

**Comment by allanmcarvalho** [comment]
Well, I do not need to do the translation, whoever wants to translate the .po file ... But anyway I think the plugin should completely use the I18N or completely not to use it... This is kind of bang. Lack of standardization.

**Comment by markstory** [comment]
@allanmcarvalho Any chance you'd be able to help add translation functions in the places it is missing?

**Comment by dereuromark** [comment]
@allanmcarvalho I agree. But then it would probably make sense to remove all i18n, as we do for Core exception and debugging messages/tools.

**Comment by allanmcarvalho** [comment]
@markstory Yes I can. Which branch should I make the fork? The Master?

@dereuromark I think the following way, as the i18n is optional, that is, it translates who they want otherwise it shows the original message. I think it's worth implementing. We are talking about an open source project where the use is very widespread and varied ... A use for translation? How about a teacher in college? He could translate so that his students understood the tool better.

**Comment by markstory** [comment]
@allanmcarvalho Master is good :+1:

**Comment by dereuromark** [comment]
https://github.com/cakephp/debug_kit/pull/582 opened
