### ISSUE TITLE
Current release (3.14.0) is broken with syntax errors

### ISSUE THREAD

**Issue by highstrike** [cakephp/debug_kit#585]
The pull request #582 introduced syntax errors everywhere.

Therefore the tabs Cache, Mail and Packages are no longer working.

@allanmcarvalho did you even TEST the changes before submitting the pull request? Travis couldn't catch them because it doesn't test `.ctp` files.

**Comment by dereuromark** [comment]
I was strongly against the PR for exactly that - and other - reasons.
It only creates problems, and doesn't solve an actual one.

True, travis was green ( https://travis-ci.org/cakephp/debug_kit/builds/339058933?utm_source=github_status&utm_medium=notification ).
We can revert IMO.

**Comment by dereuromark** [comment]
Is it solved with https://github.com/cakephp/debug_kit/pull/586 ?
Then you can close this one here.

**Comment by allanmcarvalho** [comment]
Look ... I'm no genius, sometimes I make mistakes, especially when ignoring tests. I'm sorry ... Sorry. There was a small syntax error, nothing related to the implementation of I18n. I already did the pull request that solves them ....

Once again, I'm sorry.!

**Comment by dereuromark** [comment]
Thank you for the quick response and fix @allanmcarvalho

**Comment by ADmad** [comment]
Closing as related PR is open.

**Comment by allanmcarvalho** [comment]
I thank you for understanding.

**Comment by tersmitten** [comment]
Maybe it's useful to add something like this to `.travis.yml`:

```sh
[ "$(find . \( -path './vendor' \) -prune -o -type f \( -name '*.ctp' -o -name '*.php' \) -print0 | xargs -0 --no-run-if-empty -L1 -i'{}' php -l '{}' | grep -vc 'No syntax errors')" -eq 0 ];
```

**Comment by highstrike** [comment]
@allanmcarvalho nobody has to be a genius to TEST what you actually changed and see if its still working

Quick fix but incomplete, i've put my own pull request with errors found by my IDE.

@dereuromark i'm :thumbsup: for a revert, this was quite pointless

**Comment by dereuromark** [comment]
@tersmitten Give it a shot in travis as PR.

**Comment by ADmad** [comment]
Everyone makes mistakes, one way to avoid them is not make pointless changes. :slightly_smiling_face:

**Comment by markstory** [comment]
I apologize for tagging a broken release. That is on me, I should have checked the code before tagging the release.
