### ISSUE TITLE
CakePHP 3.6.0 don't show debugkit panels

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/debug_kit#608]
I made a clean install from CakePHP 3.6.0, but it don't works. In my others applications with cake 3.5.x it works. To be sure I came back to that application for version 3.5.15 and it worked.

In 3.5.15 on view-source from Google Chrome appears the debug_kit "script" tag, but in 3.6 It is not there...

**Comment by saeideng** [comment]
add forceEnable into your `config/bootstrap.php`

```php
if (Configure::read('debug')) {
    Configure::write('DebugKit', ['forceEnable' => true]);
    Plugin::load('DebugKit', ['bootstrap' => true]);
}
```
and see result

**Comment by allanmcarvalho** [comment]
Now works... Tank you..

**Comment by saeideng** [comment]
because you are not using a local domain like `localhost`/`dev`/`local`/`192`/`10`/ ....
