### ISSUE TITLE
sqlite3.so not detected

### ISSUE THREAD

**Issue by parti-zanu** [cakephp/debug_kit#610]
https://github.com/cakephp/debug_kit/blob/81829b445053b140edfb5d153b1be8b8e0ad32e2/config/bootstrap.php#L32

in_array('sqlite', PDO::getAvailableDrivers()) will return **TRUE if pdo_sqlite.so** is loaded but will return **FALSE if sqlite3.so** is loaded

**Comment by lorenzo** [comment]
DebugKit requires. pdo_sqlite, not sqlite3
