### ISSUE TITLE
isSuspiciouslyProduction() too silent

### ISSUE THREAD

**Issue by parti-zanu** [cakephp/debug_kit#611]
https://github.com/cakephp/debug_kit/blob/81829b445053b140edfb5d153b1be8b8e0ad32e2/src/ToolbarService.php#L133

isSuspiciouslyProduction() should **at least log an error** about the TLD check before deciding not to activate DebugKit

TLD restrictions are not documented.

**Comment by markstory** [comment]
Logging and documentation sound like good ideas.

**Comment by markstory** [comment]
Logging added.
