### ISSUE TITLE
Error logging even though force enabled

### ISSUE THREAD

**Issue by davidyell** [cakephp/debug_kit#616]
For some reason, even after configuring the `forceEnable`, DebugKit is logging 10 or so force disables per request to my error log.

In my `config/bootstrap.php` I have the following.

```php
// Only try to load DebugKit in development mode
// Debug Kit should not be installed on a production system
if (Configure::read('debug')) {
    Configure::write('DebugKit.forceEnable', true);
    Plugin::load('DebugKit', ['bootstrap' => true, 'routes' => true]);
}
```

![Logs per second is over 9000!](https://i.imgur.com/xoG0rEg.png)

References, #595

**Comment by davidyell** [comment]
@lorenzo Yep, it's displaying, but logs anyway.

**Comment by markstory** [comment]
I can take a look as I added those logging statements.

**Comment by markstory** [comment]
Pull request open now.

**Comment by davidyell** [comment]
Thanks @markstory
