### ISSUE TITLE
DebugKit loads my app ToolbarHelper instead of its own

### ISSUE THREAD

**Issue by AlexMax** [cakephp/debug_kit#618]
I have a helper in my app called ToolbarHelper.  It appears to me that DebugKit will, on some of the panels, try to load the ToolbarHelper in my app.  This fails to work, which leads to panels that return a 500 error.

This is DebugKit verison **3.14.1** running on CakePHP **3.5.12**.

**Comment by markstory** [comment]
I'll get that fixed up.

**Comment by markstory** [comment]
Pull request open now.
