### ISSUE TITLE
Cake 3.6.* & ES Plugin 1.* causes a type error

### ISSUE THREAD

**Issue by burzum** [cakephp/debug_kit#624]
> Argument 1 passed to Elastica\Client::setLogger() must implement interface Psr\Log\LoggerInterface, instance of DebugKit\Database\Log\DebugLog given, called in C:\xampp\htdocs\wa3\vendor\cakephp\debug_kit\src\Panel\SqlLogPanel.php on line 67

This happens with debug kit 3.16.0 but not with 3.14.2. And that's all I've changed to make it work again. So there must be something wrong with 3.16.0. Guess a type was added somewhere.

**Comment by makamo** [comment]
Same with UseMuffin/Webservice

**Comment by markstory** [comment]
It is likely this line https://github.com/cakephp/debug_kit/blob/e7d7fc3bce3a89b5fc57d34ca8666175c52e3d4a/src/Panel/SqlLogPanel.php#L67

which would have been changed to accommodate the deprecated `logger()` method on `Connection`. This method name is clearly in use by other classes.

**Comment by burzum** [comment]
@markstory this explains the problem, but doesn't provide a solution?

**Comment by davidyell** [comment]
How come this has been closed without a resolution?

**Comment by josegonzalez** [comment]
Fixed on the other end? https://github.com/cakephp/elastic-search/pull/156

**Comment by ADmad** [comment]
@josegonzalez The issue affects other community code too, for e.g. mufin/webservice. IMO the fix should be done in debugkit.

**Comment by lorenzo** [comment]
Didn’t the pull request I merged fix his?

**Comment by davidyell** [comment]
@lorenzo If it did, then it needs a release. I've just created a new fresh application on `3.6.2` with the Webservice plugin, and when I force enable DebugKit, I get a fatal for the logger.

I would recommend this issue be re-opened.

**Comment by ceeram** [comment]
wrt muffin-webservice plugin, we can probably get by this by adding this in its Connection class:

```
    /**
     * no-op
     *
     * to avoid non-PSR loggers (Crud, DebugKit) getting passed to webservice driver, which requires PSR implementations
     */
    public function setLogger()
    {

    }
```

**Comment by davidyell** [comment]
> This method name is clearly in use by other classes outside of CakePHP.

Yes, by the PSR3 Logger at least.

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#4-psrlogloggerawareinterface

**Comment by Nic0tiN** [comment]
Hello,

I'm sorry to reopen but I just upgraded to Cakephp 3.6.7 and I'm facing the same issue. @lorenzo, is your merge part of a specific release?

**Comment by ADmad** [comment]
SqlPanelLog needs to be fixed to first check is setLogger() method exists and if not fallback to using old method for BC.

**Comment by Nic0tiN** [comment]
I'd like to help and make things move but I don't know where to look to fix that issue...
Doesn't look like either debug_kit nor webservice is wrong.
@davidyell workaround is correct except that I had to name my method `logger` instead of `setLogger`.

```php
class MyDriver extends AbstractDriver
{
    ...
    /**
     * Workaround compatibility issue between Cakephp/DebugKit and Muffin/WebService
     *
     * @return void
     */
    public function logger()
    {
        $this->logger = new NullLogger();
    }
}
```

**Comment by ADmad** [comment]
@Nic0tiN You need to add a `method_exists()` check for method name `setLogger` above this line

https://github.com/cakephp/debug_kit/blob/e7d7fc3bce3a89b5fc57d34ca8666175c52e3d4a/src/Panel/SqlLogPanel.php#L67

and if it returns `false` call `$connection->logger()` instead.

**Comment by Nic0tiN** [comment]
@ADmad Doing so won't change the fact that DebugKit is not passing a `Psr\Log\LoggerInterface` object. To workaround that, I would have to remove the type hinting of `Psr\Log\LoggerAwareTrait::setLogger`. Am I missing something?

**Comment by davidyell** [comment]
@Nic0tiN Yes you are. If you implemented a `method_exists()` check the method wouldn't be called at all, so the type hinting wouldn't matter.

**Comment by Nic0tiN** [comment]
@davidyell Not sure to understand what you mean. Following @ADmad comment, it would call `MyDriver::logger()` instead of `Muffin\Webservice\AbstractDriver::setLogger`.
```php
            if (method_exists($connection, 'setLogger')) {
                $connection->setLogger($logger);
            } else {
                $connection->logger($logger);
            }
```

**Comment by davidyell** [comment]
Yep, and the `logger` method isn't a PSR3 interface method.

**Comment by dereuromark** [comment]
PR open.

**Comment by josegonzalez** [comment]
@davidyell this was fixed in release 3.16.4.

**Comment by davidyell** [comment]
If it was, the client-side we were implementing was faulty. As we hit the same roadblock even with the latest release of DebugKit.

It's either implement the type hint and have DebugKit fail to pass the correct class, or remove the type hint and fail because the method signatures do not match.

I've been stuck on other projects, but this was raised by our front-end team today.

When I get time I will test again using the new release. I've commented on the pull request that I'd like to see a test-case for this, as all evidence so far seems shaky to me, and reading the code I'm not convinced it'll solve the issue in plugin and userland code. Although I'm happy to be proven wrong 😄

**Comment by hackzilla** [comment]
@josegonzalez I can't see how it'd work.

The fix would be to implement LoggerInterface

e.g.

```php
namespace DebugKit\Database\Log;

class DebugLog extends QueryLogger implements Psr\Log\ LoggerInterface {
}
```

otherwise I can't see how this would ever work?

```php
    public function setLogger(LoggerInterface $logger);
```

**Comment by hackzilla** [comment]
@davidyell The more I think about it, maybe this should be a change for cakephp/cakephp?
