### ISSUE TITLE
DebugKit stopped showing after Cake Update (Application.php)

### ISSUE THREAD

**Issue by Cafnio** [cakephp/debug_kit#630]
Hi there.

I've updated my cakephp from 3.4.10 to 3.6.4. Many deprecations, but everything else is ok.

Also updated debug_kit to 3.161.

During this upgrade, i've checked that my cake app missed some files, and some were outdated. I've updated webroot/index.php, created src/Application.php and created config/requirements.php, all from skeleteon App.

The thing is: as soon as I put the code on Application.php, the debug kit stops showing. As soon as I remove the code, it shows.

I believe i'm missing something, but can't find what It is.

Thanks

**Comment by markstory** [comment]
Is DebugKit plugin still being loaded in your application's bootstrap.php, or via `addPlugin()` in your `Application::boostrap()` method?

**Comment by dereuromark** [comment]
What's your TLD? most likely you didnt also configure your whitelist for local dev :)

**Comment by Cafnio** [comment]
Well, guess was missing some sleep. I've mixed up the index.php (didn't changed the webroot/index.php, but the other).

Sorry for the mess and keep up the good work!

**Comment by mehov** [comment]
To whoever finds this: what @dereuromark means above is this:

> 2018-07-24 14:58:49 Warning: DebugKit is disabling itself as your host `dev.example.com` is not in the known safe list of top-level-domains (localhost, dev, invalid, test, example, local). If you would like to force DebugKit on use the `DebugKit.forceEnable` Configure option.

However, I couldn't get it to work using `safeTld` with either of these:

    Configure::write('DebugKit.safeTLD', ['dev.example.com']); // didn't help
    Configure::write('DebugKit', ['safeTLD' => ['dev.example.com']]); // didn't help either
    Plugin::load('DebugKit', ['bootstrap' => true]);

However, the good old `forceEnable` worked:

    Configure::write('DebugKit.forceEnable', true);
    Plugin::load('DebugKit', ['bootstrap' => true]);

**Comment by dereuromark** [comment]
mind your casing saveTld not saveTLD.
=> https://github.com/cakephp/debug_kit/pull/623

**Comment by arturmamedov** [comment]
`bin/cake cache clear_all` worked for me https://github.com/cakephp/debug_kit/issues/684 
cause it seems that Cache of `_cake_routes_ ` not set duration +2 seconds in debug = true
