### ISSUE TITLE
Fatal error on CakePHP 3.6.5

### ISSUE THREAD

**Issue by asgraf** [cakephp/debug_kit#631]
After upgrading cakephp from 3.6.4 to 3.6.5 following fatal error started to appear:
> Fatal error: Cannot use Cake\Core\Plugin as Plugin because the name is already in use in [...]/vendor/cakephp/debug_kit/src/ToolbarService.php on line 16

This error does not occur on CakePHP 3.6.4 or earlier versions

How to reproduce:
1) Make a fresh installation of cakephp/app
2) Try to visit welcome page via browser or try to run bin/cake shell

**Comment by saeideng** [comment]
confirm :+1: 

I could to see error via `bin/cake shell`  => with cake 3.6.5
but in web (browser ) not

**Comment by saeideng** [comment]
related change https://github.com/cakephp/cakephp/commit/6b35611a

**Comment by markstory** [comment]
Fixed in 3.16.3 😄

**Comment by dereuromark** [comment]
This is the 2nd plugin. Will this now happen to everyone that adds this class?

**Comment by markstory** [comment]
@dereuromark Only if they are also importing `Cake\Core\Plugin` in a top level class. Apparently I frequently do that and I don't write test around my plugin classes.

**Comment by dereuromark** [comment]
But every app and plugin is doing that in the bootstrap, so it will effect every one, right?

**Comment by markstory** [comment]
Its not a problem if the application imports Cake\Core\Plugin. Plugins will have this problem if they use root level namespaced classes like `AssetCompress\AssetScanner` but they will not have issues if they only use class names like `AssetCompress\Middleware\AssetCompressMiddleware` as the extra namespace prevents conflicts.

**Comment by dereuromark** [comment]
In a rather fresh app, when now having

    Plugin::load('DebugKit', ['bootstrap' => true]);

with latest tag
you get

> Exception: Class 'DebugKit\ToolbarService' not found in [/.../demo.local/vendor/cakephp/debug_kit/config/bootstrap.php, line 26]

**Comment by markstory** [comment]
@dereuromark I don't get that same error locally. The `DebugKit\ToolbarService` is still part of the plugin and has the correct class/filename.

**Comment by dereuromark** [comment]
Interesting problem. This whole plugin loading of different plugins and different bootstrapping etc is a bit crazy.

**Comment by saeideng** [comment]
>Fixed in 3.16.3

looks we can close it
