### ISSUE TITLE
You no longer need to call `Plugin::routes()` after upgrading to use Http\Server

### ISSUE THREAD

**Issue by tersmitten** [cakephp/debug_kit#634]
I'm trying to upgrade our application to `3.6.*`. As I understand the new way of loading plugins is like this:

```php
class Application extends BaseApplication
{
    /**
     * {@inheritDoc}
     */
    public function bootstrap()
    {
        // Call parent to load bootstrap from files.
        parent::bootstrap();

        $this->addPlugin(\DebugKit\Plugin::class, ['bootstrap' => true]);
    }
```

but if I do so I'll get this error. 

```
Deprecated (16384): You no longer need to call `Plugin::routes()` after upgrading to use Http\Server. See https://book.cakephp.org/3.0/en/development/application.html#adding-the-new-http-stack-to-an-existing-application for upgrade information. - /vagrant/www/foo.dev-bar/vendor/cakephp/debug_kit/config/bootstrap.php, line: 50
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. [CORE/src/Core/functions.php, line 312]
```

Am I doing something wrong or is this a bug?

**Comment by saeideng** [comment]
update your debug_kit to latest version `3.16.3`

**Comment by tersmitten** [comment]
You're right, I thought I was already using the latest version but I wasn't (`3.15.3`)

**Comment by abhilashlohar** [comment]
How to update debug_kit?

**Comment by saeideng** [comment]
`composer update cakephp/debug_kit ` 
or 
`composer update` for all packages

**Comment by whaodu** [comment]
I can not solve this problem by update debug_kit?

**Comment by YoshikawaTaiki** [comment]
My CakePHP3.6 application's cakephp/debug_kit is version 3.16.4.
But I can not solve this problem...

**Comment by garas** [comment]
Checklist:

* Update `debug_kit` to version 3.16+
* Remove `Plugin::routes()` from `config/routes.php`
* Remove `Plugin::load('DebugKit')` from `config/bootstrap.php`
* Add `$this->addPlugin(\DebugKit\Plugin::class);` to `function bootstrap()` in `src/Application.php`


See [PR #610](https://github.com/cakephp/app/pull/610/files) and [PR #617](https://github.com/cakephp/app/pull/617/files)

**Comment by sourjya** [comment]
> Checklist:
> 
> * Update `debug_kit` to version 3.16+
> * Remove `Plugin::routes()` from `config/routes.php`
> * Remove `Plugin::load('DebugKit')` from `config/bootstrap.php`
> * Add `$this->addPlugin(\DebugKit\Plugin::class);` to `function bootstrap()` in `src/Application.php`
> 
> See [PR #610](https://github.com/cakephp/app/pull/610/files) and [PR #617](https://github.com/cakephp/app/pull/617/files)

Thanks. Worked perfectly for me.
