### ISSUE TITLE
Deprecation warnings aren't logged

### ISSUE THREAD

**Issue by berarma** [cakephp/debug_kit#638]
CakePHP 3.6.10
DebugKit 3.16.4

I have to disable DebugKit so that deprecation warnings get logged. It's useful having both on at the same time when developing. It's nice having a panel for deprecation warnings but some of them are hard to catch there and we have to rely on logs.

**Comment by dereuromark** [comment]
You can just disable this panel, as documented.

**Comment by berarma** [comment]
Thanks @Deuromark. That's better than disabling DebugKit.

**Comment by berarma** [comment]
I think this isn't a solution though.

**Comment by markstory** [comment]
@berarma Ok, what solution would you like to see? The panel was added after we received numerous issues and feedback about deprecation warnings 'breaking' application redirects cookies and responses.

**Comment by berarma** [comment]
I think we should be able to use the deprecations panel and also logging the warnings to a file.

I took a look at the code but I didn't see a way to keep the log and the panel without also getting the warnings in the page output. How do you think it could/should be done?

**Comment by markstory** [comment]
One option would be to have DebugKit's error handler also log deprecation messages.

**Comment by berarma** [comment]
Do you mean creating its own log file for that? It would override the configuration settings. It would the fastest path but more log files isn't exactly ideal.

I could write my own ErrorHandler that doesn't display errors but DebugKit would still be hijacking it. What do you think about making ErrorHandler more configurable so DebugKit could chain the handler in it? Why do errors have to be always rendered in debug mode knowing that they may break rendering and redirects?

**Comment by markstory** [comment]
> Do you mean creating its own log file for that? It would override the configuration settings. It would be the fastest path but more log files isn't exactly ideal.

No, I meant that the debugkit error handler could call `Log::notice()` or `Log::debug()`.

> Why do errors have to be always rendered in debug mode knowing that they may break rendering and redirects?

That is the default application configuration. It doesn't *need* to be that way, but using logs has proven to be foreign to many CakePHP users.
