### ISSUE TITLE
MailPanel in 3.7

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#649]
When trying out the CakePHP 3.next (3.7) branch you get a reflectionexception:

    // cakephp/debug_kit/src/Panel/MailPanel.php
    $property = $reflection->getProperty('_transportConfig');

> Property _transportConfig does not exist

Can we fix this maybe so it doesnt blow up?
Or do people know that 3.7 will require also a new debug_kit (the problem is the require constraint missing here).

debug-kit version: latest dev-master

**Comment by ADmad** [comment]
Please use the `3.next` to test with Cake `3.next` / `3.7`.

**Comment by dereuromark** [comment]
As there is no constraint here, it is a bit messy to have to manually assert these things.
Would be nicer to have this working even for master. But meeh/
