### ISSUE TITLE
SQLite database gets very big

### ISSUE THREAD

**Issue by berarma** [cakephp/debug_kit#652]
Context: My computer is always on and I usually have my development web environment open in one or more tabs. Those tabs are sending Ajax requests periodically.

Consequence: My SQLite database can get to more than 1GB. I notice it when the web app locks and the Apache process is doing a lot of IO and there's a sqlite journal file that is growing at a fast rate. I think this happens because debugkit is deleting a lot of requests at a time and the transaction is big.

I think the problem is that the database cleaning is only initiated when the panel is loaded and that doesn't happen when there're just Ajax requests. Also, it's only started pseudo-randomly once every 100 panel loads. This means sometimes a day can pass and the cleaning doesn't start yet.

I think a solution could be invoking the gc() function every time a request arrives instead.

**Comment by garas** [comment]
I think `time() % 100 !== 0` could be problem.

If your AJAX requests every 10s, it might always happen non xxx0 th second and could never match xxx00th second.

**Comment by berarma** [comment]
Looking at the code it seems it's only triggered at panel visualizations. I could be wrong though. Anyway, you're making a valid point and it can be related to my problem. ```time()``` might be returning xxxxx1 for all my Ajax requests.

**Comment by markstory** [comment]
You can delete the database if it gets too large for your comfort as well.

Instead of gc being pseudo random we could apply a cap to the number of requests that are tracked via a new setting and default that setting to 100.

**Comment by berarma** [comment]
> You can delete the database if it gets too large for your comfort as well.

That's what I do now.

> Instead of gc being pseudo random we could apply a cap to the number of requests that are tracked via a new setting and default that setting to 100.

There's already a setting for the max number of requests but ```time()``` is used so that the queries aren't executed on every request.

**Comment by lorenzo** [comment]
I think I know a way to solve this

**Comment by ADmad** [comment]
@lorenzo Ping

**Comment by mark-hayward** [comment]
Is there a way to fix this currently without deleting the database using a cron?

**Comment by markstory** [comment]
@mark-hayward Not presently. We'd be open to merging a more automated solution if you have something in mind.

**Comment by allanmcarvalho** [comment]
I don't know if you are currently working on this, but I think that my problem is something related with this issue. Some times, when debug is on, the page load is very big, and in few times I get the exception that the database is locked. I delete the sqlite file and this resolve the problem. CakePHP 4.0.6.

**Comment by allanmcarvalho** [comment]
Some times too when debug is on, I get the error FileNotFound on some plugins WWW_ROOT files. I refresh the page, and works. Very very incoherent.

**Comment by dereuromark** [comment]
I had the same issue in 3.x, one time the sqlite DB was 3.5 GB (!) big
I reported it, and it was fixed to https://github.com/cakephp/debug_kit/pull/756

Someone just needs to merge 3.x (or this specific fix) to 4.x.

**Comment by othercorey** [comment]
We just need to add a button that force clears the db so users aren't left wondering why and how.

**Comment by dereuromark** [comment]
The reset button exists in the dashboard as per https://github.com/cakephp/debug_kit/issues/554

as of right now, only the merge to master is missing as I mentioned before. to get the auto clean working as well.

**Comment by othercorey** [comment]
Port to 4.x - https://github.com/cakephp/debug_kit/pull/757
