### ISSUE TITLE
Variables: Lying array type

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#659]
Two things:
Larger view template data passed down makes the view rendering super slow as debug kit always renders out ALL variables incl nesting.
It should, ideally, lazyload those if the panel is opened. Or even per layer if clicked upon. Not all at once even with closed debug kit panels.

Then, the types are also lying :
toArray() seems to eagertransform the entity incl all nesting entities. So the actual class names are gone then. Instead of an (array) I would expect (FooEntity) displayed to know the real type that was there.

Any idea how we could achieve a better debug kit result here?

**Comment by markstory** [comment]
Having variables not recursively dumped is an interesting idea. We would need another controller that could fetch specific keys or paths. Top level keys would be simpler to build and may address some of the initial lag you're seeing.

**Comment by dereuromark** [comment]
By the way:
Since dd() now uses basically the symfony var dumper by default anyway, couldnt we just that one then instead?
```
AssociationCollection {#283 ▼
  #_items: []
  #_tableLocator: TableLocator {#62 ▼
    #_config: []
    #_instances: array:4 [▼
      "Sessions" => Table {#69 ▼
        +"registryAlias": "Sessions"
        +"table": "sessions"
        +"alias": "Sessions"
        +"entityClass": "Cake\ORM\Entity"
        +"associations": []
        +"behaviors": []
        +"defaultConnection": "default"
        +"connectionName": "default"
      }
      "Users" => UsersTable {#231 ▼
        +"registryAlias": "Users"
        +"table": "users"
        +"alias": "Users"
        +"entityClass": "App\Model\Entity\User"
        +"associations": array:1 [▶]
        +"behaviors": array:3 [▼
          0 => "Timestamp"
          1 => "Nullable"
          2 => "Search"
        ]
        +"defaultConnection": "default"
        +"connectionName": "default"
      }
      "Model" => Table {#265 ▶}
      "a_dmad_hybrid_auth_phinxlog" => Table {#282 ▼
        +"registryAlias": "a_dmad_hybrid_auth_phinxlog"
        +"table": "a_dmad_hybrid_auth_phinxlog"
        +"alias": "a_dmad_hybrid_auth_phinxlog"
        +"entityClass": "Cake\ORM\Entity"
        +"associations": []
        +"behaviors": []
        +"defaultConnection": "default"
        +"connectionName": "default"
      }
    ]
    #_fallbacked: array:3 [▼
      "Sessions" => Table {#69 ▶}
      "Model" => Table {#265 ▶}
      "a_dmad_hybrid_auth_phinxlog" => Table {#282 ▶}
    ]
    #_options: array:4 [▼
      "Sessions" => array:1 [▶]
      "Users" => []
      "Model" => []
      "a_dmad_hybrid_auth_phinxlog" => []
    ]
  }
}
```
is nicely formatted, contains the correct class names and via Control+S can even be searched.

**Comment by markstory** [comment]
We could switch to using symfony's Dumper component. dd() only uses that code path if you also have psysh installed. Using the dumper component would also open the door to leveraging the [vardumper server](https://symfony.com/blog/new-in-symfony-4-1-vardumper-server) as well.

**Comment by dereuromark** [comment]
Fun fact: It used to not lie: https://github.com/cakephp/debug_kit/issues/277 ^^
