### ISSUE TITLE
Debugkit does not work with Turbolinks

### ISSUE THREAD

**Issue by D4rkMindz** [cakephp/debug_kit#663]
Turbolinks are an improvement in any webapplication.
We use Turbolinks in a current project and recognized, that debugkit is not compatible with Turbolinks due its usage of DOMContentLoaded.

To prevent this issue, i recommend to just add another eventlistener on "turbolinks:load" to make it compatible. It should also check if the "turbolinks:load" listeners are already added to prevent a doubled execution of the handler.

What is Turbolinks:
> Turbolinks® makes navigating your web application faster. Get the performance benefits of a single-page application without the added complexity of a client-side JavaScript framework. Use HTML to render your views on the server side and link to pages as usual. When you follow a link, Turbolinks automatically fetches the page, swaps in its <body>, and merges its <head>, all without incurring the cost of a full page load.
_[Turbolinks](https://github.com/turbolinks/turbolinks)_

**Comment by D4rkMindz** [comment]
Without this feature, the developer has to reload the page everytime he navigated to another route.
This might be acceptable, but its not "perfect".

**Comment by markstory** [comment]
Closing as a pull request is open now.
