### ISSUE TITLE
Unknown fixture 'DebugKit.Requests'.

### ISSUE THREAD

**Issue by benneic** [cakephp/debug_kit#665]
I can not start app from clone of cakephp/app skeleton repo

Receiving an Unknown fixture 'DebugKit.Requests'. error. Not sure what this means or how to fix it. Google is not my friend today for some reason.
![image](https://user-images.githubusercontent.com/965281/55370271-a2909700-5545-11e9-8219-b66b6e27a5ac.png)

Using cakephp==3.7.1 and debug_kit==3.17.1 installed via composer

**Comment by benneic** [comment]
Ok issue resolved after further debugging. For the future person reading this I was installing debug_kit with 'composer install --classmap-authoritative' which seems to have caused this particular issue. Removing the --classmap-authoritative flag has everything working fine.

**Comment by Tomicapo** [comment]
This happend to me too. What's worse, is it took me ages to realize that my composer.json included the line: `"classmap-authoritative": true`

**Comment by toby-griffiths** [comment]
Thanks for this @benneic .  Save me a load of time this evening.
