### ISSUE TITLE
Notice (8): Undefined index: debugKitLog (DebugKit v3.17.1)

### ISSUE THREAD

**Issue by k-risc** [cakephp/debug_kit#666]
In MailPanel.php the `TransportFactory::class` is inspected (instead of the `Email::class`as in earlier versions). Its configuration is amended, amongst other things the following is done:

`$transport['originalClassName'] = $transport['className'];`

In case of the TransportFactory, this yields ""DebugKit.DebugKit"", not "Mail" as earlier.

This leads to problems in `DebugKitTransport->__construct()`, lines 45 ff.:

```
    public function __construct($config = [], AbstractTransport $originalTransport = null)
    {
        $this->emailLog = $config['debugKitLog'];

        if ($originalTransport !== null) {
            $this->originalTransport = $originalTransport;

            return;
        }

        $className = false;
        if (!empty($config['originalClassName'])) {
            $className = App::className(
                $config['originalClassName'], // this is "DebugKit.DebugKit"
                'Mailer/Transport',
                'Transport'
            );
        }

        // $className is "DebugKit\Mailer\Transport\DebugKitTransport"...
        if ($className) {
            unset($config['originalClassName'], $config['debugKitLog']);
            // ...hence below another instance of class DebugKitTransport is constructed,
            // but this time 'debugKitLog' is removed from the $config,
            // resulting in the notice mentioned in the subject when the first
            // line of code of this function __construct() is executed again above
            $this->originalTransport = new $className($config);
        }
    }
``` 

We do not really need the MailPanel, so we can switch it off, but I was wondering if this is something which we could fix by changing some configuration in our project, or if it is a problem in the new version of DebugKit.

**Comment by markstory** [comment]
How can someone reproduce the problem you're having?

**Comment by k-risc** [comment]
I'll try to provide an example. Starting with an empty project, sending a simple test email, the problem does not occur. Should I find out while testing that it is caused by some specifics of our project setup, I will let you know as well.

**Comment by k-risc** [comment]
Totally our fault. The reason was that the DebugKit plugin was bootstrapped multiple times, leading to the DebugKitMiddleware being inserted in the queue (and later invoked) multiple times as well.
