### ISSUE TITLE
DebugKitController could not be found.

### ISSUE THREAD

**Issue by marcheimendinger** [cakephp/debug_kit#669]
Debug mode was working perfectly… until I turning it off and on.
I now get this error in the bottom left button : `DebugKitController could not be found.`

**Comment by markstory** [comment]
How can someone reproduce the problem you're having?

**Comment by marcheimendinger** [comment]
Ok apparently I solved it by re-cloning my repository and reinstalling all composer dependencies. Strange…

**Comment by cleptric** [comment]
@marcheimendinger Which version of cake are you using?
Could you also check your `Application.php` file and paste the line about `>add(new RoutingMiddleware());` here please?

**Comment by marcheimendinger** [comment]
@cleptric As I said earlier I don't have the problem anymore, so I can't try your manipulations.

**Comment by kovic** [comment]
Clear dir /temp, if u do that, debugkit run correctly!

sorry, i´m not speach english

**Comment by admindotnu** [comment]
Got some problem, comment from @kovic  fixed it.
php cake.php cache clear_all

**Comment by mathurvishal** [comment]
### **Delete all files under** 

> temp/cache/models
>  temp/cache/persistent
> temp/cache/views

**and CTRL+F5 your Browser!**

**Comment by Fluit** [comment]
I have the same problem,
I have followed the steps above, but no good results.

@cleptric as you suggested,.. 

CakePHP v3.7.4
DebugKit v3.18
this is a part of my applications.php
            `//Add routing middleware.
            // Routes collection cache enabled by default, to disable route caching
            // pass null as cacheConfig, example: 'new RoutingMiddleware($this)'
            // you might want to disable this cache in case your routing is extremely simple`

            `->add(new RoutingMiddleware($this, '_cake_routes_'))`

**Comment by Soufiane974** [comment]
I had the same issue, clear the tmp/ directory solved the problem for me

**Comment by Fluit** [comment]
Witch one do you mean?
Tmp dir of cake or the one in the root of the server?



Op wo 26 jun. 2019 09:42 schreef Soufiane974 <notifications@github.com>:

**Comment by Soufiane974** [comment]
I mean the dir cake directory, which contain cache/, bake/ dirs. No the linux root tmp dir.

**Comment by Fluit** [comment]
Just checking to be sure.
and yes, it did the trick.
Thanks a lot.


Op ma 1 jul. 2019 om 06:59 schreef Soufiane974 <notifications@github.com>:

**Comment by tgoeminne** [comment]
It also did the trick to delete the cache, but when I set debug to false, after enable it again. I need to delete the tmp cache folder again every time.

**Comment by kovic** [comment]
The cache is generated with the current information, when you make changes to the project, it contains the previous information

**Comment by tgoeminne** [comment]
The previous version did not have this problem, not sure what you are trying to say?

**Comment by tgoeminne** [comment]
Isn't it supposed to refresh automaticly like in previous versions when debug is set to true?
