### ISSUE TITLE
Use default custom RouteClass of plugin broke the DebugKit

### ISSUE THREAD

**Issue by Aerue** [cakephp/debug_kit#670]
Working with a custom Router into a plugin result in 404 errors with the debug kit plugin.

**config/routes.php**

    Router::defaultRouteClass(\Plugin\Routing\Route\MyCustomRouter::class);

Fix :

**debug_kit/config/routes.php**

    ...
    $routes->setExtensions('json');
    $routes->setRouteClass(\Cake\Routing\Route\DashedRoute::class);
    $routes->connect(
        '/toolbar/clear-cache',
        ['controller' => 'Toolbar', 'action' => 'clearCache']
    );
    ...

**Comment by markstory** [comment]
Any chance you'd be willing to send a pull request for this?

**Comment by ADmad** [comment]
Closing as related PR is open.
