### ISSUE TITLE
4.x - Missing datasource

### ISSUE THREAD

**Issue by davidyell** [cakephp/debug_kit#671]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.0-alpha1
* Platform and Target: PHP 7.3.2 + nginx 1.15.9

[Migrated from the main repo](https://github.com/cakephp/cakephp/issues/13123).

### What you did
I created a new project using composer.
`$ composer create-project cakephp/app:4.x-dev CakePHP4`

### What happened
When I visited my development url, I got an exception for a missing datasource.

```
Missing Datasource Configuration
Cake\Datasource\Exception\MissingDatasourceConfigException

Error: The datasource configuration debug_kit was not found in config/app.php.
```

### What you expected to happen
I was expecting to see the CakePHP welcome page

### How did you sidestep the issue?
I am using a domain name not in the safe list for DebutKit. So I had to force enable DebugKit, which fixed this issue.

**Comment by Kalifax** [comment]
For those looking to get past this issue, you could (**but not recommended except for testing**), disable the DebugKit being loaded alltogether. 

**In src\Application.php**
  ```
public function bootstrap(): void
  {
        $this->addPlugin('DebugKit'); <-- COMMENT OUT THIS

        // Call parent to load bootstrap from files.
        parent::bootstrap();

        if (PHP_SAPI === 'cli') {
            try {
                $this->addPlugin('Bake');
            } catch (MissingPluginException $e) {
                // Do not halt if the plugin is missing
            }
        }

        /*
         * Only try to load DebugKit in development mode
         * Debug Kit should not be installed on a production system
         */
        if (Configure::read('debug')) {
            $this->addPlugin('DebugKit'); <-- COMMENT OUT THIS
        }
    }
```
Again, not recommended. But at least the page shows up now.

**Comment by adduc** [comment]
This error message also appears to happen when the pdo_sqlite extension is not installed.

**Comment by r19u0me1** [comment]
Installing the pdo_sqlite3 extension did resolve the issue for me. This should be noted in the documentation as requirement for the development environment.

**Comment by dereuromark** [comment]
How could this be asserted on install/usage? With a meaningful exception? 
maybe someone can make a PR here?

**Comment by Manojkumarbashnet** [comment]
**In app file:**

.../config/app.php

**in option "Datasources": create new sub option like this:**

'debug_kit' => [
        'className' => 'Cake\Database\Connection',
        'driver' => 'Cake\Database\Driver\Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'port' => Dbport,
        'username' => 'username',
        'password' => password,
        'database' => Dbname,
        'timezone' => 'UTC',
        'flags' => [],
        'cacheMetadata' => true,
        'log' => false,'quoteIdentifiers' => false,
        'url' => env('DATABASE_URL', null),
    ]

> Save file app and refresh your website. Done.

**Comment by nguyen-vu-tung** [comment]
help!  (Error) The datasource configuration debug_kit was not found in config\app.php 
I do not understand why it had such an error. Can anyone help me please show me how.

**Comment by Bob0t** [comment]
I got this working with `apt-get install php7.3-sqlite`
If it can help..

**Comment by jmmedel** [comment]
> This error message also appears to happen when the pdo_sqlite extension is not installed.

its works ty

**Comment by CHOUKI-Mouhssine** [comment]
in src/application.php
add this line 
```
if (Configure::read('debug')) {
			Configure::write('DebugKit.forceEnable', true);
            $this->addPlugin('DebugKit');
        }
```

**Comment by CHOUKI-Mouhssine** [comment]
Or you can set an array of whitelisted TLDs for local development.

in src/application.php
before line `$this->addPlugin('DebugKit');` add this line `Configure::write('DebugKit.safeTld', ['dev', 'local', 'example']);`

Example :

`if (Configure::read('debug')) {
  // Allow e.g. http://foo.bar.dev or http://my-shop.local domains locally
  Configure::write('DebugKit.safeTld', ['dev', 'local', 'example']);
  $this->addPlugin('DebugKit');
}`
