### ISSUE TITLE
DebugKit is not visible in full

### ISSUE THREAD

**Issue by ankitjaiinn** [cakephp/debug_kit#684]
DebugKit is loaded but in a tiny iframe in the botton right of the page. I am not able to make it big

**Comment by markstory** [comment]
Usually you click the square and it expands to be larger. If that is not happening check the contents of the iframe in another window by copying and pasting the URL. There could be an error in DebugKit's controllers.

**Comment by tgr0ss** [comment]
Had this issue all day today, after having it yesterday and it correcting its self..  Anyway  I was able to  **FIX** this by going into the console and clearing the cache by using **bin\cake cache clear_all**  hope that helps.

**Comment by tgoeminne** [comment]
I also have the problem that it shows in a tiny frame. Then clear cache it works. Then set debug to false. Debugkit is gone as expected. Then set debug to true without making any other changes. Debugkit shows up with error in tiny frame. I suppose there is a problem with cache. I didn't have this problem with 3.6, the problem start with cakephp 3.7 and 3.8

**Comment by markstory** [comment]
What is the error message of the error in the debugkit frame?
