### ISSUE TITLE
DebuKit dont works with json response?

### ISSUE THREAD

**Issue by BrunyC** [cakephp/debug_kit#700]
My application return a json response and I have a problem with performance. My requisition take a lot of time to return an response. I already tried use DebugKit but dont works. Im documentation of cakephp say something like: "It primarily provides a toolbar in the rendered HTML, that provides a plethora of information about your application and the current request" - https://book.cakephp.org/3.0/en/development/debugging.html - So debugKit just works with html response? What can I do to see where my app are taking all this time to return the response?

**Comment by garas** [comment]
All CakePHP requests should be logged and listed in History tab.

Toolbar is injected only on HTML pages, but intercepts all AJAX requests and they should appear in History tab without reloading HTML page.

**Comment by BrunyC** [comment]
I understand. So where i find the History tab? The icon is not showing in the bottom right-hand corner of my browser. Im new in developer world, so sorry if i say something stupid.

**Comment by saeideng** [comment]
after json request open another page in browser and switch to json request at `History` tab

**Comment by BrunyC** [comment]
sorry saeideng but I dont understand. Can you explain this better to me? Thank you for help

**Comment by markstory** [comment]
In the bottom right of server rendered html pages you should see a red cakephp icon. Clicking that icon will expand the toolbar which let's you access the history tab that @garas and @saeideng mentioned.

If you don't have the cake icon showing you likely don't have debugkit working properly.

**Comment by BrunyC** [comment]
My debug kit its working well. But my response is a json and not html. So when I open my broswer with the json return the icon not show.

**Comment by garas** [comment]
After loading `json`, open html page with DebugKit.

After opening History Panel, you will see `html` as current request, and then `json` and other previous requests.

https://book.cakephp.org/debugkit/3.x/en/index.html#using-the-history-panel has picture and video about History Panel usage.

**Comment by BrunyC** [comment]
Thanks everyone. This help me a lot!
