### ISSUE TITLE
missing body and html end tags

### ISSUE THREAD

**Issue by Erwane** [cakephp/debug_kit#701]
Hi,
according to this document, the html and body end tags can be ommited :
<https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission>
```
An html element's end tag may be omitted if the html element is not immediately followed by a comment.

A body element's end tag may be omitted if the body element is not immediately followed by a comment.
```
the package `voku/html-min` used by `wyrihaximus/html-compress` for html compression, apply this recommandations.

the method `ToolbarsService::injectScripts` lookup for body end tag and found nothing.

Maybe we can search </body> or </html> and if not present, append the script at the end of html ?

the problem is maybe with ajax  html return

**Comment by markstory** [comment]
What would the problem be with ajax html fragments? Debugkit can ensure the request is not an xhr request before appending its script tags.

**Comment by Erwane** [comment]
of course, i've just noted this problem to check before it appear ;)

**Comment by Erwane** [comment]
In the `DebugKit\Middleware\DebugKitMiddleware::process()` after `saveData()`, it's possible to check request no ?

```php
        $row = $this->service->saveData($request, $response);
        if (!$row || $request->is('ajax')) {
            return $response;
        }
```

**Comment by dereuromark** [comment]
I don't quite see the need to do so.
Whats the problem with keeping it as is?

**Comment by Erwane** [comment]
My bad. Previous MinifyHtml version will compress like that

In view
```html
<ul>
    <li>
          My long text
          <span>is cool</span>
    </li>
</ul>
```
Previous compression remove spaces between `text` and `is`. 
This broked some text, buttons, etc
```html
<ul><li>My long text<span>is cool</span></ul>
```

With current version it's ok.
```html
<ul><li> My long text <span>is cool</span> </ul>
```
Closed.
