### ISSUE TITLE
Wrong code/context display when the deprecations panel is on

### ISSUE THREAD

**Issue by berarma** [cakephp/debug_kit#718]
I'm using DebugKit 3.21.0 on CakePHP 3.8.7.

When the deprecations panel is on and an application error is displayed, the code and context is not from the app code that caused the error but from a function in DebugKit's bootstrap file.

```
Code Context
            if ($previousHandler) {
                return $previousHandler($code, $message, $file, $line, $context);
            }

Cake\Core\BasePlugin::{closure}() - ROOT/vendor/cakephp/debug_kit/config/bootstrap.php, line 42
```

The deprecation panel is on by default. I think this is happening since the deprecation panel was added maybe.

**Comment by markstory** [comment]
Where are you seeing those deprecation warnings. DebugKit should be capturing deprecations and displaying them in the deprecation panel, and from a quick check locally messages in that panel look correct.

How can I reproduce the incorrect results you're seeing?

**Comment by othercorey** [comment]
Is this related to https://github.com/cakephp/cakephp/issues/14068?

**Comment by markstory** [comment]
@othercorey  I don't think so, but it is a similar class of problem caused by the stack traces being wrong on errors.

**Comment by othercorey** [comment]
> @othercorey I don't think so, but it is a similar class of problem caused by the stack traces being wrong on errors.

FYI, I pulled that issue from a screenshot using debug kit, I believe. I have't had time to setup the failure to check.
