### ISSUE TITLE
Make it work properly in https environment

### ISSUE THREAD

**Issue by yKanazawa** [cakephp/debug_kit#736]
In https environment, Chrome Developer Console say it,
```
Mixed Content: The page at 'https://dev.example.com/' was loaded over HTTPS, 
but requested an insecure resource 
'http://dev.example.com/debug-kit/toolbar/caaa0a85-a6e0-407c-adcf-718ffd22ad16'. 
This request has been blocked; the content must be served over HTTPS.
```

The Cause is `Router::url` return only http scheme (not return https).

So, I tryed to fix as following.

vendor/cakephp/debug_kit/src/ToolbarService.php
```php
    public function injectScripts($row, ResponseInterface $response)
    {
...
        $url = Router::url('/', true);
+        if (isset($_SERVER['HTTPS']) || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
+            $url = str_replace('http', 'https', $url);
+        }
```
vendor/cakephp/debug_kit/templates/Requests/view.php
```php
<?php $this->Html->script('DebugKit./js/debug_kit', [
    'block' => true,
    'id' => '__debug_kit_app',
    'data-id' => $toolbar->id,
-    'data-url' => Router::url('/', true),
+    'data-url' => checkHttps(Router::url('/', true)),
    'data-webroot' => $this->request->getAttribute("webroot"),
]) ?>
+<?php
+function checkHttps($url) {
+    if (isset($_SERVER['HTTPS']) || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
+        $url = str_replace('http', 'https', $url);
+    }
+    return $url;
+}
?>
```

This run correctly, but i think this fix way is not so good.
Ideally, `Router :: url` should convert automatically.

**Comment by dereuromark** [comment]
Shouldn't all scripts be included using relative `//` way? https://www.paulirish.com/2010/the-protocol-relative-url/
Then they are always correct.

**Comment by garas** [comment]
It is something wrong with `App.fullBaseUrl` configuration value.
Make sure it is not set manually to `http` url. If it is not set, it should generate links with same scheme as current request. Set it to `https` instead better.

@dereuromark Read note at your link: `//` technique is now an anti-pattern.

**Comment by dereuromark** [comment]
Is it? I would say if this is used for local dev, than it is totally fine :)
I dont use https locally - and don't need any such URLs. And it works live just fine with this. So I don't agree with that note.

**Comment by garas** [comment]
With `//`, browser needs to download same file twice, there is also security issues.

Links to same domain should be `/` links. Domain should be always either on `http` or on `https`, it should avoid mixing protocols

Links to other domains should be `https://` when possible.

**Comment by yKanazawa** [comment]
Thanks!
After set `App.fullBaseUrl`, it worked correctly.

I apologize to you for a fuss over.

**Comment by waspinator** [comment]
in `app.php` set 

`'App' => ['fullBaseUrl' => 'https://example.com']` 

and in `bootstrap.php` add 

`Configure::write('DebugKit.forceEnable', true);` 

before loading `Plugin::load('DebugKit', ['bootstrap' => true]);`
