### ISSUE TITLE
version 4.x doesn't use the ignoreAuthorization configuration

### ISSUE THREAD

**Issue by chemanfit** [cakephp/debug_kit#740]
I see that the ignoreAuthorization configuration was implemented in the 3.x version but it doesn't appear to be in the 4.x release. Can it be implemented there as well?

**Comment by markstory** [comment]
It is on master, but hasn't been included in a release yet.

**Comment by markstory** [comment]
I just released 4.0.6

**Comment by chemanfit** [comment]
excellent. Thank you! I tested on my new app I am working on and it seems to be working.
