### ISSUE TITLE
DebugKit not showing on fresh CakePHP4 installation

### ISSUE THREAD

**Issue by linkinted** [cakephp/debug_kit#741]
After a fresh CakePHP 4.0.4 I activated DebugKit by adding this code to `Application.php`

        if (Configure::read('debug')) {
            Configure::write('DebugKit.safeTld', ['dev', 'local', 'ttf4.test.domain.nl','domain.nl']);
            Configure::write('DebugKit.forceEnable', true);
            $this->addPlugin('DebugKit');
        }

I've set `'debug'=>true,` in `app.local.php` as well.

On the default CakePHP it says that DebugKit is loaded, however the Toolbar isn't showing up.

What am I doing wrong here.

**Comment by markstory** [comment]
That should work. If that code is in Application::bootstrap(). In your html do you see the script tag that debug kit injects to show the toolbar?

**Comment by linkinted** [comment]
Yes, the script tag is showing.
When I go to the source of the script, it shows a 404.

**Comment by ADmad** [comment]
Sounds like URL rewriting issue.

**Comment by linkinted** [comment]
Ok, but its a fresh install, how could that be?

**Comment by ADmad** [comment]
URL rewriting depends on your webserver, there's nothing CakePHP can do about. Check the [manual](https://book.cakephp.org/4/en/installation.html#url-rewriting) on how to configure URL rewriting for your webserver.

**Comment by linkinted** [comment]
How come a 3.8 CakePHP installation with the exact same .htaccess does work. And the 4.0.4 version doesn't?

**Comment by linkinted** [comment]
FYI, the problem was that my webserver was setup as nginx server instead of apache. After changing it, the .htaccess worked and the problem was solved.
