### ISSUE TITLE
Remove cakephp/plugin-installer dependency

### ISSUE THREAD

**Issue by othercorey** [cakephp/debug_kit#747]
Can we remove this dependency? Does any code in debug_kit need it?

**Comment by ADmad** [comment]
It doesn't, unless debugkit is doing something special. 

The plugin installer readme states:
> Your plugins themselves do not need to require cakephp/plugin-installer

**Comment by dereuromark** [comment]
The app has it
https://github.com/cakephp/app/blob/master/composer.json#L11

Technically, it is a bit cleaner to have the dependency on the plugins, thus auto requiring it from the app perspective.
But I can see that this is a bit annoying to do for all plugins.
So app only seems fine.
