### ISSUE TITLE
mysql unit test fails on LIMIT & IN/ALL/ANY/SOME subquery

### ISSUE THREAD

**Issue by othercorey** [cakephp/debug_kit#753]
Example failure:

> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

> /home/travis/build/cakephp/debug_kit/src/Model/Table/RequestsTable.php:101
> /home/travis/build/cakephp/debug_kit/src/ToolbarService.php:233
> /home/travis/build/cakephp/debug_kit/tests/TestCase/ToolbarServiceTest.php:187

**Comment by garas** [comment]
Fixed in https://github.com/cakephp/debug_kit/pull/731

Only necessary to merge  `3.x`  merge to `master`.

**Comment by ADmad** [comment]
> Only necessary to merge 3.x merge to master.

Done
