### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by beboobailey** [cakephp/debug_kit#755]
Receiving a warning in Firefox similar to issue #177 but on debug kit 3.22.3.

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

The previous issue was closed stating that the warning did not exist in 3.x. This appears to be different code causing this. It is throwing the warning on the return statement of this function:

```javascript
var proxyAjaxOpen = function() {
    var proxied = window.XMLHttpRequest.prototype.open;
    window.XMLHttpRequest.prototype.open = function() {
      this._arguments = arguments;
      return proxied.apply(this, [].slice.call(arguments));
    };
};
```

While this is also not a fatal error, just wanted to bring this to someone's attention if they weren't already aware of it.

**Comment by markstory** [comment]
I'm not sure what about this is making a synchronous call XMLHttpRequest.

**Comment by garas** [comment]
Your app or library is using a synchronous XMLHttpRequest call.

DebugKit is just proxying XMLHttpRequest calls and is displayed as bad caller, but you should check full callstack for true caller.

You can test it with short script.

```js
var func = function () {
    var oReq = new XMLHttpRequest();
    // remove 3rd argument or set it to true to use async and avoid warning
    oReq.open("GET", "/example", false);
    oReq.send();
};
setTimeout(func, 1000); // allow DebugKit to replace XMLHttpRequest.open() with its proxy first
```

DebugKit does nothing wrong, you should update your scripts or dependencies.
