### ISSUE TITLE
Drop method DebugLog::totalRows() and remove "Total Rows" display from SQL Panel

### ISSUE THREAD

**Issue by ADmad** [cakephp/debug_kit#762]
`DebugLog::totalRows()` returns the total of `LoggedQuery::$numRows` of all logged queries. The latter would be count of fetched rows in case of `SELECT` queries and affected rows in case of `INSERT`,`UPDATE`/`DELETE` queries.

I can't see how the total of fetched/affect rows of multiple queries be useful to anyone.

**Comment by markstory** [comment]
Removing the total rows is fine by me. I think we added it because it was simple to add.
