### ISSUE TITLE
boolean type formatted as 0/1 in the query log and sql panel instead of false/true

### ISSUE THREAD

**Issue by swiffer** [cakephp/debug_kit#765]

**Comment by garas** [comment]
MySQL, Sqlite, SQL Server doesn't have boolean type, they are just 0/1. Only PostgreSQL has boolean type.


Query log doesn't know database dialect and [always use 0/1](https://github.com/cakephp/cakephp/blob/6ea905845759f4e54df92f45af5f839986fd402e/src/Database/Log/LoggedQuery.php#L77).

**Comment by markstory** [comment]
I don't think there is much we can do here. The logs in DebugKit are not authoritative and aim to represent the query that was run as best we can. Having booleans presented as 0/1 will be right most of the time.

**Comment by othercorey** [comment]
Closing as this is valid for all dbs.
