### ISSUE TITLE
Notice: Undefined index: debugKitLog

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#773]
Latest 3.x version of DebugKit throws

> Notice (8): Undefined index: debugKitLog [ROOT/vendor/cakephp/debug_kit/src/Mailer/Transport/DebugKitTransport.php, line 37]

Maybe we can avoid this notice?

```
Cake\Core\BasePlugin::{closure}() - ROOT/vendor/cakephp/debug_kit/config/bootstrap.php, line 43
DebugKit\Mailer\Transport\DebugKitTransport::__construct() - ROOT/vendor/cakephp/debug_kit/src/Mailer/Transport/DebugKitTransport.php, line 37
DebugKit\Mailer\Transport\DebugKitTransport::__construct() - ROOT/vendor/cakephp/debug_kit/src/Mailer/Transport/DebugKitTransport.php, line 56
Cake\Mailer\TransportRegistry::_create() - CORE/src/Mailer/TransportRegistry.php, line 90
```

**Comment by markstory** [comment]
Why is the constructor called twice in a row? Is DebugKit wrapping itself somehow?

**Comment by dereuromark** [comment]
I had this case when upgrading an app from 3.x to 4.x
And it blocked moving forward with other things.
So it would be good if we find a solution to not through those warnings - as this complicates the upgrade path.
