### ISSUE TITLE
Debug variables: class names missing

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#777]
The new debug output now shows the specific scalar types (int vs string) etc
But it seems to 
a) lost all class names on the objects
b) eager-replaces all objects with array directly

See
![xxx](https://user-images.githubusercontent.com/39854/91038524-323b5780-e60b-11ea-9325-b49eeeeac20f.png)
One doesn't know what object "created" is, nor what "contactAd" is.

When using dd() - which is hijacked by Symfony debugger - on `_authUser` array:
![xyy](https://user-images.githubusercontent.com/39854/91038547-3cf5ec80-e60b-11ea-8930-4a51b79c1db8.png)
Note the "created" field.

What's interesting, though: If you use debug(); die()  - which is again Cake internal debug output:
![xzz](https://user-images.githubusercontent.com/39854/91038734-8fcfa400-e60b-11ea-990b-c09f939213bb.png)
Here the object references are there.

So this must be a debug kit specific issue.

**Comment by markstory** [comment]
Because the contents of the variables panel are stored in the SQLite database, DebugKit array_walk's all the variables and uses `__debugInfo()` on them as a way to remove unserializable objects from the variable tree. We might be able to resolve this by exposing the new debug node tree as a public interface but I'm reluctant to expose a lower level object graph like that just for debugkit.

**Comment by dereuromark** [comment]
Given that we lose 2 important info here (class name and if object or array), this seems too important to not have IMO if we want people to use this debug var window.

**Comment by markstory** [comment]
I agree that having the class information is important. I haven't done any testing to see if the debug node tree is safe for serialization. If it is we might be able to handle serialization problems in debug kit more simply and retain more information as well. Switching over to the debug node tree would require another minor version of CakePHP as well. We would need new methods on Debugger to get the tree out.

**Comment by dereuromark** [comment]
Are we going to include the fix in the 4.2 version coming out?

**Comment by markstory** [comment]
We could add the new debugger method in 4.2, and start using it in debugkit.

**Comment by dereuromark** [comment]
The current output seems to also have some issues with nested props, e.g. for modelless forms:

    '_validators' => 'Unserializable Error: /.../vendor/cakephp/debug_kit/src/Panel/VariablesPanel.php in 176, line {3}',

**Comment by markstory** [comment]
@dereuromark I'm pretty confident that switching to the debug node tree after 4.2 comes out will make this all better.
