### ISSUE TITLE
SQLite File Lock after installation with chmod 777

### ISSUE THREAD

**Issue by maidzen** [cakephp/debug_kit#785]
![error](https://user-images.githubusercontent.com/17901424/96467621-673ee180-122b-11eb-93a7-bd5a096ae7b9.PNG)

I installed CakePHP4 with debugKit today but im getting following errors when it tries to create tables.

```
Warning (512): Fixture creation for "requests" failed "SQLSTATE[HY000]: General error: 5 database is locked" [CORE/src/TestSuite/Fixture/TestFixture.php, line 295]
Warning (512): Fixture creation for "panels" failed "SQLSTATE[HY000]: General error: 5 database is locked" [CORE/src/TestSuite/Fixture/TestFixture.php, line 295]
```
the file debug_kit.sqlite gets created but is empty. 
the file debug_kit.sqlite-journal gets created and filled but it runs into the error

Running on Apache 2.4 with PHP7.4-FPM

**Comment by markstory** [comment]
I don't know how to reproduce this problem but it sounds like you might have a concurrency or permissions related problem. If it persists you can configure DebugKit to use MySQL or Postgres instead of SQLite.

**Comment by maidzen** [comment]
resolved, there is a Networkshare on our dev VMs to access data in /var/www directly, the share blocks the file.
