### ISSUE TITLE
DebugKit "did not apply any authorization checks" error despite 'ignoreAuthorization' => true

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/debug_kit#788]
CakePHP version: 4.1.4
Authorization plugin version: 2.0.4
DebugKit version: 4.3.4

I've set
```
'DebugKit' => [
    'ignoreAuthorization' => true,
],
```
in my app configuration data, and
```
        if (Configure::read('debug')) {
            $this->addPlugin('DebugKit', [
                'ignoreAuthorization' => true,
            ]);
            Configure::write('DebugKit.ignoreAuthorization', true);
        }
```
in `Application.php`, but the Authorization plugin is still giving me a "did not apply any authorization checks" error for the DebugKit:
```
2020-10-26 16:14:29 Error: [Authorization\Exception\AuthorizationRequiredException] The request to `/debug-kit/toolbar/53ecbb00-c350-440a-a144-3edaf19232c2` did not apply any authorization checks. in C:\...\app\vendor\cakephp\authorization\src\Middleware\AuthorizationMiddleware.php on line 132
Exception Attributes: array (
  'url' => '/debug-kit/toolbar/53ecbb00-c350-440a-a144-3edaf19232c2',
)
```
Is this a bug, or is there something that I'm not doing right? I'm setting the configuration value in (I think) all of the possible ways I could set it.

Digging into an explanation, I see that [this issue](https://github.com/cakephp/authorization/issues/80) was fixed by [this DebugKit pull request](https://github.com/cakephp/debug_kit/pull/734), which added [code in DebugKitController.php](https://github.com/cakephp/debug_kit/blob/master/src/Controller/DebugKitController.php#L45) that was supposed to bypass this authorization check, but a breakpoint in that code shows that it's not actually being executed when I load a page. That controller is being skipped over entirely. Here's a stack trace:
```
Stack Trace:
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php:156
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\cakephp\src\Http\Middleware\BodyParserMiddleware.php:159
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php:166
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php:68
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:121
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php:60
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\...\app\vendor\cakephp\cakephp\src\Http\Runner.php:58
- C:\...\app\vendor\cakephp\cakephp\src\Http\Server.php:90
- C:\...\app\webroot\index.php:40
```

Does anyone have any insight into whether this looks like a bug or if I've somehow misconfigured something?

**Comment by markstory** [comment]
Is the AuthorizationService the right type? Is `DebugKitController::beforeFilter()` running at all? Are you using the `RequestAuthorizationMiddleware` that middleware is incompatible with the existing code as mentioned in #738

**Comment by PhantomWatson** [comment]
> Is the AuthorizationService the right type?

It appears to be. It's `Authorization\AuthorizationService`. In `Application.php`:
```
use App\Policy\RequestPolicy;
use Authorization\AuthorizationService;
use Authorization\AuthorizationServiceInterface;
use Psr\Http\Message\ServerRequestInterface;
...
    /**
     * Returns the authorization service
     *
     * @param \Psr\Http\Message\ServerRequestInterface $request Server request
     * @return \Authorization\AuthorizationServiceInterface
     */
    public function getAuthorizationService(ServerRequestInterface $request): AuthorizationServiceInterface
    {
        $mapResolver = new MapResolver();
        $mapResolver->map(ServerRequest::class, RequestPolicy::class);

        return new AuthorizationService($mapResolver);
    }
```

> Is DebugKitController::beforeFilter() running at all?

Nope.

> Are you using the RequestAuthorizationMiddleware that middleware is incompatible with the existing code as mentioned in #738

 - Yeah, I'm using a `RequestPolicy` and `RequestAuthorizationMiddleware` (being automatically loaded by the Users plugin). This appears to be the problem.
 - If I understand #738 correctly (which I completely missed when I was investigating this and seem to have accidentally recreated), I need to pull back and avoid using request authorization at all if I'm also using DebugKit.
 - Switching from a request policy to an entity-based policy and the `OrmResolver` solves this problem.
