### ISSUE TITLE
4.3.6 excludes /tests from archive so composer install --prefer-dist will have broken debug_kit (Fixture missing)

### ISSUE THREAD

**Issue by swiffer** [cakephp/debug_kit#793]
Fatal error: Uncaught Error: Class name must be a valid object or a string in /var/www/html/tiefblau/vendor/cakephp/debug_kit/src/Model/Table/LazyTableTrait.php on line 64

**Comment by othercorey** [comment]
Thanks for finding and reporting this. Should be fixed in 4.3.7 release.
