### ISSUE TITLE
Class name must be a valid object or a string error in LazyTableTrait

### ISSUE THREAD

**Issue by bancer** [cakephp/debug_kit#797]
After running `composer dump-autoload -a`: 

![Screenshot from 2020-11-19 22-41-32](https://user-images.githubusercontent.com/3830106/99728117-35829a00-2ab9-11eb-856c-b9fc40ca748d.png)

`$name` has value `'DebugKit.Requests'`, `$class` has value `null`.

DebugKit version 4.3.7.

**Comment by markstory** [comment]
Does the generated autoloader not include the paths to debugkit fixtures?
