### ISSUE TITLE
Cache::getConfig() returns wrong values with DebugKit enabled

### ISSUE THREAD

**Issue by mixable** [cakephp/debug_kit#801]
**_Environment:_**

- CakePHP 4.1.6
- DebugKit 4.3.8

**_Issue:_**

When calling `\Cake\Cache\Cache::getConfig('default')` the expected output [as documented in the Api](https://api.cakephp.org/4.1/trait-Cake.Core.StaticConfigTrait.html#getConfig) is:
```
array:3 [▼
  "className" => "Cake\Cache\Engine\FileEngine"
  "path" => "/.../app/tmp/cache/"
  "url" => null
]
```

Having DebugKit enabled, the output is different:
```
array:1 [▼
  "className" => DebugKit\Cache\Engine\DebugEngine {#106 ▼
    #_config: array:3 [▼
      "className" => "Cake\Cache\Engine\FileEngine"
      "path" => "/.../app/tmp/cache/"
      "url" => null
    ]
```

With this behavior, it's not possible to access the cache configuration when DebugKit is enabled.

I think this issue is related to an issue that popped up some time ago #359.

**Comment by markstory** [comment]
Would you need access to the path, url and other configuration options? Or is the problem that `className` is no longer a string?

**Comment by mixable** [comment]
I need to access the path. I use this value in a method that optimizes the cache files in the cache folders.

I stumbled apon this issue because (all locale) tests for this method failed when DebugKit is enabled. This will not be the case for the production server. However, this does not allow a full test of the logic behind this method.

Or are there other ways to access the cache config? I also tried to use `Configure`, but by default `Configure` "comsumes" the Cache settings and so they are not available anymore.

What is the idea behind overriding the output of `\Cake\Cache\Cache::getConfig('default')`?

**Comment by ADmad** [comment]
@mixable The cache engine's use `InstanceConfigTrait`, so for case where `className` is an engine instance you should be able to use `\Cake\Cache\Cache::getConfig('default')['className']->getConfig()` to get the original config.

Another options is to change the call `Cache::setConfig(Configure::consume('Cache'));` in `bootstrap.php` to `Cache::setConfig(Configure::getConfig('Cache'));` so the the config isn't "consumed" and can be fetched again later.

**Comment by ndm2** [comment]
How about accessing the engine directly, like `\Cake\Cache\Cache::pool('default')->getConfig()`?

**Comment by garas** [comment]
> I need to access the path. I use this value in a method that optimizes the cache files in the cache folders.

You could try to use custom cache engine and do the optimization on write.

**Comment by mixable** [comment]
Thank you all for the comments. I think accessing the engine directly as @ndm2 pointed out is the perfect solution for this. It does not change the behavior nor does it require additional code to detect if DebugKit is enabled or disabled.

But I'm still wondering, if the different output of `getConfig()` might be a problem for other usages? I don't have an example, I'm just thinking about this as I also had problems with this behavior...

**Comment by markstory** [comment]
> But I'm still wondering, if the different output of getConfig() might be a problem for other usages? I don't have an example, I'm just thinking about this as I also had problems with this behavior...

It likely could be. I think we can overload the `getConfig()` and `setConfig()` methods in the proxy so that it quacks the right way.
