### ISSUE TITLE
Argument 2 passed to Cake\I18n\Package::addMessage() must be of the type string, array given

### ISSUE THREAD

**Issue by LordSimal** [cakephp/debug_kit#811]
![image](https://user-images.githubusercontent.com/9105243/102802379-d618f200-43b6-11eb-9f7c-bbd50764e43f.png)

I get this error after I upgraded my CakePHP 4 app to 4.2 and my DebugKit to 4.4.1

The error is not "shown" directly in the debug_kit or in the frontend but it is present when I got to the URL the debug_kit tries to open when clicking on the "Timer" tab.

![image](https://user-images.githubusercontent.com/9105243/102802484-03fe3680-43b7-11eb-96e9-9d59db28bbee.png)

I got the following URL from the network tab of my browser.

My URL was: http://myapp/debug-kit/panels/view/19671143-3e02-416d-93e6-a6607fce1130

The Problem - see the xdebug state here:
![image](https://user-images.githubusercontent.com/9105243/102802253-ab2e9e00-43b6-11eb-8f68-2c4bba2d972b.png)

**Comment by dereuromark** [comment]
You need to clear your DB, in that case remove/delete your SQlite file.
The 4.2 debug kit DB doesnt work with 4.1 one.
So there is no upgrade path for the debug data here.

**Comment by LordSimal** [comment]
This problem still persist after deleting the `tmp/debug_kit.sqlite` file and performing a `bin/cake cache clear_all`

**Comment by LordSimal** [comment]
I only get this behaviour on the following tabs

- Packages
- Timer
- Variables

All other tabs work normally

**Comment by dereuromark** [comment]
I cannot reproduce that, timer works fine in my app.

**Comment by LordSimal** [comment]
i try reinstalling all composer modules

**Comment by LordSimal** [comment]
No luck with re-downloading and installing all composer modules.

I just tried to Xdebug that.
Basically it starts in `vendor/cakephp/debug_kit/templates/element/timer_panel.php` Line 59 where it tries to output
`__d('debug_kit', 'Timeline')`

Since there is no "direct" translation for that String in `$this->package` it tries the fallback and accesses the translation via `$this->fallback`

![image](https://user-images.githubusercontent.com/9105243/102805317-56415680-43bb-11eb-894c-ce2f89ba94a7.png)


But this translation (and basically any translation string in there) is surrounded in an array like that
![image](https://user-images.githubusercontent.com/9105243/102805194-22fec780-43bb-11eb-8426-4273a8bccfed.png)

**Comment by LordSimal** [comment]
FYI: I am on PHP 7.4.13 if that helps

**Comment by dereuromark** [comment]
https://github.com/cakephp/cakephp/issues/15231

**Comment by LordSimal** [comment]
This PR fixed my problem
https://github.com/cakephp/cakephp/pull/15233
