### ISSUE TITLE
XHR requests in the history panels are not updating

### ISSUE THREAD

**Issue by boyerdalton** [cakephp/debug_kit#813]
Php version: 7.2.4

Cakephp version:3.9.5

Debugkit version:3.22.4

Development setup: Done through vagrant with a development url in this format _site.subdomain.com_

Install steps: The ones provided on [The cakephp cookbook](https://book.cakephp.org/debugkit/3/en/index.html) with addition of 
```
if (Configure::read('debug')) {
    Configure::write('DebugKit', ['forceEnable' => true]);
    Plugin::load('DebugKit', ['bootstrap' => true]);

}

```
It appears that I am having an issue with getting the debugkit to display XHR requests in the History panel. They are being logged into MYSQL database and can be accessed once I refresh my browser, but do not update when they happen as shown on this [article](https://bakery.cakephp.org/2015/04/26/queries_log_for_your_ajax_requests.html). It also appears that not all XHR requests are even being shown in the History panel when I Refresh. The requests that I make is just through simple Jquery Ajax, and I even tried to make a request in the manner that was shown on that video in that link. My question is do I have to configure something else to get this to show, or should it just show automaticlly. I am attaching a screenshot to show you what happens when I make an ajax call in the console (*note I have covered my base url in the screenshot and replaced it with a url that is in the same format and manner as mine). 

![image](https://user-images.githubusercontent.com/41798899/103838203-16809d00-5052-11eb-8ee2-543201ab9676.png)

**Comment by markstory** [comment]
If your requests end up going through `fetch()` DebugKit will not be able to capture them. The live logging relies on patching `XMLHttpRequest` and it is possible for libraries to obtain a reference to that object before DebugKit can apply its patches.

**Comment by boyerdalton** [comment]
> If your requests end up going through `fetch()` DebugKit will not be able to capture them. The live logging relies on patching `XMLHttpRequest` and it is possible for libraries to obtain a reference to that object before DebugKit can apply its patches.

@markstory it is an `XMLHttpRequest`, as it is just a jquery ajax call. I only use ajax in this codebase, I don't use `fetch()` anywhere in it.

**Comment by markstory** [comment]
https://github.com/cakephp/debug_kit/blob/master/webroot/js/toolbar.js#L60-L117 Is the code that adds the proxy. I'm not able to reproduce your problem so you'll need to help find the problem :smile:

**Comment by boyerdalton** [comment]
Thanks @markstory so I did some testing around and it seems that `this.getResponseHeader('X-DEBUGKIT-ID')` on line 62 of toolbar.js is returning as null.

**Comment by markstory** [comment]
Are there warnings in the browser console about forbidden access to headers? That header should be set by the Middleware in DebugKit when it saves a request.

**Comment by boyerdalton** [comment]
@markstory there are no warnings in the console. When I console logged `getAllResponseHeaders ()`, and  `X-DEBUGKIT-ID` Is not even present in the list of headers. I consulted another dev about this at my job, as he uses debugkit on 2 other products, and he didn’t even know it could log XHR request because his requests are not updating either. I use Firefox and he uses chrome, I don’t know if that helps or not.

**Comment by markstory** [comment]
Could there be a webserver or proxy that is stripping the response header? I tried tonight with the `bin/cake server` webserver and was able to capture requests in the history panel.
![screenshot - 2021-01-08 23:01:42](https://user-images.githubusercontent.com/24086/104082976-9c464900-5208-11eb-9b41-edd036ad5343.png)

**Comment by boyerdalton** [comment]
@markstory Yeah I'm not sure whats going on here, I `debug( $response->withBody($body))` in ToolbarServices in injectScripts and it does have the X-DEBUGKIT-ID in there. The only things I can think of is maybe if doesn't like that my dev enviroment ends in `.com` even though I have `forceEnabled` as true. I'm not the best at websevers but what I do know about this, is that is nginx, and when I look at my access log I see `debug-kit/toolbar/IDWOULDBEHERE` being registered there. It just never makes it into the `return function() {` in `logAjaxRequest`.

**Comment by LordSimal** [comment]
@boyerdalton Its been quite some time but I just wanted to ask if this issue can still be reproduced with the latest version of the DebugKit.
