### ISSUE TITLE
Big amount of errors when running PHP8

### ISSUE THREAD

**Issue by FinlayDaG33k** [cakephp/debug_kit#818]
Hii there,

We have updated to PHP8 a little while ago, however, ever since, the debug kit shows a big amount of errors (this repeats about 300 times)
![image](https://user-images.githubusercontent.com/13424273/105838293-34497e00-5fd0-11eb-9d55-93b386da0a75.png)

I suppose the debug kit isn't made to be compatible with PHP8 yet?

**Comment by dereuromark** [comment]
You need to also include the info what version of debug kit and core you are using.

**Comment by FinlayDaG33k** [comment]
Whoops, forgot to add those.
core: `3.9.5`
dk: `3.22.4`

**Comment by dereuromark** [comment]
See also https://github.com/cakephp/cakephp/wiki#version-map

**Comment by markstory** [comment]
All of 3.x is not going to support PHP8. There are multiple breaking changes in the dependencies for 3.x that would also require breaking changes in cake.

**Comment by FinlayDaG33k** [comment]
@markstory I see... will CakePHP 4.x support it?

**Comment by ADmad** [comment]
CakePHP 4 already supports PHP 8.
