### ISSUE TITLE
Connection datasource and SqlLogPanel conflict

### ISSUE THREAD

**Issue by Erwane** [cakephp/debug_kit#832]
Hi,

Cakephp version : cakephp 4.2

I'm creating an API datasource for my project.
My connection implements `Cake\Datasource\ConnectionInterface`.

DebugKit add it's own `DebugKit\Database\Log\DebugLog` but this logger is really specific to `Database` due to this method `protected function isSchemaQuery(LoggedQuery $query): bool`

I need to log my request with headers, uri, data and response, in my own DebugKit panel but DebugLog throw an error before.

**Comment by ADmad** [comment]
Why is your connection class implementing `ConnectionInterface`? It has methods like `transactional()`,  `disableConstraints()` which wouldn't make sense for an API datasource.

Debugkit's sql logger will stay out of the way if a connection class doesn't implement `ConnectionInterface`.

**Comment by Erwane** [comment]
`Datasources` are not *all datasources* ?

**Comment by ADmad** [comment]
> Datasources are not all datasources ?

Yes they are, but with the methods `ConnectionInterface` has it's is only suitable for RDBMS datasouces. Maybe in the next version we should trim down it's methods and move it under `Database` namespace and add a more generic interface under `Datasource`.

For now you can checkout the `muffin/webservice` plugin for example of a connection class which doesn't implement `ConnectionInterface`.

**Comment by Erwane** [comment]
Ok thanks.
I did for muffin/webservice. It's not working in my specific case but it's a good source of inspiration.
Thanks.
