### ISSUE TITLE
Show history and related panels in dashboard

### ISSUE THREAD

**Issue by raul338** [cakephp/debug_kit#834]
Related to "Last requests to inspect in detail maybe" in #554

I'm using a cakephp mainly as a rest-only backend, so i don't see much the toolbar. I could really use the panels to inspect each request made by the front-end (a separate non-php project) or mobile apps.

A quick way to enable this would be just show the toolbar in the dashboard, and a button in the requests panel to reload the requests (or refresh the page). If you are ok with this I can try open a PR.

**Comment by markstory** [comment]
> A quick way to enable this would be just show the toolbar in the dashboard, and a button in the requests panel to reload the requests (or refresh the page).

I think a button to fetch the new history would be better than a page load as reloading the page could disrupt the current page state. DebugKit usually captures network requests that are made as it patches `XMLHttpRequest`. Are you using `fetch()` instead?

> If` you are ok with this I can try open a PR.

That would be great!

**Comment by raul338** [comment]
> DebugKit usually captures network requests that are made as it patches XMLHttpRequest. Are you using fetch() instead?

In my case the request are external, while cakephp listen to localhost:8765, the frontend (webpack dev server) listen another ports and act as a proxy to the cake server. So the dashboard (or any view) does never see a XHR request.
The same is with mobile, the requests are made from another devices entirely.
