### ISSUE TITLE
typo in font-familiy -> font-family

### ISSUE THREAD

**Issue by braguzz** [cakephp/debug_kit#842]
https://github.com/cakephp/debug_kit/blob/10d7d9ba36945844211f1d8763e59618917e1784/templates/MailPreview/index.php#L38

**Comment by dereuromark** [comment]
Can you make a PR here to fix it?

**Comment by braguzz** [comment]
<pre style="background-color:#f8f8f8;font-family:Monaco,sans-serif;overflow:scroll;margin:10px 0;line-height:25px;">

**Comment by dereuromark** [comment]
PR => Pull request
