### ISSUE TITLE
Can we show the database name with the connection name in SQL Log

### ISSUE THREAD

**Issue by nshiddqui** [cakephp/debug_kit#849]
in the SQL log, currently, we are showing connection name, number of rows and took the time(ms),

it would be better if we will show the database name as well.

and it should work on a fly database that is created on the controller.

**Comment by markstory** [comment]
In most applications the database name would be redundant as the connection generally maps to only one database.

We could replace the connection name with the database name but having both seems noisy.

**Comment by LordSimal** [comment]
I am also against showing redundant information.

**Comment by nshiddqui** [comment]
replace the connection name with database like CakePHP 1.3 debug log
