### ISSUE TITLE
RFC: Group plugin-routes into tab-sections in routes panel

### ISSUE THREAD

**Issue by LordSimal** [cakephp/debug_kit#850]
I just thought of a UX improvement for the routes tab: In my case I have 100 loaded routes.

![image](https://user-images.githubusercontent.com/9105243/145676241-03741516-2cfa-4d47-a229-6d800e3b6df8.png)

These are not sorted or grouped in any particular way (inverse route key order as I have seen in the code) but still a bit "messy" I would say.

My improvement would be to introduce tabs at the top similar to the already present "Toggle debugkit internal routes" button.
The amount of tabs is depending on the available plugins / loaded routes in those plugins.

![image](https://user-images.githubusercontent.com/9105243/145676506-550834c5-3579-47a8-b50c-720fc7951573.png)

This is a very rude, quick mockup I just made but I guess you get the point.

Clicking on one of these buttons will show only the routes loaded for that particular plugin. 

What are your opinions about that?

**Comment by ADmad** [comment]
> These are not sorted...

They are stored in the order in which they will be checked when parsing the request URL :slightly_smiling_face:.

Having tabs/buttons to filter the routes by plugins sounds fine but it could cause display issue if someone has a lot of plugins with routes.

**Comment by LordSimal** [comment]
I would build it so that at the center of the viewport it would wrap around to the next line.
![image](https://user-images.githubusercontent.com/9105243/145677005-77d41d0f-6b74-4f86-b9a1-d24799e18184.png)

**Comment by LordSimal** [comment]
also I wouldn't actually mess with the default table ordering.

I rather add a class like `plugin-<parsed-plugin-name` to each row and hide/show those entries when clicking on the button at the top (with of course an active/inactive state)

**Comment by dereuromark** [comment]
If it is too many it could also be a dropdown :)
I guess there are different ways to solve this.

**Comment by LordSimal** [comment]
I just realised that the current "Toggle debugkit internal routes" button actually does what I want but just for the debugkit routes.

Therefore I will remove that button, center the whole buttons array and include the DebugKit plugin into those.
