### ISSUE TITLE
[feature request] Change iframe size when debugKit iframe shows an error

### ISSUE THREAD

**Issue by hacheraw** [cakephp/debug_kit#857]
![image](https://user-images.githubusercontent.com/10481749/158342336-2f8c9e23-f955-4a8d-af76-94de10911449.png)

In some cases, when there's an application error (usually error 5xx or routes one) the DebugKit iframe looks like the above picture.

Would it be possible to add a css class to the iframe if an error template is shown inside? Or just change it's size.

**Wanted behavior:**
iFrame is 40x40px by default. When an error is thrown, iFrame should be, maybe, 40% by 40% so we can see the error.

![image](https://user-images.githubusercontent.com/10481749/158342237-15fef1cd-dfad-43a4-bc37-b2621b3d26ea.png)

**Comment by LordSimal** [comment]
I'll try to implement that now.

**Comment by LordSimal** [comment]
The mentioned PR above only catches errors which happen when a panel like `Requests` or `Routes` is loaded.

But can you explain a scenario where the initial DebugKit Toolbar is not loading / throwing an error? This would need be handled seperately I would say.

**Comment by hacheraw** [comment]
Sorry, I don't know if I'm understanding your question but I can't remember how to reproduce it in different scenarios.

For instance, that screenshot was from a day I was trying to implement a custom Middleware. Adding a bug on a custom Middleware could be a way to reproduce this.

It's been a couple of months since I don't touch CakePHP, so I'm a bit rusty...

**Comment by hacheraw** [comment]
Now looking at your gif, yeah, I understand what you mean.

I'll try to reproduce it before Tuesday.

**Comment by LordSimal** [comment]
That error would have to be somewhat `debug_kit` specific because middlewares are run everywhere (not only inside debug_kit)

Therefore if you have an error in your middleware it would be shown in the "normal" window, not the DebugKit window.

But if you find a way how to reproduce that it would be awesome 👍🏻

**Comment by hacheraw** [comment]
If I recall correctly, I was playing with redirects when the url has /es /de, etc...
And someway it made the app work but /debug-kit route was not loading.

So try making /debug-kit route not loading or wait for me to try to reproduce.

Sorry, I'm not at home/work now

**Comment by LordSimal** [comment]
I'll try that, thanks 👍🏻 
And no stress, thanks for the response after quite some time ^^

**Comment by hacheraw** [comment]
**Use this!**
The middleware will redirect debug_kit request to a non-existent Controller.
Then, debug_kit will try to load another debug_kit inside it so it will be an iframe inside an iframe but, hey, It will not load for sure!

What I don't know is if you can detect that debug_kit is not properly loaded and add the `40%` height and width to the iframe...

### src/Application.php
```php
use App\Middleware\BuggyMiddleware;
```
```php
$middlewareQueue
    ->add(new BuggyMiddleware())
    // ->add other middlewares...
```

### src/Middleware/BuggyMiddleware.php
```php
<?php

declare(strict_types=1);

namespace App\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Psr\Http\Server\MiddlewareInterface;
use Laminas\Diactoros\Response\RedirectResponse;

class BuggyMiddleware implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $path = $request->getUri()->getPath();

        if (preg_match('/^\/debug.*/i', $path)) {
            return $response = new RedirectResponse(
                $request->getAttribute('webroot') . 'non-existent-route'
            );
        }

        $response = $handler->handle($request);

        return $response;
    }
}
```

**Comment by LordSimal** [comment]
Gotta say I am not really sure how much safety checks we should implement here...
Especially the `debug-kit/toolbar/` part of the URL to load the iframe content is [hard-coded](https://github.com/cakephp/debug_kit/blob/4.x/webroot/js/inject-iframe.js#L49) in the JS so (currently) it has to stay the same.

**Comment by LordSimal** [comment]
After talking with the team we came to the conclussion that an enabled DebugKit (which should only be in local/dev instances anyway) requires the pre-configured URLs starting with `/debug-kit` to be available and not redirected by any other code parts.
