### ISSUE TITLE
TimerPanel causes deprecation warning in Cake 4.4.0

### ISSUE THREAD

**Issue by LordSimal** [cakephp/debug_kit#870]
After upgrading to CakePHP 4.4.0 the following deprecation warning is permanently present in the `Deprecations` tab:

```
CAKE/Event/EventManager.php:102
Registering multiple methods with an event is deprecated. Assign a single method and call others from it. 
<my-path>/vendor/cakephp/cakephp/src/Event/EventManager.php, line: 102 
You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`. 
Adding `vendor/cakephp/cakephp/src/Event/EventManager.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` config will mute deprecations from that file only.
```

The root cause of this is the change made in https://github.com/cakephp/cakephp/pull/16530

The current TimerPanel implementation uses exactly that feature, see https://github.com/cakephp/debug_kit/blob/4.x/src/Panel/TimerPanel.php#L51

Therefore this change was reverted in https://github.com/cakephp/cakephp/pull/16552 and will be released in Cake 4.4.1

The main question now is: Can we implement the `TimerPanel` functionality in a different way so we can still add that deprecation in the core?

**Comment by markstory** [comment]
> The main question now is: Can we implement the TimerPanel functionality in a different way so we can still add that deprecation in the core?

We could not use `implementedEvents` and register all the event handlers manually.

**Comment by othercorey** [comment]
Regardless, this indicates closures are actually supported which means the idea of deprecating attaching multiple class methods doesn't work. Unfortunately, I was too lost in the code to realize this.

**Comment by LordSimal** [comment]
4.4.1 has now been released and this issue is no longer present. Therefore I will close this issue
