### ISSUE TITLE
Tasks for cake5 branch

### ISSUE THREAD

**Issue by ADmad** [cakephp/debug_kit#880]
- [ ] Figure out why the table schema are missing when running the testuite on GA. 
- [x] Add back authorization plugin to "require-dev" when it has a Cake 5 compatible branch.
- [ ] Update LazyTableTrait for schema creation. TestFixture::create() no longer exists.
- [x] Use [named arguments for finders](https://github.com/cakephp/cakephp/pull/17108) - see https://github.com/cakephp/debug_kit/pull/931

**Comment by othercorey** [comment]
Marked authorization dependency done

**Comment by LordSimal** [comment]
I am not really sure what to do here because LazyTableTrait adjustments have already been done in https://github.com/cakephp/debug_kit/pull/881 and I don't see any problems related to table schema creation just in Github Actions 🤔

**Comment by markstory** [comment]
Last time I checked debugkit was working well in 5.x.

**Comment by dereuromark** [comment]
Is this still valid? With release of 5.0.0 and https://github.com/cakephp/debug_kit/releases/tag/5.0.1 ?

**Comment by LordSimal** [comment]
This can be closed
