### ISSUE TITLE
Allow debug kit on CLI

### ISSUE THREAD

**Issue by raul338** [cakephp/debug_kit#886]
Hello.

I integrated [road runner](https://roadrunner.dev/) in a cakephp app.
Everything seems to work fine except for debug kit. Because of this line

https://github.com/cakephp/debug_kit/blob/cd05c7b0d5600308683dc9911c3ff3e4fbe9d590/src/Plugin.php#L50

Roadrunner launches php scripts as CLI, so theres no way to load the plugin.

I suggest adding a config like `forceEnable` but for cli, like `enableCli` or similar

Refs #240

**Comment by markstory** [comment]
> I suggest adding a config like forceEnable but for cli, like enableCli or similar

We could move the cli/phpdbg checks into `isEnabled()` and override all of that logic if `forceEnable` is set. I don't think we need additional options added.
