### ISSUE TITLE
A dump of the `panels` table takes 17 GB

### ISSUE THREAD

**Issue by mehov** [cakephp/debug_kit#892]
Hey everyone,

I was looking into why do my backups take so long to complete, and discovered that the dump of the panels table takes whopping 17 GB. Before I investigate further, is there an obvious flag of some kind or auto-cleanup cron job that I'm missing?

Is it safe to `TRUNCATE` the table? Is it my job to do it regularly? (My hotfix for now will be to manually exclude it from the backup command.)

My CakePHP is 3.8.8 and the debug_kit version is 3.15.0. Please let me know if I need to post anything else.

Thank you!

**Comment by ndm2** [comment]
There is garbage collection in DebugKit, but previously it ran on a time based check that had a very low chance to actually be satisfied, resulting in what you're seeing, huge databases.

This has been change to a random based check as of `3.22.4` and `4.1.2`, which will trigger GC much more often. So the solution for you should be to upgrade your debug kit dependency accordingly.

**Comment by mehov** [comment]
Got it, thank you for helping Oliver!
