### ISSUE TITLE
DebugKit is not able to connect to the database. (SQLite installed and enabled)

### ISSUE THREAD

**Issue by nrj4all** [cakephp/debug_kit#894]
Hello,

I've installed CakePHP 4.4.7 successfully on my machine via latest Composer version, configured DB Connection by changing username, password and database name in config/app_local.php. Nothing else happened.

When I open the page I'm facing the DebugKit error message that is informing me about a not working DebugKit.

> DebugKit is not able to connect to the database. The datasource configuration "debug_kit" was not found.

![cakephp](https://user-images.githubusercontent.com/22965121/199000011-389c7cf1-8fc1-4316-be12-cb0823b40cfb.png)

After investigating the problem I noticed that SQLite is necessary. But unfortunately it is already installed.

![phpinfo](https://user-images.githubusercontent.com/22965121/199000309-d2c5de57-d34b-45e8-ba4c-b97cb329e575.png)

**My environment:**
- Raspbian Linux 11
- PHP 8.1.12
- Apache 2.4.54
- SQLite 3.34.1

**Comment by garas** [comment]
Check error log, it might contain more information.

Possible reason is you are running DebugKit on unsafe TLD without whitelistening it or force enabling.

**Comment by nrj4all** [comment]
Hi,

this solved the problem.  Thank you very much! I tried it before with the full domain and that did not work.

src/Application.php
`        if (Configure::read('debug')) {`
`        	Configure::write('DebugKit.safeTld', ['de']);`
`        	// instead of`
`        	//Configure::write('DebugKit.safeTld', ['domain.de']);`
`            $this->addPlugin('DebugKit');`
`        }`

LG PD

**Comment by LordSimal** [comment]
@nrj4all Well the config key is called `safeTld` so top level domain 😉 
There is also an example in the docs for that https://book.cakephp.org/debugkit/4/en/index.html#configuration

We can't know on which domain you are going to deploy/create your initial cakephp application, therefore we can't just whitelist all top level domains. The default whitelisted top level domains are `'localhost', 'invalid', 'test', 'example', 'local'` so if you have e.g. a local environment which uses one of those top level domains it will work out of the box.

Just so you understand why this has happened 😄
