### ISSUE TITLE
DebugKit with cakephp 4.4.10 on php 8.2 does not show deprecations

### ISSUE THREAD

**Issue by web010** [cakephp/debug_kit#908]
Using DebugKit in my cakephp 4.4.10 application does not show the deprecation-messages in de Debug-kits Deprecations-panel (is empty). Deprecated-messages are shown on the webpage instead. All other DebugKit panels are working correct.
Any idea why?

**Comment by othercorey** [comment]
Are you talking about PHP deprecation messages or CakePHP deprecation messages?

**Comment by web010** [comment]
cakephp deprecation, like 'Creation of dynamic property Acl\Model\Table\PermissionsTable::$Aro is deprecated'

**Comment by web010** [comment]
cakephp deprecation, f.e.  'Creation of dynamic property Acl\Model\Table\PermissionsTable::$Aro is deprecated'

**Comment by othercorey** [comment]
That should be a PHP deprecation from https://wiki.php.net/rfc/deprecate_dynamic_properties.

However, I think the problem might be version conflicts. debug_kit was updated to use new exception with the new Trap system introduced in CakePHP 4.4. 

What version of debug_kit are you using? Did you just upgrade to CakePHP 4.4?

**Comment by web010** [comment]
composer lock says “version": "4.9.2”

**Comment by othercorey** [comment]
Are you using the new ErrorTrap in CakePHP 4.4?

**Comment by web010** [comment]
Yes, in bootstrap.php I have replaced the old ConsoleErrorHandler and ErrorHandler with
 
(new ErrorTrap(Configure::read('Error')))->register();
(new ExceptionTrap(Configure::read('Error')))->register();
 
Somehow DebugKit seems to come to late to catch the deprecations...

**Comment by web010** [comment]
It seems to work now. Maybe some caching and last change in bootstrap with 
 
(new ErrorTrap(Configure::read('Error')))->register();
(new ExceptionTrap(Configure::read('Error')))->register();
 
thanks for your support
