### ISSUE TITLE
Toolbar is rendering with scrollbars on non-fullscreen sizes

### ISSUE THREAD

**Issue by othercorey** [cakephp/debug_kit#926]
The cake icon on the right appears to be in the wrong spot when expanded. When the toolbar is collapsed, the icon is rendered correctly.

![image](https://user-images.githubusercontent.com/24221186/221890955-798750cd-a476-4caa-8dd7-99c212bed75c.png)

![image](https://user-images.githubusercontent.com/24221186/221891215-4cf1f2b1-c5f2-48b1-a76e-c7ec4c0571a0.png)

**Comment by LordSimal** [comment]
What do I have to do to reproduce this problem? I am unable to reproduce this with debug_kit 4.9.3
Which browser are you using (on what OS)
What Viewport size do you have in your screenshot?

**Comment by othercorey** [comment]
I'm not sure exactly how you'd reproduce it if you can't just by viewport size. It seems to switch to this view at around 1485px width.

This is using Chrome (latest) on Windows 11.

**Comment by LordSimal** [comment]
ah, windows is the culprit here 😄 
I can reproduce it now and will try to find a solution 👍🏻

**Comment by othercorey** [comment]
> ah, windows is the culprit here 😄 I can reproduce it now and will try to find a solution 👍🏻

Strange that behaves differently. It happens the same on Edge which makes sense.

**Comment by LordSimal** [comment]
Actually... are you on the latest version of debug kit?
This sounds very familiar to https://github.com/cakephp/debug_kit/issues/888
Which was released with [4.9.1](https://github.com/cakephp/debug_kit/releases/tag/4.9.1)

I was only able to reproduce it on my Windows Machine with an old CakePHP 4.4.7 installation which didn't have that 4.9.1+ Debug Kit installed.

**Comment by othercorey** [comment]
Seems I am on 4.9.0 for some reason. The packages were updated, but guess this one wasn't.

The icon still pops out of place, but it is more usable now.

**Comment by othercorey** [comment]
Working as expected with the new release. I apparently had some unknown issue causing it still show old behavior after updating the first time.
