### ISSUE TITLE
Errors if default Cache invalid --> doesn't follow fallback like core

### ISSUE THREAD

**Issue by umer936** [cakephp/debug_kit#927]
![image](https://user-images.githubusercontent.com/2078163/227308967-a1fa6e3e-719e-4205-9ac2-0f6c1380eab5.png)

```php
$redisHost = 'https://google.com';
$redisPort = 6379;
```
```php
    'Cache' => [
        'default' => [
            'className' => RedisEngine::class,
            'prefix' => 'site_',
            'host' => $redisHost,
            'port' => $redisPort,
            'fallback' => 'default_file',
        ],
        'default_file' => [
            'className' => FileEngine::class,
            'path' => CACHE,
            'url' => env('CACHE_DEFAULT_URL', null),
        ],
    ],
```
(repeat for all the `_cake_*` Cache configs) 

With `debug = false`, DebugKit does not load and the site behaves correctly. The Cache falls back to the `FileEngine`. But with DebugKit on, it throws the error above. If `$redisHost` is valid, it uses the redis cache as expected.

**Comment by ajibarra** [comment]
Hi @umer936,

Thanks for reporting. 

On DebugEngine::init, it does not take 'fallback' config into account so if Redis connection fails the actual engine is not initialized properly. It needs to implement something like Cache::_buildEngine()::L159.

I will prepare a MR and a couple of unit tests to fix the issue.

**Comment by ADmad** [comment]
Couldn't the issue be solved by making the following change to `CachePanel`? This won't need any change to the core. Only drawback of this patch is cache engine instances will be preemptively created even if they are not used. But I don't think that's an issue during development.

```diff
diff --git a/src/Panel/CachePanel.php b/src/Panel/CachePanel.php
index 0265157e..be9afc49 100644
--- a/src/Panel/CachePanel.php
+++ b/src/Panel/CachePanel.php
@@ -55,9 +55,15 @@ class CachePanel extends DebugPanel
             if (isset($config['className']) && $config['className'] instanceof DebugEngine) {
                 $instance = $config['className'];
             } elseif (isset($config['className'])) {
-                Cache::drop($name);
-                $instance = new DebugEngine($config, $name, $this->logger);
+                $engine = Cache::pool($name);
+                // Unload from the cache registry so that subsequence calls to
+                // Cache::pool($name) use the new config with DebugEngine instance set below.
+                Cache::getRegistry()->unload($name);
+
+                $instance = new DebugEngine($engine, $name, $this->logger);
                 $config['className'] = $instance;
+
+                Cache::drop($name);
                 Cache::setConfig($name, $config);
             }
             if (isset($instance)) {
```
