### ISSUE TITLE
Introspect pagination results

### ISSUE THREAD

**Issue by dereuromark** [cakephp/debug_kit#928]
Currently, you have to pass the ResultSetDecorator into the view
->toArray() doesnt work, as the pagination needs those pagination data passed inside (at least in future versions for sure).
But that leads to this:

![vars](https://user-images.githubusercontent.com/39854/231403482-6b4cd8c3-513f-40c3-a4a1-32ef83ba2c7f.png)

It would be nice if there was an easy way to look into the actual results behind it instead of having to dd() or otherwise introspect the variable in the template (or controller) then manually.

**Comment by LordSimal** [comment]
This is fixed with the next CakePHP 4.5 minor update. See linked PR's
