### ISSUE TITLE
Call to undefined function DebugKit\env() in ToolbarService

### ISSUE THREAD

**Issue by BGehrels** [cakephp/debug_kit#961]
Since the env-function has been removed from the global namespace with Cake 5, DebugKit should explicitly import it.

**Comment by LordSimal** [comment]
I am unable to reproduce your problem.

**Comment by LordSimal** [comment]
I guess this can happen if one doesn't [opt into the global functions](https://github.com/cakephp/app/blob/5.x/config/bootstrap.php#L52)

**Comment by ADmad** [comment]
@BGehrels Can you make a PR to add required `use` statement for the function?
