### ISSUE TITLE
CakePHP 5 + Elasticsearch 4 causes an error "Call to undefined method Elastica\Client::getLogger()"

### ISSUE THREAD

**Issue by Christopher-HM** [cakephp/debug_kit#970]
Hello,

When I install CakePHP 5 + Elasticsearch 4, I get an error:
`Call to undefined method Elastica\Client::getLogger()`

This error comes from the file:
`ROOT/vendor/cakephp/debug_kit/src/Panel/SqlLogPanel.php, line 60`

```php
$logger = $connection->getDriver()->getLogger();
```

Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-137-generic x86_64)
PHP 8.2.1

Install:
```
composer create-project --prefer-dist cakephp/app ./
composer require cakephp/elastic-search -W
```

To install Elasticsearch, you must pass the option --with-all-dependencies (-W), which results in a downgrading 
`react/promise (v3.0.0 => v2.10.0)`

It will also be necessary to add the configuration for elastic :

```php
'Datasources' => [
        'elastic' => [
            'className' => ElasticSearchConnection::class,
            'driver' => ElasticSearchConnection::class,
            'host' => '0.0.0.0',
            'port' => 9200,
            'transport' => 'https',
            'username' => 'elastic',
            'password' => 'verysecret',
        ],
    ],
```

Thanks

**Comment by Christopher-HM** [comment]
Hi @LordSimal ,

I have just tested the code of the "5.x-elastic-logger" branch, the initial error has disappeared, but as soon as we make a request `$VideosIndex->find()->count()`, we get another error.

I am attaching a screenshot.
Don't hesitate if you want me to take another test.

![CaptureElastic](https://github.com/cakephp/debug_kit/assets/149246172/2769c2f6-7a72-4ed1-8c96-9e44ffe13ee9)

**Comment by LordSimal** [comment]
@markstory should we skip the `isSchemaQuery()` check if no query instance can be found in the given log context?

**Comment by markstory** [comment]
> should we skip the isSchemaQuery() check if no query instance can be found in the given log context?

That would work. If there is no `query` in the context we can't capture much related queries. We could also relax the type on `isSchemaQuery` to allow nulls and return early :shrug:

**Comment by Christopher-HM** [comment]
Hello,

Happy New Year and best wishes for 2024.

Do you know if the correction will be included in a future release?

THANKS.

**Comment by LordSimal** [comment]
@Christopher-HM I am still waiting in your repsonse in https://github.com/cakephp/debug_kit/pull/971 if this actually works.

But let me adjust the PR to not check `isSchemaQuery()` if no query is present at all

**Comment by Christopher-HM** [comment]
There was a misunderstanding.
I replied to you [https://github.com/cakephp/debug_kit/issues/970#issuecomment-1785762155](https://github.com/cakephp/debug_kit/issues/970#issuecomment-1785762155)
Yes it works but there was another error with `isSchemaQuery`.
Don't hesitate if you want me to do some tests with Elastic ;)

**Comment by LordSimal** [comment]
I have adjust the PR to also check for the `isSchemaQuery`
Can you check that out again?

**Comment by Christopher-HM** [comment]
I just did the test, no more error messages.
There is a warning `Undefined array key "query"`
I took a screenshot with the contents of the `$context` variable (see capture 1)
The SQL log does not display anything unlike the old version with CakePHP 4 (see screenshot 2)

![Capture](https://github.com/cakephp/debug_kit/assets/149246172/360f0593-52b4-420f-81c0-c8cd5d21a433)
![CaptureBefore](https://github.com/cakephp/debug_kit/assets/149246172/1eb072ce-fc1c-488c-9534-a08170b91e86)

**Comment by LordSimal** [comment]
Ah, I thought we didn't display anything previously...

**Comment by Christopher-HM** [comment]
Yes, that’s why I attached a screenshot :)

**Comment by LordSimal** [comment]
@Christopher-HM According to your screenshot the current version of the PR should lead to better results.

**Comment by Christopher-HM** [comment]
It's already much better.
We're not far LOL
There is another error (see screenshot)
![Capture2](https://github.com/cakephp/debug_kit/assets/149246172/65c45daa-6085-409c-a3d4-1518f9033f10)

**Comment by LordSimal** [comment]
ah right, it expects a query string...

**Comment by LordSimal** [comment]
I had to add another flag to the queries array inside the DebugLog so we can differentiate between SQL queries and non SQL queries. Please try again with the latest version of that branch.

**Comment by Christopher-HM** [comment]
Yes, I think the `$context['request']` should be serialized but not completely

Old capture
![CaptureOld](https://github.com/cakephp/debug_kit/assets/149246172/8ebee1de-51fc-4e69-be50-37c07c40437d)

New One
![CaptureNew](https://github.com/cakephp/debug_kit/assets/149246172/1ee9c878-1d90-46e3-b427-0060888f4f52)

**Comment by LordSimal** [comment]
what would you then log if not the whole request?

**Comment by Christopher-HM** [comment]
Here are some changes:

In `DebugLog.php`
```php
...

$this->_queries[] = [
    //'isSqlQuery' => false,
    'query' => json_encode([
        'method' => $context['request']['method'],
        'path' => $context['request']['path'],
        'data' => $context['request']['data'],
    ], JSON_PRETTY_PRINT),
    'took' => $context['response']['took'] ?: 0,
    'rows' => $context['response']['hits']['total']['value'] ?? $context['response']['hits']['total'] ?? 0,
];

....

$this->_queries[] = [
    //'isSqlQuery' => true,
    'query' => (string)$query,
    'took' => $data['took'],
    'rows' => $data['numRows'],
];
```

In `sql_log_panel.php` revert to old version
```PHP
<?php foreach ($queries as $query) : ?>
<tr>
    <td>
        <?php
            echo (new SqlFormatter(
                new HtmlHighlighter([
                    HtmlHighlighter::HIGHLIGHT_QUOTE => 'style="color: #004d40;"',
                    HtmlHighlighter::HIGHLIGHT_BACKTICK_QUOTE => 'style="color: #26a69a;"',
                    HtmlHighlighter::HIGHLIGHT_NUMBER => 'style="color: #ec407a;"',
                    HtmlHighlighter::HIGHLIGHT_WORD => 'style="color: #9c27b0;"',
                    HtmlHighlighter::HIGHLIGHT_PRE => 'style="color: #222; background-color: transparent;"',
                ])
            ))
            ->format($query['query']);
         ?>
    </td>
    <td><?= h($query['rows']) ?></td>
    <td><?= h($query['took']) ?></td>
</tr>
<?php endforeach; ?>
```

From my side, everything is good (see capture)

![CaptureOk](https://github.com/cakephp/debug_kit/assets/149246172/094d0341-708c-46f2-a133-ba21ccb481c9)

**Comment by LordSimal** [comment]
I have now applied your changes to the PR

**Comment by Christopher-HM** [comment]
Great. I just tested the code, nothing to report :)
THANKS!

**Comment by LordSimal** [comment]
This fix has now been released in https://github.com/cakephp/debug_kit/releases/tag/5.0.5
