### ISSUE TITLE
CakePHP 4.4.18 - DebugKit 4.9.5 - The view for PanelsController::index() was not found.

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/debug_kit#972]
Screenshot:

![image](https://github.com/cakephp/debug_kit/assets/17245982/1385daaf-22ec-4166-8e1b-c1339c3a4489)

Steps to reproduce:

Have some cakePHP project opened with debug kit enabled.
Then navigate through your page, so that you have history entries in debug kit.
Open the history, click the 'Reload' - button and then select any of the history entries.
Voila the error in the screenshot appearing.

Stack-Trace Screenshots (maybe it is dependent to some othe package or plugin?
![image](https://github.com/cakephp/debug_kit/assets/17245982/e914da44-a337-4bcd-9cae-3465c1858d3e)
![image](https://github.com/cakephp/debug_kit/assets/17245982/6862ed34-790f-43f1-b045-813b72c5d8cb)

So if you need more details or so one, don't hesitate to reply.

**Comment by Manuel1948** [comment]
composer.json:
```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=7.4",
        "cakephp/cakephp": "4.4.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "*",
        "cakephp/plugin-installer": "*",
        "cakephp/authentication": "*",
        "cakephp/authorization": "*",
        "cakephp/acl": "*",
        "muffin/footprint": "*",
        "queencitycodefactory/ldap": "dev-master",
        "phpoffice/phpspreadsheet": "1.*"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "4.*",
        "cakephp/bake": "*"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src",
            "FilterExport\\": "./plugins/FilterExport/src"
        }
    },
    "minimum-stability": "beta",
    "prefer-stable": true,
    "config": {
        "allow-plugins": {
            "cakephp/plugin-installer": true
        }
    }
}
```

All running on PHP 8.2

**Comment by ndm2** [comment]
The variables panel has the same underlying problem, a `loadPanel()` call with the wrong panel type value, containing a `panel` prefix.

**Comment by LordSimal** [comment]
@Manuel1948 can you please test the changes proposed in the linked PR? Its just 2 JS files you can directly adjust in your `vendor/cakephp/debug_kit` folder (or you adjust your composer.json to the branch I created)

**Comment by Manuel1948** [comment]
> @Manuel1948 can you please test the changes proposed in the linked PR? Its just 2 JS files you can directly adjust in your `vendor/cakephp/debug_kit` folder (or you adjust your composer.json to the branch I created)

Thank you for the quick fix, problem is now solved.

I am no extensive github user, could you tell me how I know, when this fix is public so that composer update is getting the new version?

**Comment by Manuel1948** [comment]
Fixed.

**Comment by LordSimal** [comment]
We just released

* https://github.com/cakephp/debug_kit/releases/tag/4.9.6
* https://github.com/cakephp/debug_kit/releases/tag/4.10.1
* https://github.com/cakephp/debug_kit/releases/tag/5.0.3

which all contain that fix so you should be able to just do a `composer update -W`
